# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from opensqt.market_maker.v1 import position_pb2 as opensqt_dot_market__maker_dot_v1_dot_position__pb2


class PositionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPositions = channel.unary_unary(
                '/opensqt.market_maker.v1.PositionService/GetPositions',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionsRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionsResponse.FromString,
                _registered_method=True)
        self.GetPosition = channel.unary_unary(
                '/opensqt.market_maker.v1.PositionService/GetPosition',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionResponse.FromString,
                _registered_method=True)
        self.SubscribePositions = channel.unary_stream(
                '/opensqt.market_maker.v1.PositionService/SubscribePositions',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceSubscribePositionsRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionUpdate.FromString,
                _registered_method=True)
        self.GetOpenOrders = channel.unary_unary(
                '/opensqt.market_maker.v1.PositionService/GetOpenOrders',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOpenOrdersRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOpenOrdersResponse.FromString,
                _registered_method=True)
        self.GetOrderHistory = channel.unary_unary(
                '/opensqt.market_maker.v1.PositionService/GetOrderHistory',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderHistoryRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderHistoryResponse.FromString,
                _registered_method=True)
        self.GetOrder = channel.unary_unary(
                '/opensqt.market_maker.v1.PositionService/GetOrder',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderResponse.FromString,
                _registered_method=True)
        self.GetFills = channel.unary_unary(
                '/opensqt.market_maker.v1.PositionService/GetFills',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetFillsRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetFillsResponse.FromString,
                _registered_method=True)
        self.GetPositionHistory = channel.unary_unary(
                '/opensqt.market_maker.v1.PositionService/GetPositionHistory',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionHistoryRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionHistoryResponse.FromString,
                _registered_method=True)
        self.GetRealizedPnL = channel.unary_unary(
                '/opensqt.market_maker.v1.PositionService/GetRealizedPnL',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetRealizedPnLRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetRealizedPnLResponse.FromString,
                _registered_method=True)
        self.GetUnrealizedPnL = channel.unary_unary(
                '/opensqt.market_maker.v1.PositionService/GetUnrealizedPnL',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetUnrealizedPnLRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetUnrealizedPnLResponse.FromString,
                _registered_method=True)


class PositionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPositions(self, request, context):
        """Query positions
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribePositions(self, request, context):
        """Subscribe to position updates (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOpenOrders(self, request, context):
        """Query orders
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrderHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFills(self, request, context):
        """Query fills
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositionHistory(self, request, context):
        """Position history
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRealizedPnL(self, request, context):
        """PnL queries
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUnrealizedPnL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PositionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPositions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositions,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionsRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionsResponse.SerializeToString,
            ),
            'GetPosition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPosition,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionResponse.SerializeToString,
            ),
            'SubscribePositions': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribePositions,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceSubscribePositionsRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionUpdate.SerializeToString,
            ),
            'GetOpenOrders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOpenOrders,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOpenOrdersRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOpenOrdersResponse.SerializeToString,
            ),
            'GetOrderHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrderHistory,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderHistoryRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderHistoryResponse.SerializeToString,
            ),
            'GetOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOrder,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderResponse.SerializeToString,
            ),
            'GetFills': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFills,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetFillsRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetFillsResponse.SerializeToString,
            ),
            'GetPositionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositionHistory,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionHistoryRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionHistoryResponse.SerializeToString,
            ),
            'GetRealizedPnL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRealizedPnL,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetRealizedPnLRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetRealizedPnLResponse.SerializeToString,
            ),
            'GetUnrealizedPnL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUnrealizedPnL,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetUnrealizedPnLRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetUnrealizedPnLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'opensqt.market_maker.v1.PositionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('opensqt.market_maker.v1.PositionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PositionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/GetPositions',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionsRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPosition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/GetPosition',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribePositions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/SubscribePositions',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceSubscribePositionsRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOpenOrders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/GetOpenOrders',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOpenOrdersRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOpenOrdersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrderHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/GetOrderHistory',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderHistoryRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/GetOrder',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetOrderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/GetFills',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetFillsRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetFillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/GetPositionHistory',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionHistoryRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetPositionHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRealizedPnL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/GetRealizedPnL',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetRealizedPnLRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetRealizedPnLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUnrealizedPnL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.PositionService/GetUnrealizedPnL',
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetUnrealizedPnLRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_position__pb2.PositionServiceGetUnrealizedPnLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
