# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from opensqt.market_maker.v1 import risk_pb2 as opensqt_dot_market__maker_dot_v1_dot_risk__pb2


class RiskServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRiskMetrics = channel.unary_unary(
                '/opensqt.market_maker.v1.RiskService/GetRiskMetrics',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetRiskMetricsRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetRiskMetricsResponse.FromString,
                _registered_method=True)
        self.GetPositionLimits = channel.unary_unary(
                '/opensqt.market_maker.v1.RiskService/GetPositionLimits',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetPositionLimitsRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetPositionLimitsResponse.FromString,
                _registered_method=True)
        self.UpdatePositionLimits = channel.unary_unary(
                '/opensqt.market_maker.v1.RiskService/UpdatePositionLimits',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.UpdatePositionLimitsRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.UpdatePositionLimitsResponse.FromString,
                _registered_method=True)
        self.GetExposure = channel.unary_unary(
                '/opensqt.market_maker.v1.RiskService/GetExposure',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetExposureRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetExposureResponse.FromString,
                _registered_method=True)
        self.SubscribeRiskAlerts = channel.unary_stream(
                '/opensqt.market_maker.v1.RiskService/SubscribeRiskAlerts',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.SubscribeRiskAlertsRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.RiskAlert.FromString,
                _registered_method=True)
        self.TriggerReconciliation = channel.unary_unary(
                '/opensqt.market_maker.v1.RiskService/TriggerReconciliation',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.TriggerReconciliationRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.TriggerReconciliationResponse.FromString,
                _registered_method=True)
        self.GetReconciliationStatus = channel.unary_unary(
                '/opensqt.market_maker.v1.RiskService/GetReconciliationStatus',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetReconciliationStatusRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetReconciliationStatusResponse.FromString,
                _registered_method=True)
        self.GetCircuitBreakerStatus = channel.unary_unary(
                '/opensqt.market_maker.v1.RiskService/GetCircuitBreakerStatus',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetCircuitBreakerStatusRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetCircuitBreakerStatusResponse.FromString,
                _registered_method=True)
        self.OpenCircuitBreaker = channel.unary_unary(
                '/opensqt.market_maker.v1.RiskService/OpenCircuitBreaker',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.OpenCircuitBreakerRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.OpenCircuitBreakerResponse.FromString,
                _registered_method=True)
        self.CloseCircuitBreaker = channel.unary_unary(
                '/opensqt.market_maker.v1.RiskService/CloseCircuitBreaker',
                request_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.CloseCircuitBreakerRequest.SerializeToString,
                response_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.CloseCircuitBreakerResponse.FromString,
                _registered_method=True)


class RiskServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetRiskMetrics(self, request, context):
        """Query risk metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPositionLimits(self, request, context):
        """Query position limits
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePositionLimits(self, request, context):
        """Update position limits (admin only)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExposure(self, request, context):
        """Get current exposure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeRiskAlerts(self, request, context):
        """Subscribe to risk alerts (streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerReconciliation(self, request, context):
        """Trigger manual reconciliation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReconciliationStatus(self, request, context):
        """Get reconciliation status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCircuitBreakerStatus(self, request, context):
        """Circuit breaker control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenCircuitBreaker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseCircuitBreaker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RiskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRiskMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRiskMetrics,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetRiskMetricsRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetRiskMetricsResponse.SerializeToString,
            ),
            'GetPositionLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPositionLimits,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetPositionLimitsRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetPositionLimitsResponse.SerializeToString,
            ),
            'UpdatePositionLimits': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePositionLimits,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.UpdatePositionLimitsRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.UpdatePositionLimitsResponse.SerializeToString,
            ),
            'GetExposure': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExposure,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetExposureRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetExposureResponse.SerializeToString,
            ),
            'SubscribeRiskAlerts': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeRiskAlerts,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.SubscribeRiskAlertsRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.RiskAlert.SerializeToString,
            ),
            'TriggerReconciliation': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerReconciliation,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.TriggerReconciliationRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.TriggerReconciliationResponse.SerializeToString,
            ),
            'GetReconciliationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReconciliationStatus,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetReconciliationStatusRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetReconciliationStatusResponse.SerializeToString,
            ),
            'GetCircuitBreakerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCircuitBreakerStatus,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetCircuitBreakerStatusRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetCircuitBreakerStatusResponse.SerializeToString,
            ),
            'OpenCircuitBreaker': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenCircuitBreaker,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.OpenCircuitBreakerRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.OpenCircuitBreakerResponse.SerializeToString,
            ),
            'CloseCircuitBreaker': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseCircuitBreaker,
                    request_deserializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.CloseCircuitBreakerRequest.FromString,
                    response_serializer=opensqt_dot_market__maker_dot_v1_dot_risk__pb2.CloseCircuitBreakerResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'opensqt.market_maker.v1.RiskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('opensqt.market_maker.v1.RiskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RiskService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetRiskMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/GetRiskMetrics',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetRiskMetricsRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetRiskMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPositionLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/GetPositionLimits',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetPositionLimitsRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetPositionLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePositionLimits(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/UpdatePositionLimits',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.UpdatePositionLimitsRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.UpdatePositionLimitsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExposure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/GetExposure',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetExposureRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetExposureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeRiskAlerts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/SubscribeRiskAlerts',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.SubscribeRiskAlertsRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.RiskAlert.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerReconciliation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/TriggerReconciliation',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.TriggerReconciliationRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.TriggerReconciliationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReconciliationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/GetReconciliationStatus',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetReconciliationStatusRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetReconciliationStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCircuitBreakerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/GetCircuitBreakerStatus',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetCircuitBreakerStatusRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.GetCircuitBreakerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenCircuitBreaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/OpenCircuitBreaker',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.OpenCircuitBreakerRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.OpenCircuitBreakerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseCircuitBreaker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/opensqt.market_maker.v1.RiskService/CloseCircuitBreaker',
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.CloseCircuitBreakerRequest.SerializeToString,
            opensqt_dot_market__maker_dot_v1_dot_risk__pb2.CloseCircuitBreakerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
