// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: opensqt/market_maker/v1/events.proto

package pb

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,3,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          OrderSide              `protobuf:"varint,5,opt,name=side,proto3,enum=opensqt.market_maker.v1.OrderSide" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,6,opt,name=type,proto3,enum=opensqt.market_maker.v1.OrderType" json:"type,omitempty"`
	Status        OrderStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=opensqt.market_maker.v1.OrderStatus" json:"status,omitempty"`
	Price         *decimal.Decimal       `protobuf:"bytes,8,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      *decimal.Decimal       `protobuf:"bytes,9,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ExecutedQty   *decimal.Decimal       `protobuf:"bytes,10,opt,name=executed_qty,json=executedQty,proto3" json:"executed_qty,omitempty"`
	AvgPrice      *decimal.Decimal       `protobuf:"bytes,11,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	LastTrade     *Trade                 `protobuf:"bytes,13,opt,name=last_trade,json=lastTrade,proto3" json:"last_trade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderUpdate) Reset() {
	*x = OrderUpdate{}
	mi := &file_opensqt_market_maker_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderUpdate) ProtoMessage() {}

func (x *OrderUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderUpdate.ProtoReflect.Descriptor instead.
func (*OrderUpdate) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderUpdate) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OrderUpdate) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderUpdate) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *OrderUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderUpdate) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *OrderUpdate) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *OrderUpdate) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderUpdate) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrderUpdate) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *OrderUpdate) GetExecutedQty() *decimal.Decimal {
	if x != nil {
		return x.ExecutedQty
	}
	return nil
}

func (x *OrderUpdate) GetAvgPrice() *decimal.Decimal {
	if x != nil {
		return x.AvgPrice
	}
	return nil
}

func (x *OrderUpdate) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *OrderUpdate) GetLastTrade() *Trade {
	if x != nil {
		return x.LastTrade
	}
	return nil
}

type PriceChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         *decimal.Decimal       `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceChange) Reset() {
	*x = PriceChange{}
	mi := &file_opensqt_market_maker_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceChange) ProtoMessage() {}

func (x *PriceChange) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceChange.ProtoReflect.Descriptor instead.
func (*PriceChange) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *PriceChange) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PriceChange) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceChange) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *PriceChange) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type FundingUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Exchange        string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol          string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Rate            *decimal.Decimal       `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`                                                 // Current interval funding rate (per-interval)
	PredictedRate   *decimal.Decimal       `protobuf:"bytes,4,opt,name=predicted_rate,json=predictedRate,proto3" json:"predicted_rate,omitempty"`          // Optional; next interval funding if provided by venue; unset if unknown
	NextFundingTime int64                  `protobuf:"varint,5,opt,name=next_funding_time,json=nextFundingTime,proto3" json:"next_funding_time,omitempty"` // Unix epoch milliseconds (UTC) for the start of the next funding interval; 0 if not applicable (e.g., spot)
	Timestamp       int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // Unix epoch milliseconds (UTC) when observed (exchange event time when available; else connector receipt time)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FundingUpdate) Reset() {
	*x = FundingUpdate{}
	mi := &file_opensqt_market_maker_v1_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingUpdate) ProtoMessage() {}

func (x *FundingUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingUpdate.ProtoReflect.Descriptor instead.
func (*FundingUpdate) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_events_proto_rawDescGZIP(), []int{2}
}

func (x *FundingUpdate) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *FundingUpdate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FundingUpdate) GetRate() *decimal.Decimal {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *FundingUpdate) GetPredictedRate() *decimal.Decimal {
	if x != nil {
		return x.PredictedRate
	}
	return nil
}

func (x *FundingUpdate) GetNextFundingTime() int64 {
	if x != nil {
		return x.NextFundingTime
	}
	return 0
}

func (x *FundingUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_opensqt_market_maker_v1_events_proto protoreflect.FileDescriptor

const file_opensqt_market_maker_v1_events_proto_rawDesc = "" +
	"\n" +
	"$opensqt/market_maker/v1/events.proto\x12\x17opensqt.market_maker.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/type/decimal.proto\x1a#opensqt/market_maker/v1/types.proto\x1a'opensqt/market_maker/v1/resources.proto\"\xdc\x04\n" +
	"\vOrderUpdate\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x03 \x01(\tR\rclientOrderId\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x126\n" +
	"\x04side\x18\x05 \x01(\x0e2\".opensqt.market_maker.v1.OrderSideR\x04side\x126\n" +
	"\x04type\x18\x06 \x01(\x0e2\".opensqt.market_maker.v1.OrderTypeR\x04type\x12<\n" +
	"\x06status\x18\a \x01(\x0e2$.opensqt.market_maker.v1.OrderStatusR\x06status\x12*\n" +
	"\x05price\x18\b \x01(\v2\x14.google.type.DecimalR\x05price\x120\n" +
	"\bquantity\x18\t \x01(\v2\x14.google.type.DecimalR\bquantity\x127\n" +
	"\fexecuted_qty\x18\n" +
	" \x01(\v2\x14.google.type.DecimalR\vexecutedQty\x121\n" +
	"\tavg_price\x18\v \x01(\v2\x14.google.type.DecimalR\bavgPrice\x12\x1f\n" +
	"\vupdate_time\x18\f \x01(\x03R\n" +
	"updateTime\x12=\n" +
	"\n" +
	"last_trade\x18\r \x01(\v2\x1e.opensqt.market_maker.v1.TradeR\tlastTrade\"\xa7\x01\n" +
	"\vPriceChange\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12*\n" +
	"\x05price\x18\x03 \x01(\v2\x14.google.type.DecimalR\x05price\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xf4\x01\n" +
	"\rFundingUpdate\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12(\n" +
	"\x04rate\x18\x03 \x01(\v2\x14.google.type.DecimalR\x04rate\x12;\n" +
	"\x0epredicted_rate\x18\x04 \x01(\v2\x14.google.type.DecimalR\rpredictedRate\x12*\n" +
	"\x11next_funding_time\x18\x05 \x01(\x03R\x0fnextFundingTime\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestampB\xbe\x01\n" +
	"\x1bcom.opensqt.market_maker.v1B\vEventsProtoP\x01Z\x18market_maker/internal/pb\xa2\x02\x03OMX\xaa\x02\x16Opensqt.MarketMaker.V1\xca\x02\x16Opensqt\\MarketMaker\\V1\xe2\x02\"Opensqt\\MarketMaker\\V1\\GPBMetadata\xea\x02\x18Opensqt::MarketMaker::V1b\x06proto3"

var (
	file_opensqt_market_maker_v1_events_proto_rawDescOnce sync.Once
	file_opensqt_market_maker_v1_events_proto_rawDescData []byte
)

func file_opensqt_market_maker_v1_events_proto_rawDescGZIP() []byte {
	file_opensqt_market_maker_v1_events_proto_rawDescOnce.Do(func() {
		file_opensqt_market_maker_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_events_proto_rawDesc), len(file_opensqt_market_maker_v1_events_proto_rawDesc)))
	})
	return file_opensqt_market_maker_v1_events_proto_rawDescData
}

var file_opensqt_market_maker_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_opensqt_market_maker_v1_events_proto_goTypes = []any{
	(*OrderUpdate)(nil),           // 0: opensqt.market_maker.v1.OrderUpdate
	(*PriceChange)(nil),           // 1: opensqt.market_maker.v1.PriceChange
	(*FundingUpdate)(nil),         // 2: opensqt.market_maker.v1.FundingUpdate
	(OrderSide)(0),                // 3: opensqt.market_maker.v1.OrderSide
	(OrderType)(0),                // 4: opensqt.market_maker.v1.OrderType
	(OrderStatus)(0),              // 5: opensqt.market_maker.v1.OrderStatus
	(*decimal.Decimal)(nil),       // 6: google.type.Decimal
	(*Trade)(nil),                 // 7: opensqt.market_maker.v1.Trade
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_opensqt_market_maker_v1_events_proto_depIdxs = []int32{
	3,  // 0: opensqt.market_maker.v1.OrderUpdate.side:type_name -> opensqt.market_maker.v1.OrderSide
	4,  // 1: opensqt.market_maker.v1.OrderUpdate.type:type_name -> opensqt.market_maker.v1.OrderType
	5,  // 2: opensqt.market_maker.v1.OrderUpdate.status:type_name -> opensqt.market_maker.v1.OrderStatus
	6,  // 3: opensqt.market_maker.v1.OrderUpdate.price:type_name -> google.type.Decimal
	6,  // 4: opensqt.market_maker.v1.OrderUpdate.quantity:type_name -> google.type.Decimal
	6,  // 5: opensqt.market_maker.v1.OrderUpdate.executed_qty:type_name -> google.type.Decimal
	6,  // 6: opensqt.market_maker.v1.OrderUpdate.avg_price:type_name -> google.type.Decimal
	7,  // 7: opensqt.market_maker.v1.OrderUpdate.last_trade:type_name -> opensqt.market_maker.v1.Trade
	6,  // 8: opensqt.market_maker.v1.PriceChange.price:type_name -> google.type.Decimal
	8,  // 9: opensqt.market_maker.v1.PriceChange.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 10: opensqt.market_maker.v1.FundingUpdate.rate:type_name -> google.type.Decimal
	6,  // 11: opensqt.market_maker.v1.FundingUpdate.predicted_rate:type_name -> google.type.Decimal
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_opensqt_market_maker_v1_events_proto_init() }
func file_opensqt_market_maker_v1_events_proto_init() {
	if File_opensqt_market_maker_v1_events_proto != nil {
		return
	}
	file_opensqt_market_maker_v1_types_proto_init()
	file_opensqt_market_maker_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_events_proto_rawDesc), len(file_opensqt_market_maker_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opensqt_market_maker_v1_events_proto_goTypes,
		DependencyIndexes: file_opensqt_market_maker_v1_events_proto_depIdxs,
		MessageInfos:      file_opensqt_market_maker_v1_events_proto_msgTypes,
	}.Build()
	File_opensqt_market_maker_v1_events_proto = out.File
	file_opensqt_market_maker_v1_events_proto_goTypes = nil
	file_opensqt_market_maker_v1_events_proto_depIdxs = nil
}
