// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: opensqt/market_maker/v1/exchange.proto

package pb

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNameRequest) Reset() {
	*x = GetNameRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNameRequest) ProtoMessage() {}

func (x *GetNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNameRequest.ProtoReflect.Descriptor instead.
func (*GetNameRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{0}
}

type GetNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNameResponse) Reset() {
	*x = GetNameResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNameResponse) ProtoMessage() {}

func (x *GetNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNameResponse.ProtoReflect.Descriptor instead.
func (*GetNameResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{1}
}

func (x *GetNameResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTypeRequest) Reset() {
	*x = GetTypeRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeRequest) ProtoMessage() {}

func (x *GetTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTypeRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{2}
}

type GetTypeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Type            ExchangeType           `protobuf:"varint,1,opt,name=type,proto3,enum=opensqt.market_maker.v1.ExchangeType" json:"type,omitempty"`
	IsUnifiedMargin bool                   `protobuf:"varint,2,opt,name=is_unified_margin,json=isUnifiedMargin,proto3" json:"is_unified_margin,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTypeResponse) Reset() {
	*x = GetTypeResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTypeResponse) ProtoMessage() {}

func (x *GetTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTypeResponse.ProtoReflect.Descriptor instead.
func (*GetTypeResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{3}
}

func (x *GetTypeResponse) GetType() ExchangeType {
	if x != nil {
		return x.Type
	}
	return ExchangeType_EXCHANGE_TYPE_UNSPECIFIED
}

func (x *GetTypeResponse) GetIsUnifiedMargin() bool {
	if x != nil {
		return x.IsUnifiedMargin
	}
	return false
}

type BatchPlaceOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*PlaceOrderRequest   `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPlaceOrdersRequest) Reset() {
	*x = BatchPlaceOrdersRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPlaceOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPlaceOrdersRequest) ProtoMessage() {}

func (x *BatchPlaceOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPlaceOrdersRequest.ProtoReflect.Descriptor instead.
func (*BatchPlaceOrdersRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{4}
}

func (x *BatchPlaceOrdersRequest) GetOrders() []*PlaceOrderRequest {
	if x != nil {
		return x.Orders
	}
	return nil
}

type BatchPlaceOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	AllSuccess    bool                   `protobuf:"varint,2,opt,name=all_success,json=allSuccess,proto3" json:"all_success,omitempty"`
	Errors        []*BatchOrderError     `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPlaceOrdersResponse) Reset() {
	*x = BatchPlaceOrdersResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPlaceOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPlaceOrdersResponse) ProtoMessage() {}

func (x *BatchPlaceOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPlaceOrdersResponse.ProtoReflect.Descriptor instead.
func (*BatchPlaceOrdersResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{5}
}

func (x *BatchPlaceOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *BatchPlaceOrdersResponse) GetAllSuccess() bool {
	if x != nil {
		return x.AllSuccess
	}
	return false
}

func (x *BatchPlaceOrdersResponse) GetErrors() []*BatchOrderError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type BatchOrderError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         int32                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"` // gRPC status code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchOrderError) Reset() {
	*x = BatchOrderError{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchOrderError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchOrderError) ProtoMessage() {}

func (x *BatchOrderError) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchOrderError.ProtoReflect.Descriptor instead.
func (*BatchOrderError) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{6}
}

func (x *BatchOrderError) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BatchOrderError) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *BatchOrderError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BatchOrderError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type CancelOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UseMargin     bool                   `protobuf:"varint,3,opt,name=use_margin,json=useMargin,proto3" json:"use_margin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderRequest) Reset() {
	*x = CancelOrderRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderRequest) ProtoMessage() {}

func (x *CancelOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderRequest.ProtoReflect.Descriptor instead.
func (*CancelOrderRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{7}
}

func (x *CancelOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *CancelOrderRequest) GetUseMargin() bool {
	if x != nil {
		return x.UseMargin
	}
	return false
}

type CancelOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderResponse) Reset() {
	*x = CancelOrderResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderResponse) ProtoMessage() {}

func (x *CancelOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderResponse.ProtoReflect.Descriptor instead.
func (*CancelOrderResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{8}
}

type BatchCancelOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderIds      []int64                `protobuf:"varint,2,rep,packed,name=order_ids,json=orderIds,proto3" json:"order_ids,omitempty"`
	UseMargin     bool                   `protobuf:"varint,3,opt,name=use_margin,json=useMargin,proto3" json:"use_margin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCancelOrdersRequest) Reset() {
	*x = BatchCancelOrdersRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCancelOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCancelOrdersRequest) ProtoMessage() {}

func (x *BatchCancelOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCancelOrdersRequest.ProtoReflect.Descriptor instead.
func (*BatchCancelOrdersRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{9}
}

func (x *BatchCancelOrdersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BatchCancelOrdersRequest) GetOrderIds() []int64 {
	if x != nil {
		return x.OrderIds
	}
	return nil
}

func (x *BatchCancelOrdersRequest) GetUseMargin() bool {
	if x != nil {
		return x.UseMargin
	}
	return false
}

type BatchCancelOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errors        []*BatchOrderError     `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCancelOrdersResponse) Reset() {
	*x = BatchCancelOrdersResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCancelOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCancelOrdersResponse) ProtoMessage() {}

func (x *BatchCancelOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCancelOrdersResponse.ProtoReflect.Descriptor instead.
func (*BatchCancelOrdersResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{10}
}

func (x *BatchCancelOrdersResponse) GetErrors() []*BatchOrderError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type CancelAllOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	UseMargin     bool                   `protobuf:"varint,2,opt,name=use_margin,json=useMargin,proto3" json:"use_margin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllOrdersRequest) Reset() {
	*x = CancelAllOrdersRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllOrdersRequest) ProtoMessage() {}

func (x *CancelAllOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllOrdersRequest.ProtoReflect.Descriptor instead.
func (*CancelAllOrdersRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{11}
}

func (x *CancelAllOrdersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CancelAllOrdersRequest) GetUseMargin() bool {
	if x != nil {
		return x.UseMargin
	}
	return false
}

type CancelAllOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAllOrdersResponse) Reset() {
	*x = CancelAllOrdersResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAllOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAllOrdersResponse) ProtoMessage() {}

func (x *CancelAllOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAllOrdersResponse.ProtoReflect.Descriptor instead.
func (*CancelAllOrdersResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{12}
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,3,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	UseMargin     bool                   `protobuf:"varint,4,opt,name=use_margin,json=useMargin,proto3" json:"use_margin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{13}
}

func (x *GetOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOrderRequest) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *GetOrderRequest) GetUseMargin() bool {
	if x != nil {
		return x.UseMargin
	}
	return false
}

type GetOpenOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	UseMargin     bool                   `protobuf:"varint,2,opt,name=use_margin,json=useMargin,proto3" json:"use_margin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenOrdersRequest) Reset() {
	*x = GetOpenOrdersRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenOrdersRequest) ProtoMessage() {}

func (x *GetOpenOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetOpenOrdersRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{14}
}

func (x *GetOpenOrdersRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetOpenOrdersRequest) GetUseMargin() bool {
	if x != nil {
		return x.UseMargin
	}
	return false
}

type GetOpenOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenOrdersResponse) Reset() {
	*x = GetOpenOrdersResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenOrdersResponse) ProtoMessage() {}

func (x *GetOpenOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetOpenOrdersResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{15}
}

func (x *GetOpenOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{16}
}

type GetPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsRequest) Reset() {
	*x = GetPositionsRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsRequest) ProtoMessage() {}

func (x *GetPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetPositionsRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{17}
}

func (x *GetPositionsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*Position            `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPositionsResponse) Reset() {
	*x = GetPositionsResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPositionsResponse) ProtoMessage() {}

func (x *GetPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetPositionsResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{18}
}

func (x *GetPositionsResponse) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         string                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{19}
}

func (x *GetBalanceRequest) GetAsset() string {
	if x != nil {
		return x.Asset
	}
	return ""
}

type GetBalanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Balance       *decimal.Decimal       `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceResponse) Reset() {
	*x = GetBalanceResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceResponse) ProtoMessage() {}

func (x *GetBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceResponse.ProtoReflect.Descriptor instead.
func (*GetBalanceResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{20}
}

func (x *GetBalanceResponse) GetBalance() *decimal.Decimal {
	if x != nil {
		return x.Balance
	}
	return nil
}

type GetLatestPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestPriceRequest) Reset() {
	*x = GetLatestPriceRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPriceRequest) ProtoMessage() {}

func (x *GetLatestPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPriceRequest.ProtoReflect.Descriptor instead.
func (*GetLatestPriceRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{21}
}

func (x *GetLatestPriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetLatestPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         *decimal.Decimal       `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestPriceResponse) Reset() {
	*x = GetLatestPriceResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestPriceResponse) ProtoMessage() {}

func (x *GetLatestPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestPriceResponse.ProtoReflect.Descriptor instead.
func (*GetLatestPriceResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{22}
}

func (x *GetLatestPriceResponse) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

type GetHistoricalKlinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoricalKlinesRequest) Reset() {
	*x = GetHistoricalKlinesRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoricalKlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoricalKlinesRequest) ProtoMessage() {}

func (x *GetHistoricalKlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoricalKlinesRequest.ProtoReflect.Descriptor instead.
func (*GetHistoricalKlinesRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{23}
}

func (x *GetHistoricalKlinesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetHistoricalKlinesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

func (x *GetHistoricalKlinesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoricalKlinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candles       []*Candle              `protobuf:"bytes,1,rep,name=candles,proto3" json:"candles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoricalKlinesResponse) Reset() {
	*x = GetHistoricalKlinesResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoricalKlinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoricalKlinesResponse) ProtoMessage() {}

func (x *GetHistoricalKlinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoricalKlinesResponse.ProtoReflect.Descriptor instead.
func (*GetHistoricalKlinesResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{24}
}

func (x *GetHistoricalKlinesResponse) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

type FetchExchangeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchExchangeInfoRequest) Reset() {
	*x = FetchExchangeInfoRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchExchangeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchExchangeInfoRequest) ProtoMessage() {}

func (x *FetchExchangeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchExchangeInfoRequest.ProtoReflect.Descriptor instead.
func (*FetchExchangeInfoRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{25}
}

func (x *FetchExchangeInfoRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type FetchExchangeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchExchangeInfoResponse) Reset() {
	*x = FetchExchangeInfoResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchExchangeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchExchangeInfoResponse) ProtoMessage() {}

func (x *FetchExchangeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchExchangeInfoResponse.ProtoReflect.Descriptor instead.
func (*FetchExchangeInfoResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{26}
}

type GetSymbolInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolInfoRequest) Reset() {
	*x = GetSymbolInfoRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolInfoRequest) ProtoMessage() {}

func (x *GetSymbolInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSymbolInfoRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{27}
}

func (x *GetSymbolInfoRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetSymbolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolsRequest) Reset() {
	*x = GetSymbolsRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolsRequest) ProtoMessage() {}

func (x *GetSymbolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolsRequest.ProtoReflect.Descriptor instead.
func (*GetSymbolsRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{28}
}

type GetSymbolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSymbolsResponse) Reset() {
	*x = GetSymbolsResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSymbolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSymbolsResponse) ProtoMessage() {}

func (x *GetSymbolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSymbolsResponse.ProtoReflect.Descriptor instead.
func (*GetSymbolsResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{29}
}

func (x *GetSymbolsResponse) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type GetFundingRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundingRateRequest) Reset() {
	*x = GetFundingRateRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundingRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRateRequest) ProtoMessage() {}

func (x *GetFundingRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRateRequest.ProtoReflect.Descriptor instead.
func (*GetFundingRateRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{30}
}

func (x *GetFundingRateRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetFundingRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundingRatesRequest) Reset() {
	*x = GetFundingRatesRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundingRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRatesRequest) ProtoMessage() {}

func (x *GetFundingRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRatesRequest.ProtoReflect.Descriptor instead.
func (*GetFundingRatesRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{31}
}

type GetFundingRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*FundingRate         `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundingRatesResponse) Reset() {
	*x = GetFundingRatesResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundingRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundingRatesResponse) ProtoMessage() {}

func (x *GetFundingRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundingRatesResponse.ProtoReflect.Descriptor instead.
func (*GetFundingRatesResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{32}
}

func (x *GetFundingRatesResponse) GetRates() []*FundingRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

type GetHistoricalFundingRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"` // e.g., 100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoricalFundingRatesRequest) Reset() {
	*x = GetHistoricalFundingRatesRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoricalFundingRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoricalFundingRatesRequest) ProtoMessage() {}

func (x *GetHistoricalFundingRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoricalFundingRatesRequest.ProtoReflect.Descriptor instead.
func (*GetHistoricalFundingRatesRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{33}
}

func (x *GetHistoricalFundingRatesRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetHistoricalFundingRatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetHistoricalFundingRatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rates         []*FundingRate         `protobuf:"bytes,1,rep,name=rates,proto3" json:"rates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHistoricalFundingRatesResponse) Reset() {
	*x = GetHistoricalFundingRatesResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHistoricalFundingRatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHistoricalFundingRatesResponse) ProtoMessage() {}

func (x *GetHistoricalFundingRatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHistoricalFundingRatesResponse.ProtoReflect.Descriptor instead.
func (*GetHistoricalFundingRatesResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{34}
}

func (x *GetHistoricalFundingRatesResponse) GetRates() []*FundingRate {
	if x != nil {
		return x.Rates
	}
	return nil
}

type GetTickersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickersRequest) Reset() {
	*x = GetTickersRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickersRequest) ProtoMessage() {}

func (x *GetTickersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickersRequest.ProtoReflect.Descriptor instead.
func (*GetTickersRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{35}
}

type GetTickersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tickers       []*Ticker              `protobuf:"bytes,1,rep,name=tickers,proto3" json:"tickers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTickersResponse) Reset() {
	*x = GetTickersResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTickersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTickersResponse) ProtoMessage() {}

func (x *GetTickersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTickersResponse.ProtoReflect.Descriptor instead.
func (*GetTickersResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{36}
}

func (x *GetTickersResponse) GetTickers() []*Ticker {
	if x != nil {
		return x.Tickers
	}
	return nil
}

type GetOpenInterestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenInterestRequest) Reset() {
	*x = GetOpenInterestRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenInterestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenInterestRequest) ProtoMessage() {}

func (x *GetOpenInterestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenInterestRequest.ProtoReflect.Descriptor instead.
func (*GetOpenInterestRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{37}
}

func (x *GetOpenInterestRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GetOpenInterestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OpenInterest  *decimal.Decimal       `protobuf:"bytes,1,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOpenInterestResponse) Reset() {
	*x = GetOpenInterestResponse{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOpenInterestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOpenInterestResponse) ProtoMessage() {}

func (x *GetOpenInterestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOpenInterestResponse.ProtoReflect.Descriptor instead.
func (*GetOpenInterestResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{38}
}

func (x *GetOpenInterestResponse) GetOpenInterest() *decimal.Decimal {
	if x != nil {
		return x.OpenInterest
	}
	return nil
}

type SubscribeFundingRateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeFundingRateRequest) Reset() {
	*x = SubscribeFundingRateRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeFundingRateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeFundingRateRequest) ProtoMessage() {}

func (x *SubscribeFundingRateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeFundingRateRequest.ProtoReflect.Descriptor instead.
func (*SubscribeFundingRateRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{39}
}

func (x *SubscribeFundingRateRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type SubscribePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribePriceRequest) Reset() {
	*x = SubscribePriceRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePriceRequest) ProtoMessage() {}

func (x *SubscribePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePriceRequest.ProtoReflect.Descriptor instead.
func (*SubscribePriceRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{40}
}

func (x *SubscribePriceRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type SubscribeOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeOrdersRequest) Reset() {
	*x = SubscribeOrdersRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeOrdersRequest) ProtoMessage() {}

func (x *SubscribeOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeOrdersRequest.ProtoReflect.Descriptor instead.
func (*SubscribeOrdersRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{41}
}

type SubscribeKlinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Interval      string                 `protobuf:"bytes,2,opt,name=interval,proto3" json:"interval,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeKlinesRequest) Reset() {
	*x = SubscribeKlinesRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeKlinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeKlinesRequest) ProtoMessage() {}

func (x *SubscribeKlinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeKlinesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeKlinesRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{42}
}

func (x *SubscribeKlinesRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *SubscribeKlinesRequest) GetInterval() string {
	if x != nil {
		return x.Interval
	}
	return ""
}

type SubscribeAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeAccountRequest) Reset() {
	*x = SubscribeAccountRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeAccountRequest) ProtoMessage() {}

func (x *SubscribeAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeAccountRequest.ProtoReflect.Descriptor instead.
func (*SubscribeAccountRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{43}
}

type SubscribePositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"` // Optional: filter by symbol
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribePositionsRequest) Reset() {
	*x = SubscribePositionsRequest{}
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribePositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribePositionsRequest) ProtoMessage() {}

func (x *SubscribePositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_exchange_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribePositionsRequest.ProtoReflect.Descriptor instead.
func (*SubscribePositionsRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP(), []int{44}
}

func (x *SubscribePositionsRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_opensqt_market_maker_v1_exchange_proto protoreflect.FileDescriptor

const file_opensqt_market_maker_v1_exchange_proto_rawDesc = "" +
	"\n" +
	"&opensqt/market_maker/v1/exchange.proto\x12\x17opensqt.market_maker.v1\x1a#opensqt/market_maker/v1/types.proto\x1a'opensqt/market_maker/v1/resources.proto\x1a$opensqt/market_maker/v1/events.proto\x1a\x19google/type/decimal.proto\"\x10\n" +
	"\x0eGetNameRequest\"%\n" +
	"\x0fGetNameResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x10\n" +
	"\x0eGetTypeRequest\"x\n" +
	"\x0fGetTypeResponse\x129\n" +
	"\x04type\x18\x01 \x01(\x0e2%.opensqt.market_maker.v1.ExchangeTypeR\x04type\x12*\n" +
	"\x11is_unified_margin\x18\x02 \x01(\bR\x0fisUnifiedMargin\"]\n" +
	"\x17BatchPlaceOrdersRequest\x12B\n" +
	"\x06orders\x18\x01 \x03(\v2*.opensqt.market_maker.v1.PlaceOrderRequestR\x06orders\"\xb5\x01\n" +
	"\x18BatchPlaceOrdersResponse\x126\n" +
	"\x06orders\x18\x01 \x03(\v2\x1e.opensqt.market_maker.v1.OrderR\x06orders\x12\x1f\n" +
	"\vall_success\x18\x02 \x01(\bR\n" +
	"allSuccess\x12@\n" +
	"\x06errors\x18\x03 \x03(\v2(.opensqt.market_maker.v1.BatchOrderErrorR\x06errors\"\x88\x01\n" +
	"\x0fBatchOrderError\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12&\n" +
	"\x0fclient_order_id\x18\x02 \x01(\tR\rclientOrderId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\"f\n" +
	"\x12CancelOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"use_margin\x18\x03 \x01(\bR\tuseMargin\"\x15\n" +
	"\x13CancelOrderResponse\"n\n" +
	"\x18BatchCancelOrdersRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1b\n" +
	"\torder_ids\x18\x02 \x03(\x03R\borderIds\x12\x1d\n" +
	"\n" +
	"use_margin\x18\x03 \x01(\bR\tuseMargin\"]\n" +
	"\x19BatchCancelOrdersResponse\x12@\n" +
	"\x06errors\x18\x01 \x03(\v2(.opensqt.market_maker.v1.BatchOrderErrorR\x06errors\"O\n" +
	"\x16CancelAllOrdersRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"use_margin\x18\x02 \x01(\bR\tuseMargin\"\x19\n" +
	"\x17CancelAllOrdersResponse\"\x8b\x01\n" +
	"\x0fGetOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x03 \x01(\tR\rclientOrderId\x12\x1d\n" +
	"\n" +
	"use_margin\x18\x04 \x01(\bR\tuseMargin\"M\n" +
	"\x14GetOpenOrdersRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"use_margin\x18\x02 \x01(\bR\tuseMargin\"O\n" +
	"\x15GetOpenOrdersResponse\x126\n" +
	"\x06orders\x18\x01 \x03(\v2\x1e.opensqt.market_maker.v1.OrderR\x06orders\"\x13\n" +
	"\x11GetAccountRequest\"-\n" +
	"\x13GetPositionsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"W\n" +
	"\x14GetPositionsResponse\x12?\n" +
	"\tpositions\x18\x01 \x03(\v2!.opensqt.market_maker.v1.PositionR\tpositions\")\n" +
	"\x11GetBalanceRequest\x12\x14\n" +
	"\x05asset\x18\x01 \x01(\tR\x05asset\"D\n" +
	"\x12GetBalanceResponse\x12.\n" +
	"\abalance\x18\x01 \x01(\v2\x14.google.type.DecimalR\abalance\"/\n" +
	"\x15GetLatestPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"D\n" +
	"\x16GetLatestPriceResponse\x12*\n" +
	"\x05price\x18\x01 \x01(\v2\x14.google.type.DecimalR\x05price\"f\n" +
	"\x1aGetHistoricalKlinesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"X\n" +
	"\x1bGetHistoricalKlinesResponse\x129\n" +
	"\acandles\x18\x01 \x03(\v2\x1f.opensqt.market_maker.v1.CandleR\acandles\"2\n" +
	"\x18FetchExchangeInfoRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\x1b\n" +
	"\x19FetchExchangeInfoResponse\".\n" +
	"\x14GetSymbolInfoRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\x13\n" +
	"\x11GetSymbolsRequest\".\n" +
	"\x12GetSymbolsResponse\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"/\n" +
	"\x15GetFundingRateRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\x18\n" +
	"\x16GetFundingRatesRequest\"U\n" +
	"\x17GetFundingRatesResponse\x12:\n" +
	"\x05rates\x18\x01 \x03(\v2$.opensqt.market_maker.v1.FundingRateR\x05rates\"P\n" +
	" GetHistoricalFundingRatesRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"_\n" +
	"!GetHistoricalFundingRatesResponse\x12:\n" +
	"\x05rates\x18\x01 \x03(\v2$.opensqt.market_maker.v1.FundingRateR\x05rates\"\x13\n" +
	"\x11GetTickersRequest\"O\n" +
	"\x12GetTickersResponse\x129\n" +
	"\atickers\x18\x01 \x03(\v2\x1f.opensqt.market_maker.v1.TickerR\atickers\"0\n" +
	"\x16GetOpenInterestRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"T\n" +
	"\x17GetOpenInterestResponse\x129\n" +
	"\ropen_interest\x18\x01 \x01(\v2\x14.google.type.DecimalR\fopenInterest\"5\n" +
	"\x1bSubscribeFundingRateRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"1\n" +
	"\x15SubscribePriceRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\x18\n" +
	"\x16SubscribeOrdersRequest\"N\n" +
	"\x16SubscribeKlinesRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\tR\binterval\"\x19\n" +
	"\x17SubscribeAccountRequest\"3\n" +
	"\x19SubscribePositionsRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol2\x8e\x18\n" +
	"\x0fExchangeService\x12\\\n" +
	"\aGetName\x12'.opensqt.market_maker.v1.GetNameRequest\x1a(.opensqt.market_maker.v1.GetNameResponse\x12\\\n" +
	"\aGetType\x12'.opensqt.market_maker.v1.GetTypeRequest\x1a(.opensqt.market_maker.v1.GetTypeResponse\x12X\n" +
	"\n" +
	"PlaceOrder\x12*.opensqt.market_maker.v1.PlaceOrderRequest\x1a\x1e.opensqt.market_maker.v1.Order\x12w\n" +
	"\x10BatchPlaceOrders\x120.opensqt.market_maker.v1.BatchPlaceOrdersRequest\x1a1.opensqt.market_maker.v1.BatchPlaceOrdersResponse\x12h\n" +
	"\vCancelOrder\x12+.opensqt.market_maker.v1.CancelOrderRequest\x1a,.opensqt.market_maker.v1.CancelOrderResponse\x12z\n" +
	"\x11BatchCancelOrders\x121.opensqt.market_maker.v1.BatchCancelOrdersRequest\x1a2.opensqt.market_maker.v1.BatchCancelOrdersResponse\x12t\n" +
	"\x0fCancelAllOrders\x12/.opensqt.market_maker.v1.CancelAllOrdersRequest\x1a0.opensqt.market_maker.v1.CancelAllOrdersResponse\x12T\n" +
	"\bGetOrder\x12(.opensqt.market_maker.v1.GetOrderRequest\x1a\x1e.opensqt.market_maker.v1.Order\x12n\n" +
	"\rGetOpenOrders\x12-.opensqt.market_maker.v1.GetOpenOrdersRequest\x1a..opensqt.market_maker.v1.GetOpenOrdersResponse\x12Z\n" +
	"\n" +
	"GetAccount\x12*.opensqt.market_maker.v1.GetAccountRequest\x1a .opensqt.market_maker.v1.Account\x12k\n" +
	"\fGetPositions\x12,.opensqt.market_maker.v1.GetPositionsRequest\x1a-.opensqt.market_maker.v1.GetPositionsResponse\x12e\n" +
	"\n" +
	"GetBalance\x12*.opensqt.market_maker.v1.GetBalanceRequest\x1a+.opensqt.market_maker.v1.GetBalanceResponse\x12q\n" +
	"\x0eGetLatestPrice\x12..opensqt.market_maker.v1.GetLatestPriceRequest\x1a/.opensqt.market_maker.v1.GetLatestPriceResponse\x12e\n" +
	"\n" +
	"GetTickers\x12*.opensqt.market_maker.v1.GetTickersRequest\x1a+.opensqt.market_maker.v1.GetTickersResponse\x12t\n" +
	"\x0fGetOpenInterest\x12/.opensqt.market_maker.v1.GetOpenInterestRequest\x1a0.opensqt.market_maker.v1.GetOpenInterestResponse\x12\x80\x01\n" +
	"\x13GetHistoricalKlines\x123.opensqt.market_maker.v1.GetHistoricalKlinesRequest\x1a4.opensqt.market_maker.v1.GetHistoricalKlinesResponse\x12z\n" +
	"\x11FetchExchangeInfo\x121.opensqt.market_maker.v1.FetchExchangeInfoRequest\x1a2.opensqt.market_maker.v1.FetchExchangeInfoResponse\x12c\n" +
	"\rGetSymbolInfo\x12-.opensqt.market_maker.v1.GetSymbolInfoRequest\x1a#.opensqt.market_maker.v1.SymbolInfo\x12e\n" +
	"\n" +
	"GetSymbols\x12*.opensqt.market_maker.v1.GetSymbolsRequest\x1a+.opensqt.market_maker.v1.GetSymbolsResponse\x12f\n" +
	"\x0eGetFundingRate\x12..opensqt.market_maker.v1.GetFundingRateRequest\x1a$.opensqt.market_maker.v1.FundingRate\x12t\n" +
	"\x0fGetFundingRates\x12/.opensqt.market_maker.v1.GetFundingRatesRequest\x1a0.opensqt.market_maker.v1.GetFundingRatesResponse\x12\x92\x01\n" +
	"\x19GetHistoricalFundingRates\x129.opensqt.market_maker.v1.GetHistoricalFundingRatesRequest\x1a:.opensqt.market_maker.v1.GetHistoricalFundingRatesResponse\x12v\n" +
	"\x14SubscribeFundingRate\x124.opensqt.market_maker.v1.SubscribeFundingRateRequest\x1a&.opensqt.market_maker.v1.FundingUpdate0\x01\x12h\n" +
	"\x0eSubscribePrice\x12..opensqt.market_maker.v1.SubscribePriceRequest\x1a$.opensqt.market_maker.v1.PriceChange0\x01\x12j\n" +
	"\x0fSubscribeOrders\x12/.opensqt.market_maker.v1.SubscribeOrdersRequest\x1a$.opensqt.market_maker.v1.OrderUpdate0\x01\x12e\n" +
	"\x0fSubscribeKlines\x12/.opensqt.market_maker.v1.SubscribeKlinesRequest\x1a\x1f.opensqt.market_maker.v1.Candle0\x01\x12h\n" +
	"\x10SubscribeAccount\x120.opensqt.market_maker.v1.SubscribeAccountRequest\x1a .opensqt.market_maker.v1.Account0\x01\x12m\n" +
	"\x12SubscribePositions\x122.opensqt.market_maker.v1.SubscribePositionsRequest\x1a!.opensqt.market_maker.v1.Position0\x01B\xc0\x01\n" +
	"\x1bcom.opensqt.market_maker.v1B\rExchangeProtoP\x01Z\x18market_maker/internal/pb\xa2\x02\x03OMX\xaa\x02\x16Opensqt.MarketMaker.V1\xca\x02\x16Opensqt\\MarketMaker\\V1\xe2\x02\"Opensqt\\MarketMaker\\V1\\GPBMetadata\xea\x02\x18Opensqt::MarketMaker::V1b\x06proto3"

var (
	file_opensqt_market_maker_v1_exchange_proto_rawDescOnce sync.Once
	file_opensqt_market_maker_v1_exchange_proto_rawDescData []byte
)

func file_opensqt_market_maker_v1_exchange_proto_rawDescGZIP() []byte {
	file_opensqt_market_maker_v1_exchange_proto_rawDescOnce.Do(func() {
		file_opensqt_market_maker_v1_exchange_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_exchange_proto_rawDesc), len(file_opensqt_market_maker_v1_exchange_proto_rawDesc)))
	})
	return file_opensqt_market_maker_v1_exchange_proto_rawDescData
}

var file_opensqt_market_maker_v1_exchange_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_opensqt_market_maker_v1_exchange_proto_goTypes = []any{
	(*GetNameRequest)(nil),                    // 0: opensqt.market_maker.v1.GetNameRequest
	(*GetNameResponse)(nil),                   // 1: opensqt.market_maker.v1.GetNameResponse
	(*GetTypeRequest)(nil),                    // 2: opensqt.market_maker.v1.GetTypeRequest
	(*GetTypeResponse)(nil),                   // 3: opensqt.market_maker.v1.GetTypeResponse
	(*BatchPlaceOrdersRequest)(nil),           // 4: opensqt.market_maker.v1.BatchPlaceOrdersRequest
	(*BatchPlaceOrdersResponse)(nil),          // 5: opensqt.market_maker.v1.BatchPlaceOrdersResponse
	(*BatchOrderError)(nil),                   // 6: opensqt.market_maker.v1.BatchOrderError
	(*CancelOrderRequest)(nil),                // 7: opensqt.market_maker.v1.CancelOrderRequest
	(*CancelOrderResponse)(nil),               // 8: opensqt.market_maker.v1.CancelOrderResponse
	(*BatchCancelOrdersRequest)(nil),          // 9: opensqt.market_maker.v1.BatchCancelOrdersRequest
	(*BatchCancelOrdersResponse)(nil),         // 10: opensqt.market_maker.v1.BatchCancelOrdersResponse
	(*CancelAllOrdersRequest)(nil),            // 11: opensqt.market_maker.v1.CancelAllOrdersRequest
	(*CancelAllOrdersResponse)(nil),           // 12: opensqt.market_maker.v1.CancelAllOrdersResponse
	(*GetOrderRequest)(nil),                   // 13: opensqt.market_maker.v1.GetOrderRequest
	(*GetOpenOrdersRequest)(nil),              // 14: opensqt.market_maker.v1.GetOpenOrdersRequest
	(*GetOpenOrdersResponse)(nil),             // 15: opensqt.market_maker.v1.GetOpenOrdersResponse
	(*GetAccountRequest)(nil),                 // 16: opensqt.market_maker.v1.GetAccountRequest
	(*GetPositionsRequest)(nil),               // 17: opensqt.market_maker.v1.GetPositionsRequest
	(*GetPositionsResponse)(nil),              // 18: opensqt.market_maker.v1.GetPositionsResponse
	(*GetBalanceRequest)(nil),                 // 19: opensqt.market_maker.v1.GetBalanceRequest
	(*GetBalanceResponse)(nil),                // 20: opensqt.market_maker.v1.GetBalanceResponse
	(*GetLatestPriceRequest)(nil),             // 21: opensqt.market_maker.v1.GetLatestPriceRequest
	(*GetLatestPriceResponse)(nil),            // 22: opensqt.market_maker.v1.GetLatestPriceResponse
	(*GetHistoricalKlinesRequest)(nil),        // 23: opensqt.market_maker.v1.GetHistoricalKlinesRequest
	(*GetHistoricalKlinesResponse)(nil),       // 24: opensqt.market_maker.v1.GetHistoricalKlinesResponse
	(*FetchExchangeInfoRequest)(nil),          // 25: opensqt.market_maker.v1.FetchExchangeInfoRequest
	(*FetchExchangeInfoResponse)(nil),         // 26: opensqt.market_maker.v1.FetchExchangeInfoResponse
	(*GetSymbolInfoRequest)(nil),              // 27: opensqt.market_maker.v1.GetSymbolInfoRequest
	(*GetSymbolsRequest)(nil),                 // 28: opensqt.market_maker.v1.GetSymbolsRequest
	(*GetSymbolsResponse)(nil),                // 29: opensqt.market_maker.v1.GetSymbolsResponse
	(*GetFundingRateRequest)(nil),             // 30: opensqt.market_maker.v1.GetFundingRateRequest
	(*GetFundingRatesRequest)(nil),            // 31: opensqt.market_maker.v1.GetFundingRatesRequest
	(*GetFundingRatesResponse)(nil),           // 32: opensqt.market_maker.v1.GetFundingRatesResponse
	(*GetHistoricalFundingRatesRequest)(nil),  // 33: opensqt.market_maker.v1.GetHistoricalFundingRatesRequest
	(*GetHistoricalFundingRatesResponse)(nil), // 34: opensqt.market_maker.v1.GetHistoricalFundingRatesResponse
	(*GetTickersRequest)(nil),                 // 35: opensqt.market_maker.v1.GetTickersRequest
	(*GetTickersResponse)(nil),                // 36: opensqt.market_maker.v1.GetTickersResponse
	(*GetOpenInterestRequest)(nil),            // 37: opensqt.market_maker.v1.GetOpenInterestRequest
	(*GetOpenInterestResponse)(nil),           // 38: opensqt.market_maker.v1.GetOpenInterestResponse
	(*SubscribeFundingRateRequest)(nil),       // 39: opensqt.market_maker.v1.SubscribeFundingRateRequest
	(*SubscribePriceRequest)(nil),             // 40: opensqt.market_maker.v1.SubscribePriceRequest
	(*SubscribeOrdersRequest)(nil),            // 41: opensqt.market_maker.v1.SubscribeOrdersRequest
	(*SubscribeKlinesRequest)(nil),            // 42: opensqt.market_maker.v1.SubscribeKlinesRequest
	(*SubscribeAccountRequest)(nil),           // 43: opensqt.market_maker.v1.SubscribeAccountRequest
	(*SubscribePositionsRequest)(nil),         // 44: opensqt.market_maker.v1.SubscribePositionsRequest
	(ExchangeType)(0),                         // 45: opensqt.market_maker.v1.ExchangeType
	(*PlaceOrderRequest)(nil),                 // 46: opensqt.market_maker.v1.PlaceOrderRequest
	(*Order)(nil),                             // 47: opensqt.market_maker.v1.Order
	(*Position)(nil),                          // 48: opensqt.market_maker.v1.Position
	(*decimal.Decimal)(nil),                   // 49: google.type.Decimal
	(*Candle)(nil),                            // 50: opensqt.market_maker.v1.Candle
	(*FundingRate)(nil),                       // 51: opensqt.market_maker.v1.FundingRate
	(*Ticker)(nil),                            // 52: opensqt.market_maker.v1.Ticker
	(*Account)(nil),                           // 53: opensqt.market_maker.v1.Account
	(*SymbolInfo)(nil),                        // 54: opensqt.market_maker.v1.SymbolInfo
	(*FundingUpdate)(nil),                     // 55: opensqt.market_maker.v1.FundingUpdate
	(*PriceChange)(nil),                       // 56: opensqt.market_maker.v1.PriceChange
	(*OrderUpdate)(nil),                       // 57: opensqt.market_maker.v1.OrderUpdate
}
var file_opensqt_market_maker_v1_exchange_proto_depIdxs = []int32{
	45, // 0: opensqt.market_maker.v1.GetTypeResponse.type:type_name -> opensqt.market_maker.v1.ExchangeType
	46, // 1: opensqt.market_maker.v1.BatchPlaceOrdersRequest.orders:type_name -> opensqt.market_maker.v1.PlaceOrderRequest
	47, // 2: opensqt.market_maker.v1.BatchPlaceOrdersResponse.orders:type_name -> opensqt.market_maker.v1.Order
	6,  // 3: opensqt.market_maker.v1.BatchPlaceOrdersResponse.errors:type_name -> opensqt.market_maker.v1.BatchOrderError
	6,  // 4: opensqt.market_maker.v1.BatchCancelOrdersResponse.errors:type_name -> opensqt.market_maker.v1.BatchOrderError
	47, // 5: opensqt.market_maker.v1.GetOpenOrdersResponse.orders:type_name -> opensqt.market_maker.v1.Order
	48, // 6: opensqt.market_maker.v1.GetPositionsResponse.positions:type_name -> opensqt.market_maker.v1.Position
	49, // 7: opensqt.market_maker.v1.GetBalanceResponse.balance:type_name -> google.type.Decimal
	49, // 8: opensqt.market_maker.v1.GetLatestPriceResponse.price:type_name -> google.type.Decimal
	50, // 9: opensqt.market_maker.v1.GetHistoricalKlinesResponse.candles:type_name -> opensqt.market_maker.v1.Candle
	51, // 10: opensqt.market_maker.v1.GetFundingRatesResponse.rates:type_name -> opensqt.market_maker.v1.FundingRate
	51, // 11: opensqt.market_maker.v1.GetHistoricalFundingRatesResponse.rates:type_name -> opensqt.market_maker.v1.FundingRate
	52, // 12: opensqt.market_maker.v1.GetTickersResponse.tickers:type_name -> opensqt.market_maker.v1.Ticker
	49, // 13: opensqt.market_maker.v1.GetOpenInterestResponse.open_interest:type_name -> google.type.Decimal
	0,  // 14: opensqt.market_maker.v1.ExchangeService.GetName:input_type -> opensqt.market_maker.v1.GetNameRequest
	2,  // 15: opensqt.market_maker.v1.ExchangeService.GetType:input_type -> opensqt.market_maker.v1.GetTypeRequest
	46, // 16: opensqt.market_maker.v1.ExchangeService.PlaceOrder:input_type -> opensqt.market_maker.v1.PlaceOrderRequest
	4,  // 17: opensqt.market_maker.v1.ExchangeService.BatchPlaceOrders:input_type -> opensqt.market_maker.v1.BatchPlaceOrdersRequest
	7,  // 18: opensqt.market_maker.v1.ExchangeService.CancelOrder:input_type -> opensqt.market_maker.v1.CancelOrderRequest
	9,  // 19: opensqt.market_maker.v1.ExchangeService.BatchCancelOrders:input_type -> opensqt.market_maker.v1.BatchCancelOrdersRequest
	11, // 20: opensqt.market_maker.v1.ExchangeService.CancelAllOrders:input_type -> opensqt.market_maker.v1.CancelAllOrdersRequest
	13, // 21: opensqt.market_maker.v1.ExchangeService.GetOrder:input_type -> opensqt.market_maker.v1.GetOrderRequest
	14, // 22: opensqt.market_maker.v1.ExchangeService.GetOpenOrders:input_type -> opensqt.market_maker.v1.GetOpenOrdersRequest
	16, // 23: opensqt.market_maker.v1.ExchangeService.GetAccount:input_type -> opensqt.market_maker.v1.GetAccountRequest
	17, // 24: opensqt.market_maker.v1.ExchangeService.GetPositions:input_type -> opensqt.market_maker.v1.GetPositionsRequest
	19, // 25: opensqt.market_maker.v1.ExchangeService.GetBalance:input_type -> opensqt.market_maker.v1.GetBalanceRequest
	21, // 26: opensqt.market_maker.v1.ExchangeService.GetLatestPrice:input_type -> opensqt.market_maker.v1.GetLatestPriceRequest
	35, // 27: opensqt.market_maker.v1.ExchangeService.GetTickers:input_type -> opensqt.market_maker.v1.GetTickersRequest
	37, // 28: opensqt.market_maker.v1.ExchangeService.GetOpenInterest:input_type -> opensqt.market_maker.v1.GetOpenInterestRequest
	23, // 29: opensqt.market_maker.v1.ExchangeService.GetHistoricalKlines:input_type -> opensqt.market_maker.v1.GetHistoricalKlinesRequest
	25, // 30: opensqt.market_maker.v1.ExchangeService.FetchExchangeInfo:input_type -> opensqt.market_maker.v1.FetchExchangeInfoRequest
	27, // 31: opensqt.market_maker.v1.ExchangeService.GetSymbolInfo:input_type -> opensqt.market_maker.v1.GetSymbolInfoRequest
	28, // 32: opensqt.market_maker.v1.ExchangeService.GetSymbols:input_type -> opensqt.market_maker.v1.GetSymbolsRequest
	30, // 33: opensqt.market_maker.v1.ExchangeService.GetFundingRate:input_type -> opensqt.market_maker.v1.GetFundingRateRequest
	31, // 34: opensqt.market_maker.v1.ExchangeService.GetFundingRates:input_type -> opensqt.market_maker.v1.GetFundingRatesRequest
	33, // 35: opensqt.market_maker.v1.ExchangeService.GetHistoricalFundingRates:input_type -> opensqt.market_maker.v1.GetHistoricalFundingRatesRequest
	39, // 36: opensqt.market_maker.v1.ExchangeService.SubscribeFundingRate:input_type -> opensqt.market_maker.v1.SubscribeFundingRateRequest
	40, // 37: opensqt.market_maker.v1.ExchangeService.SubscribePrice:input_type -> opensqt.market_maker.v1.SubscribePriceRequest
	41, // 38: opensqt.market_maker.v1.ExchangeService.SubscribeOrders:input_type -> opensqt.market_maker.v1.SubscribeOrdersRequest
	42, // 39: opensqt.market_maker.v1.ExchangeService.SubscribeKlines:input_type -> opensqt.market_maker.v1.SubscribeKlinesRequest
	43, // 40: opensqt.market_maker.v1.ExchangeService.SubscribeAccount:input_type -> opensqt.market_maker.v1.SubscribeAccountRequest
	44, // 41: opensqt.market_maker.v1.ExchangeService.SubscribePositions:input_type -> opensqt.market_maker.v1.SubscribePositionsRequest
	1,  // 42: opensqt.market_maker.v1.ExchangeService.GetName:output_type -> opensqt.market_maker.v1.GetNameResponse
	3,  // 43: opensqt.market_maker.v1.ExchangeService.GetType:output_type -> opensqt.market_maker.v1.GetTypeResponse
	47, // 44: opensqt.market_maker.v1.ExchangeService.PlaceOrder:output_type -> opensqt.market_maker.v1.Order
	5,  // 45: opensqt.market_maker.v1.ExchangeService.BatchPlaceOrders:output_type -> opensqt.market_maker.v1.BatchPlaceOrdersResponse
	8,  // 46: opensqt.market_maker.v1.ExchangeService.CancelOrder:output_type -> opensqt.market_maker.v1.CancelOrderResponse
	10, // 47: opensqt.market_maker.v1.ExchangeService.BatchCancelOrders:output_type -> opensqt.market_maker.v1.BatchCancelOrdersResponse
	12, // 48: opensqt.market_maker.v1.ExchangeService.CancelAllOrders:output_type -> opensqt.market_maker.v1.CancelAllOrdersResponse
	47, // 49: opensqt.market_maker.v1.ExchangeService.GetOrder:output_type -> opensqt.market_maker.v1.Order
	15, // 50: opensqt.market_maker.v1.ExchangeService.GetOpenOrders:output_type -> opensqt.market_maker.v1.GetOpenOrdersResponse
	53, // 51: opensqt.market_maker.v1.ExchangeService.GetAccount:output_type -> opensqt.market_maker.v1.Account
	18, // 52: opensqt.market_maker.v1.ExchangeService.GetPositions:output_type -> opensqt.market_maker.v1.GetPositionsResponse
	20, // 53: opensqt.market_maker.v1.ExchangeService.GetBalance:output_type -> opensqt.market_maker.v1.GetBalanceResponse
	22, // 54: opensqt.market_maker.v1.ExchangeService.GetLatestPrice:output_type -> opensqt.market_maker.v1.GetLatestPriceResponse
	36, // 55: opensqt.market_maker.v1.ExchangeService.GetTickers:output_type -> opensqt.market_maker.v1.GetTickersResponse
	38, // 56: opensqt.market_maker.v1.ExchangeService.GetOpenInterest:output_type -> opensqt.market_maker.v1.GetOpenInterestResponse
	24, // 57: opensqt.market_maker.v1.ExchangeService.GetHistoricalKlines:output_type -> opensqt.market_maker.v1.GetHistoricalKlinesResponse
	26, // 58: opensqt.market_maker.v1.ExchangeService.FetchExchangeInfo:output_type -> opensqt.market_maker.v1.FetchExchangeInfoResponse
	54, // 59: opensqt.market_maker.v1.ExchangeService.GetSymbolInfo:output_type -> opensqt.market_maker.v1.SymbolInfo
	29, // 60: opensqt.market_maker.v1.ExchangeService.GetSymbols:output_type -> opensqt.market_maker.v1.GetSymbolsResponse
	51, // 61: opensqt.market_maker.v1.ExchangeService.GetFundingRate:output_type -> opensqt.market_maker.v1.FundingRate
	32, // 62: opensqt.market_maker.v1.ExchangeService.GetFundingRates:output_type -> opensqt.market_maker.v1.GetFundingRatesResponse
	34, // 63: opensqt.market_maker.v1.ExchangeService.GetHistoricalFundingRates:output_type -> opensqt.market_maker.v1.GetHistoricalFundingRatesResponse
	55, // 64: opensqt.market_maker.v1.ExchangeService.SubscribeFundingRate:output_type -> opensqt.market_maker.v1.FundingUpdate
	56, // 65: opensqt.market_maker.v1.ExchangeService.SubscribePrice:output_type -> opensqt.market_maker.v1.PriceChange
	57, // 66: opensqt.market_maker.v1.ExchangeService.SubscribeOrders:output_type -> opensqt.market_maker.v1.OrderUpdate
	50, // 67: opensqt.market_maker.v1.ExchangeService.SubscribeKlines:output_type -> opensqt.market_maker.v1.Candle
	53, // 68: opensqt.market_maker.v1.ExchangeService.SubscribeAccount:output_type -> opensqt.market_maker.v1.Account
	48, // 69: opensqt.market_maker.v1.ExchangeService.SubscribePositions:output_type -> opensqt.market_maker.v1.Position
	42, // [42:70] is the sub-list for method output_type
	14, // [14:42] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_opensqt_market_maker_v1_exchange_proto_init() }
func file_opensqt_market_maker_v1_exchange_proto_init() {
	if File_opensqt_market_maker_v1_exchange_proto != nil {
		return
	}
	file_opensqt_market_maker_v1_types_proto_init()
	file_opensqt_market_maker_v1_resources_proto_init()
	file_opensqt_market_maker_v1_events_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_exchange_proto_rawDesc), len(file_opensqt_market_maker_v1_exchange_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_opensqt_market_maker_v1_exchange_proto_goTypes,
		DependencyIndexes: file_opensqt_market_maker_v1_exchange_proto_depIdxs,
		MessageInfos:      file_opensqt_market_maker_v1_exchange_proto_msgTypes,
	}.Build()
	File_opensqt_market_maker_v1_exchange_proto = out.File
	file_opensqt_market_maker_v1_exchange_proto_goTypes = nil
	file_opensqt_market_maker_v1_exchange_proto_depIdxs = nil
}
