// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: opensqt/market_maker/v1/portfolio.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortfolioService_GetRiskProfile_FullMethodName     = "/opensqt.market_maker.v1.PortfolioService/GetRiskProfile"
	PortfolioService_SimulateMargin_FullMethodName     = "/opensqt.market_maker.v1.PortfolioService/SimulateMargin"
	PortfolioService_GetTargetPositions_FullMethodName = "/opensqt.market_maker.v1.PortfolioService/GetTargetPositions"
	PortfolioService_GetMarketScores_FullMethodName    = "/opensqt.market_maker.v1.PortfolioService/GetMarketScores"
)

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	// Risk and Margin
	GetRiskProfile(ctx context.Context, in *GetRiskProfileRequest, opts ...grpc.CallOption) (*RiskProfile, error)
	SimulateMargin(ctx context.Context, in *SimulateMarginRequest, opts ...grpc.CallOption) (*SimulateMarginResponse, error)
	// Targets and Allocations
	GetTargetPositions(ctx context.Context, in *GetTargetPositionsRequest, opts ...grpc.CallOption) (*GetTargetPositionsResponse, error)
	GetMarketScores(ctx context.Context, in *GetMarketScoresRequest, opts ...grpc.CallOption) (*GetMarketScoresResponse, error)
}

type portfolioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioServiceClient(cc grpc.ClientConnInterface) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) GetRiskProfile(ctx context.Context, in *GetRiskProfileRequest, opts ...grpc.CallOption) (*RiskProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskProfile)
	err := c.cc.Invoke(ctx, PortfolioService_GetRiskProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) SimulateMargin(ctx context.Context, in *SimulateMarginRequest, opts ...grpc.CallOption) (*SimulateMarginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimulateMarginResponse)
	err := c.cc.Invoke(ctx, PortfolioService_SimulateMargin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetTargetPositions(ctx context.Context, in *GetTargetPositionsRequest, opts ...grpc.CallOption) (*GetTargetPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTargetPositionsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetTargetPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetMarketScores(ctx context.Context, in *GetMarketScoresRequest, opts ...grpc.CallOption) (*GetMarketScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMarketScoresResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetMarketScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
// All implementations must embed UnimplementedPortfolioServiceServer
// for forward compatibility.
type PortfolioServiceServer interface {
	// Risk and Margin
	GetRiskProfile(context.Context, *GetRiskProfileRequest) (*RiskProfile, error)
	SimulateMargin(context.Context, *SimulateMarginRequest) (*SimulateMarginResponse, error)
	// Targets and Allocations
	GetTargetPositions(context.Context, *GetTargetPositionsRequest) (*GetTargetPositionsResponse, error)
	GetMarketScores(context.Context, *GetMarketScoresRequest) (*GetMarketScoresResponse, error)
	mustEmbedUnimplementedPortfolioServiceServer()
}

// UnimplementedPortfolioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortfolioServiceServer struct{}

func (UnimplementedPortfolioServiceServer) GetRiskProfile(context.Context, *GetRiskProfileRequest) (*RiskProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRiskProfile not implemented")
}
func (UnimplementedPortfolioServiceServer) SimulateMargin(context.Context, *SimulateMarginRequest) (*SimulateMarginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SimulateMargin not implemented")
}
func (UnimplementedPortfolioServiceServer) GetTargetPositions(context.Context, *GetTargetPositionsRequest) (*GetTargetPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTargetPositions not implemented")
}
func (UnimplementedPortfolioServiceServer) GetMarketScores(context.Context, *GetMarketScoresRequest) (*GetMarketScoresResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMarketScores not implemented")
}
func (UnimplementedPortfolioServiceServer) mustEmbedUnimplementedPortfolioServiceServer() {}
func (UnimplementedPortfolioServiceServer) testEmbeddedByValue()                          {}

// UnsafePortfolioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServiceServer will
// result in compilation errors.
type UnsafePortfolioServiceServer interface {
	mustEmbedUnimplementedPortfolioServiceServer()
}

func RegisterPortfolioServiceServer(s grpc.ServiceRegistrar, srv PortfolioServiceServer) {
	// If the following call panics, it indicates UnimplementedPortfolioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortfolioService_ServiceDesc, srv)
}

func _PortfolioService_GetRiskProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRiskProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetRiskProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetRiskProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetRiskProfile(ctx, req.(*GetRiskProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_SimulateMargin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateMarginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).SimulateMargin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_SimulateMargin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).SimulateMargin(ctx, req.(*SimulateMarginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetTargetPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTargetPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetTargetPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetTargetPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetTargetPositions(ctx, req.(*GetTargetPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetMarketScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMarketScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetMarketScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetMarketScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetMarketScores(ctx, req.(*GetMarketScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortfolioService_ServiceDesc is the grpc.ServiceDesc for PortfolioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortfolioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opensqt.market_maker.v1.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRiskProfile",
			Handler:    _PortfolioService_GetRiskProfile_Handler,
		},
		{
			MethodName: "SimulateMargin",
			Handler:    _PortfolioService_SimulateMargin_Handler,
		},
		{
			MethodName: "GetTargetPositions",
			Handler:    _PortfolioService_GetTargetPositions_Handler,
		},
		{
			MethodName: "GetMarketScores",
			Handler:    _PortfolioService_GetMarketScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "opensqt/market_maker/v1/portfolio.proto",
}
