// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: opensqt/market_maker/v1/portfolio.proto

package pb

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRiskProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRiskProfileRequest) Reset() {
	*x = GetRiskProfileRequest{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRiskProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRiskProfileRequest) ProtoMessage() {}

func (x *GetRiskProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRiskProfileRequest.ProtoReflect.Descriptor instead.
func (*GetRiskProfileRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{0}
}

type RiskProfile struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	AdjustedEquity         *decimal.Decimal       `protobuf:"bytes,1,opt,name=adjusted_equity,json=adjustedEquity,proto3" json:"adjusted_equity,omitempty"`
	TotalMaintenanceMargin *decimal.Decimal       `protobuf:"bytes,2,opt,name=total_maintenance_margin,json=totalMaintenanceMargin,proto3" json:"total_maintenance_margin,omitempty"`
	AvailableHeadroom      *decimal.Decimal       `protobuf:"bytes,3,opt,name=available_headroom,json=availableHeadroom,proto3" json:"available_headroom,omitempty"`
	HealthScore            *decimal.Decimal       `protobuf:"bytes,4,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"`
	IsUnified              bool                   `protobuf:"varint,5,opt,name=is_unified,json=isUnified,proto3" json:"is_unified,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RiskProfile) Reset() {
	*x = RiskProfile{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskProfile) ProtoMessage() {}

func (x *RiskProfile) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskProfile.ProtoReflect.Descriptor instead.
func (*RiskProfile) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{1}
}

func (x *RiskProfile) GetAdjustedEquity() *decimal.Decimal {
	if x != nil {
		return x.AdjustedEquity
	}
	return nil
}

func (x *RiskProfile) GetTotalMaintenanceMargin() *decimal.Decimal {
	if x != nil {
		return x.TotalMaintenanceMargin
	}
	return nil
}

func (x *RiskProfile) GetAvailableHeadroom() *decimal.Decimal {
	if x != nil {
		return x.AvailableHeadroom
	}
	return nil
}

func (x *RiskProfile) GetHealthScore() *decimal.Decimal {
	if x != nil {
		return x.HealthScore
	}
	return nil
}

func (x *RiskProfile) GetIsUnified() bool {
	if x != nil {
		return x.IsUnified
	}
	return false
}

type SimulateMarginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of symbol to proposed size change (notional)
	Proposals     map[string]*decimal.Decimal `protobuf:"bytes,1,rep,name=proposals,proto3" json:"proposals,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateMarginRequest) Reset() {
	*x = SimulateMarginRequest{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateMarginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateMarginRequest) ProtoMessage() {}

func (x *SimulateMarginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateMarginRequest.ProtoReflect.Descriptor instead.
func (*SimulateMarginRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{2}
}

func (x *SimulateMarginRequest) GetProposals() map[string]*decimal.Decimal {
	if x != nil {
		return x.Proposals
	}
	return nil
}

type SimulateMarginResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProjectedHealthScore *decimal.Decimal       `protobuf:"bytes,1,opt,name=projected_health_score,json=projectedHealthScore,proto3" json:"projected_health_score,omitempty"`
	WouldLiquidate       bool                   `protobuf:"varint,2,opt,name=would_liquidate,json=wouldLiquidate,proto3" json:"would_liquidate,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SimulateMarginResponse) Reset() {
	*x = SimulateMarginResponse{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateMarginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateMarginResponse) ProtoMessage() {}

func (x *SimulateMarginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateMarginResponse.ProtoReflect.Descriptor instead.
func (*SimulateMarginResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{3}
}

func (x *SimulateMarginResponse) GetProjectedHealthScore() *decimal.Decimal {
	if x != nil {
		return x.ProjectedHealthScore
	}
	return nil
}

func (x *SimulateMarginResponse) GetWouldLiquidate() bool {
	if x != nil {
		return x.WouldLiquidate
	}
	return false
}

type GetTargetPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetPositionsRequest) Reset() {
	*x = GetTargetPositionsRequest{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetPositionsRequest) ProtoMessage() {}

func (x *GetTargetPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetTargetPositionsRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{4}
}

type GetTargetPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Targets       []*TargetPosition      `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetPositionsResponse) Reset() {
	*x = GetTargetPositionsResponse{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetPositionsResponse) ProtoMessage() {}

func (x *GetTargetPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetTargetPositionsResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{5}
}

func (x *GetTargetPositionsResponse) GetTargets() []*TargetPosition {
	if x != nil {
		return x.Targets
	}
	return nil
}

type TargetPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Weight        *decimal.Decimal       `protobuf:"bytes,2,opt,name=weight,proto3" json:"weight,omitempty"`
	Notional      *decimal.Decimal       `protobuf:"bytes,3,opt,name=notional,proto3" json:"notional,omitempty"`
	Exchange      string                 `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	QualityScore  *decimal.Decimal       `protobuf:"bytes,5,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetPosition) Reset() {
	*x = TargetPosition{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetPosition) ProtoMessage() {}

func (x *TargetPosition) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetPosition.ProtoReflect.Descriptor instead.
func (*TargetPosition) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{6}
}

func (x *TargetPosition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TargetPosition) GetWeight() *decimal.Decimal {
	if x != nil {
		return x.Weight
	}
	return nil
}

func (x *TargetPosition) GetNotional() *decimal.Decimal {
	if x != nil {
		return x.Notional
	}
	return nil
}

func (x *TargetPosition) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *TargetPosition) GetQualityScore() *decimal.Decimal {
	if x != nil {
		return x.QualityScore
	}
	return nil
}

type GetMarketScoresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketScoresRequest) Reset() {
	*x = GetMarketScoresRequest{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketScoresRequest) ProtoMessage() {}

func (x *GetMarketScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketScoresRequest.ProtoReflect.Descriptor instead.
func (*GetMarketScoresRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{7}
}

type GetMarketScoresResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Opportunities []*PortfolioOpportunity `protobuf:"bytes,1,rep,name=opportunities,proto3" json:"opportunities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketScoresResponse) Reset() {
	*x = GetMarketScoresResponse{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketScoresResponse) ProtoMessage() {}

func (x *GetMarketScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketScoresResponse.ProtoReflect.Descriptor instead.
func (*GetMarketScoresResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{8}
}

func (x *GetMarketScoresResponse) GetOpportunities() []*PortfolioOpportunity {
	if x != nil {
		return x.Opportunities
	}
	return nil
}

type PortfolioOpportunity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Strategy      string                 `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	LongExchange  string                 `protobuf:"bytes,3,opt,name=long_exchange,json=longExchange,proto3" json:"long_exchange,omitempty"`
	ShortExchange string                 `protobuf:"bytes,4,opt,name=short_exchange,json=shortExchange,proto3" json:"short_exchange,omitempty"`
	Spread        *decimal.Decimal       `protobuf:"bytes,5,opt,name=spread,proto3" json:"spread,omitempty"`
	SpreadApr     *decimal.Decimal       `protobuf:"bytes,6,opt,name=spread_apr,json=spreadApr,proto3" json:"spread_apr,omitempty"`
	Basis         *decimal.Decimal       `protobuf:"bytes,7,opt,name=basis,proto3" json:"basis,omitempty"`
	QualityScore  *decimal.Decimal       `protobuf:"bytes,8,opt,name=quality_score,json=qualityScore,proto3" json:"quality_score,omitempty"`
	Metrics       *FundingMetrics        `protobuf:"bytes,9,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Timestamp     int64                  `protobuf:"varint,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix epoch milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortfolioOpportunity) Reset() {
	*x = PortfolioOpportunity{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortfolioOpportunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortfolioOpportunity) ProtoMessage() {}

func (x *PortfolioOpportunity) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortfolioOpportunity.ProtoReflect.Descriptor instead.
func (*PortfolioOpportunity) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{9}
}

func (x *PortfolioOpportunity) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PortfolioOpportunity) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *PortfolioOpportunity) GetLongExchange() string {
	if x != nil {
		return x.LongExchange
	}
	return ""
}

func (x *PortfolioOpportunity) GetShortExchange() string {
	if x != nil {
		return x.ShortExchange
	}
	return ""
}

func (x *PortfolioOpportunity) GetSpread() *decimal.Decimal {
	if x != nil {
		return x.Spread
	}
	return nil
}

func (x *PortfolioOpportunity) GetSpreadApr() *decimal.Decimal {
	if x != nil {
		return x.SpreadApr
	}
	return nil
}

func (x *PortfolioOpportunity) GetBasis() *decimal.Decimal {
	if x != nil {
		return x.Basis
	}
	return nil
}

func (x *PortfolioOpportunity) GetQualityScore() *decimal.Decimal {
	if x != nil {
		return x.QualityScore
	}
	return nil
}

func (x *PortfolioOpportunity) GetMetrics() *FundingMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *PortfolioOpportunity) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FundingMetrics struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Sma_1D           *decimal.Decimal       `protobuf:"bytes,1,opt,name=sma_1d,json=sma1d,proto3" json:"sma_1d,omitempty"`
	Sma_7D           *decimal.Decimal       `protobuf:"bytes,2,opt,name=sma_7d,json=sma7d,proto3" json:"sma_7d,omitempty"`
	Sma_30D          *decimal.Decimal       `protobuf:"bytes,3,opt,name=sma_30d,json=sma30d,proto3" json:"sma_30d,omitempty"`
	StabilityScore   *decimal.Decimal       `protobuf:"bytes,4,opt,name=stability_score,json=stabilityScore,proto3" json:"stability_score,omitempty"`
	VolatilityScore  *decimal.Decimal       `protobuf:"bytes,5,opt,name=volatility_score,json=volatilityScore,proto3" json:"volatility_score,omitempty"`
	Momentum         *decimal.Decimal       `protobuf:"bytes,6,opt,name=momentum,proto3" json:"momentum,omitempty"`
	OiFactor         *decimal.Decimal       `protobuf:"bytes,7,opt,name=oi_factor,json=oiFactor,proto3" json:"oi_factor,omitempty"`
	PositiveRatio    *decimal.Decimal       `protobuf:"bytes,8,opt,name=positive_ratio,json=positiveRatio,proto3" json:"positive_ratio,omitempty"`
	NumSignFlips     int32                  `protobuf:"varint,9,opt,name=num_sign_flips,json=numSignFlips,proto3" json:"num_sign_flips,omitempty"`
	CurrentDuration  int32                  `protobuf:"varint,10,opt,name=current_duration,json=currentDuration,proto3" json:"current_duration,omitempty"`
	AverageAnnualApr *decimal.Decimal       `protobuf:"bytes,11,opt,name=average_annual_apr,json=averageAnnualApr,proto3" json:"average_annual_apr,omitempty"`
	NarrativeSector  string                 `protobuf:"bytes,12,opt,name=narrative_sector,json=narrativeSector,proto3" json:"narrative_sector,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FundingMetrics) Reset() {
	*x = FundingMetrics{}
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingMetrics) ProtoMessage() {}

func (x *FundingMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_portfolio_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingMetrics.ProtoReflect.Descriptor instead.
func (*FundingMetrics) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP(), []int{10}
}

func (x *FundingMetrics) GetSma_1D() *decimal.Decimal {
	if x != nil {
		return x.Sma_1D
	}
	return nil
}

func (x *FundingMetrics) GetSma_7D() *decimal.Decimal {
	if x != nil {
		return x.Sma_7D
	}
	return nil
}

func (x *FundingMetrics) GetSma_30D() *decimal.Decimal {
	if x != nil {
		return x.Sma_30D
	}
	return nil
}

func (x *FundingMetrics) GetStabilityScore() *decimal.Decimal {
	if x != nil {
		return x.StabilityScore
	}
	return nil
}

func (x *FundingMetrics) GetVolatilityScore() *decimal.Decimal {
	if x != nil {
		return x.VolatilityScore
	}
	return nil
}

func (x *FundingMetrics) GetMomentum() *decimal.Decimal {
	if x != nil {
		return x.Momentum
	}
	return nil
}

func (x *FundingMetrics) GetOiFactor() *decimal.Decimal {
	if x != nil {
		return x.OiFactor
	}
	return nil
}

func (x *FundingMetrics) GetPositiveRatio() *decimal.Decimal {
	if x != nil {
		return x.PositiveRatio
	}
	return nil
}

func (x *FundingMetrics) GetNumSignFlips() int32 {
	if x != nil {
		return x.NumSignFlips
	}
	return 0
}

func (x *FundingMetrics) GetCurrentDuration() int32 {
	if x != nil {
		return x.CurrentDuration
	}
	return 0
}

func (x *FundingMetrics) GetAverageAnnualApr() *decimal.Decimal {
	if x != nil {
		return x.AverageAnnualApr
	}
	return nil
}

func (x *FundingMetrics) GetNarrativeSector() string {
	if x != nil {
		return x.NarrativeSector
	}
	return ""
}

var File_opensqt_market_maker_v1_portfolio_proto protoreflect.FileDescriptor

const file_opensqt_market_maker_v1_portfolio_proto_rawDesc = "" +
	"\n" +
	"'opensqt/market_maker/v1/portfolio.proto\x12\x17opensqt.market_maker.v1\x1a\x19google/type/decimal.proto\x1a'opensqt/market_maker/v1/resources.proto\"\x17\n" +
	"\x15GetRiskProfileRequest\"\xb9\x02\n" +
	"\vRiskProfile\x12=\n" +
	"\x0fadjusted_equity\x18\x01 \x01(\v2\x14.google.type.DecimalR\x0eadjustedEquity\x12N\n" +
	"\x18total_maintenance_margin\x18\x02 \x01(\v2\x14.google.type.DecimalR\x16totalMaintenanceMargin\x12C\n" +
	"\x12available_headroom\x18\x03 \x01(\v2\x14.google.type.DecimalR\x11availableHeadroom\x127\n" +
	"\fhealth_score\x18\x04 \x01(\v2\x14.google.type.DecimalR\vhealthScore\x12\x1d\n" +
	"\n" +
	"is_unified\x18\x05 \x01(\bR\tisUnified\"\xc8\x01\n" +
	"\x15SimulateMarginRequest\x12[\n" +
	"\tproposals\x18\x01 \x03(\v2=.opensqt.market_maker.v1.SimulateMarginRequest.ProposalsEntryR\tproposals\x1aR\n" +
	"\x0eProposalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.google.type.DecimalR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x16SimulateMarginResponse\x12J\n" +
	"\x16projected_health_score\x18\x01 \x01(\v2\x14.google.type.DecimalR\x14projectedHealthScore\x12'\n" +
	"\x0fwould_liquidate\x18\x02 \x01(\bR\x0ewouldLiquidate\"\x1b\n" +
	"\x19GetTargetPositionsRequest\"_\n" +
	"\x1aGetTargetPositionsResponse\x12A\n" +
	"\atargets\x18\x01 \x03(\v2'.opensqt.market_maker.v1.TargetPositionR\atargets\"\xdf\x01\n" +
	"\x0eTargetPosition\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12,\n" +
	"\x06weight\x18\x02 \x01(\v2\x14.google.type.DecimalR\x06weight\x120\n" +
	"\bnotional\x18\x03 \x01(\v2\x14.google.type.DecimalR\bnotional\x12\x1a\n" +
	"\bexchange\x18\x04 \x01(\tR\bexchange\x129\n" +
	"\rquality_score\x18\x05 \x01(\v2\x14.google.type.DecimalR\fqualityScore\"\x18\n" +
	"\x16GetMarketScoresRequest\"n\n" +
	"\x17GetMarketScoresResponse\x12S\n" +
	"\ropportunities\x18\x01 \x03(\v2-.opensqt.market_maker.v1.PortfolioOpportunityR\ropportunities\"\xc1\x03\n" +
	"\x14PortfolioOpportunity\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bstrategy\x18\x02 \x01(\tR\bstrategy\x12#\n" +
	"\rlong_exchange\x18\x03 \x01(\tR\flongExchange\x12%\n" +
	"\x0eshort_exchange\x18\x04 \x01(\tR\rshortExchange\x12,\n" +
	"\x06spread\x18\x05 \x01(\v2\x14.google.type.DecimalR\x06spread\x123\n" +
	"\n" +
	"spread_apr\x18\x06 \x01(\v2\x14.google.type.DecimalR\tspreadApr\x12*\n" +
	"\x05basis\x18\a \x01(\v2\x14.google.type.DecimalR\x05basis\x129\n" +
	"\rquality_score\x18\b \x01(\v2\x14.google.type.DecimalR\fqualityScore\x12A\n" +
	"\ametrics\x18\t \x01(\v2'.opensqt.market_maker.v1.FundingMetricsR\ametrics\x12\x1c\n" +
	"\ttimestamp\x18\n" +
	" \x01(\x03R\ttimestamp\"\xfb\x04\n" +
	"\x0eFundingMetrics\x12+\n" +
	"\x06sma_1d\x18\x01 \x01(\v2\x14.google.type.DecimalR\x05sma1d\x12+\n" +
	"\x06sma_7d\x18\x02 \x01(\v2\x14.google.type.DecimalR\x05sma7d\x12-\n" +
	"\asma_30d\x18\x03 \x01(\v2\x14.google.type.DecimalR\x06sma30d\x12=\n" +
	"\x0fstability_score\x18\x04 \x01(\v2\x14.google.type.DecimalR\x0estabilityScore\x12?\n" +
	"\x10volatility_score\x18\x05 \x01(\v2\x14.google.type.DecimalR\x0fvolatilityScore\x120\n" +
	"\bmomentum\x18\x06 \x01(\v2\x14.google.type.DecimalR\bmomentum\x121\n" +
	"\toi_factor\x18\a \x01(\v2\x14.google.type.DecimalR\boiFactor\x12;\n" +
	"\x0epositive_ratio\x18\b \x01(\v2\x14.google.type.DecimalR\rpositiveRatio\x12$\n" +
	"\x0enum_sign_flips\x18\t \x01(\x05R\fnumSignFlips\x12)\n" +
	"\x10current_duration\x18\n" +
	" \x01(\x05R\x0fcurrentDuration\x12B\n" +
	"\x12average_annual_apr\x18\v \x01(\v2\x14.google.type.DecimalR\x10averageAnnualApr\x12)\n" +
	"\x10narrative_sector\x18\f \x01(\tR\x0fnarrativeSector2\xe2\x03\n" +
	"\x10PortfolioService\x12f\n" +
	"\x0eGetRiskProfile\x12..opensqt.market_maker.v1.GetRiskProfileRequest\x1a$.opensqt.market_maker.v1.RiskProfile\x12q\n" +
	"\x0eSimulateMargin\x12..opensqt.market_maker.v1.SimulateMarginRequest\x1a/.opensqt.market_maker.v1.SimulateMarginResponse\x12}\n" +
	"\x12GetTargetPositions\x122.opensqt.market_maker.v1.GetTargetPositionsRequest\x1a3.opensqt.market_maker.v1.GetTargetPositionsResponse\x12t\n" +
	"\x0fGetMarketScores\x12/.opensqt.market_maker.v1.GetMarketScoresRequest\x1a0.opensqt.market_maker.v1.GetMarketScoresResponseB\xc1\x01\n" +
	"\x1bcom.opensqt.market_maker.v1B\x0ePortfolioProtoP\x01Z\x18market_maker/internal/pb\xa2\x02\x03OMX\xaa\x02\x16Opensqt.MarketMaker.V1\xca\x02\x16Opensqt\\MarketMaker\\V1\xe2\x02\"Opensqt\\MarketMaker\\V1\\GPBMetadata\xea\x02\x18Opensqt::MarketMaker::V1b\x06proto3"

var (
	file_opensqt_market_maker_v1_portfolio_proto_rawDescOnce sync.Once
	file_opensqt_market_maker_v1_portfolio_proto_rawDescData []byte
)

func file_opensqt_market_maker_v1_portfolio_proto_rawDescGZIP() []byte {
	file_opensqt_market_maker_v1_portfolio_proto_rawDescOnce.Do(func() {
		file_opensqt_market_maker_v1_portfolio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_portfolio_proto_rawDesc), len(file_opensqt_market_maker_v1_portfolio_proto_rawDesc)))
	})
	return file_opensqt_market_maker_v1_portfolio_proto_rawDescData
}

var file_opensqt_market_maker_v1_portfolio_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_opensqt_market_maker_v1_portfolio_proto_goTypes = []any{
	(*GetRiskProfileRequest)(nil),      // 0: opensqt.market_maker.v1.GetRiskProfileRequest
	(*RiskProfile)(nil),                // 1: opensqt.market_maker.v1.RiskProfile
	(*SimulateMarginRequest)(nil),      // 2: opensqt.market_maker.v1.SimulateMarginRequest
	(*SimulateMarginResponse)(nil),     // 3: opensqt.market_maker.v1.SimulateMarginResponse
	(*GetTargetPositionsRequest)(nil),  // 4: opensqt.market_maker.v1.GetTargetPositionsRequest
	(*GetTargetPositionsResponse)(nil), // 5: opensqt.market_maker.v1.GetTargetPositionsResponse
	(*TargetPosition)(nil),             // 6: opensqt.market_maker.v1.TargetPosition
	(*GetMarketScoresRequest)(nil),     // 7: opensqt.market_maker.v1.GetMarketScoresRequest
	(*GetMarketScoresResponse)(nil),    // 8: opensqt.market_maker.v1.GetMarketScoresResponse
	(*PortfolioOpportunity)(nil),       // 9: opensqt.market_maker.v1.PortfolioOpportunity
	(*FundingMetrics)(nil),             // 10: opensqt.market_maker.v1.FundingMetrics
	nil,                                // 11: opensqt.market_maker.v1.SimulateMarginRequest.ProposalsEntry
	(*decimal.Decimal)(nil),            // 12: google.type.Decimal
}
var file_opensqt_market_maker_v1_portfolio_proto_depIdxs = []int32{
	12, // 0: opensqt.market_maker.v1.RiskProfile.adjusted_equity:type_name -> google.type.Decimal
	12, // 1: opensqt.market_maker.v1.RiskProfile.total_maintenance_margin:type_name -> google.type.Decimal
	12, // 2: opensqt.market_maker.v1.RiskProfile.available_headroom:type_name -> google.type.Decimal
	12, // 3: opensqt.market_maker.v1.RiskProfile.health_score:type_name -> google.type.Decimal
	11, // 4: opensqt.market_maker.v1.SimulateMarginRequest.proposals:type_name -> opensqt.market_maker.v1.SimulateMarginRequest.ProposalsEntry
	12, // 5: opensqt.market_maker.v1.SimulateMarginResponse.projected_health_score:type_name -> google.type.Decimal
	6,  // 6: opensqt.market_maker.v1.GetTargetPositionsResponse.targets:type_name -> opensqt.market_maker.v1.TargetPosition
	12, // 7: opensqt.market_maker.v1.TargetPosition.weight:type_name -> google.type.Decimal
	12, // 8: opensqt.market_maker.v1.TargetPosition.notional:type_name -> google.type.Decimal
	12, // 9: opensqt.market_maker.v1.TargetPosition.quality_score:type_name -> google.type.Decimal
	9,  // 10: opensqt.market_maker.v1.GetMarketScoresResponse.opportunities:type_name -> opensqt.market_maker.v1.PortfolioOpportunity
	12, // 11: opensqt.market_maker.v1.PortfolioOpportunity.spread:type_name -> google.type.Decimal
	12, // 12: opensqt.market_maker.v1.PortfolioOpportunity.spread_apr:type_name -> google.type.Decimal
	12, // 13: opensqt.market_maker.v1.PortfolioOpportunity.basis:type_name -> google.type.Decimal
	12, // 14: opensqt.market_maker.v1.PortfolioOpportunity.quality_score:type_name -> google.type.Decimal
	10, // 15: opensqt.market_maker.v1.PortfolioOpportunity.metrics:type_name -> opensqt.market_maker.v1.FundingMetrics
	12, // 16: opensqt.market_maker.v1.FundingMetrics.sma_1d:type_name -> google.type.Decimal
	12, // 17: opensqt.market_maker.v1.FundingMetrics.sma_7d:type_name -> google.type.Decimal
	12, // 18: opensqt.market_maker.v1.FundingMetrics.sma_30d:type_name -> google.type.Decimal
	12, // 19: opensqt.market_maker.v1.FundingMetrics.stability_score:type_name -> google.type.Decimal
	12, // 20: opensqt.market_maker.v1.FundingMetrics.volatility_score:type_name -> google.type.Decimal
	12, // 21: opensqt.market_maker.v1.FundingMetrics.momentum:type_name -> google.type.Decimal
	12, // 22: opensqt.market_maker.v1.FundingMetrics.oi_factor:type_name -> google.type.Decimal
	12, // 23: opensqt.market_maker.v1.FundingMetrics.positive_ratio:type_name -> google.type.Decimal
	12, // 24: opensqt.market_maker.v1.FundingMetrics.average_annual_apr:type_name -> google.type.Decimal
	12, // 25: opensqt.market_maker.v1.SimulateMarginRequest.ProposalsEntry.value:type_name -> google.type.Decimal
	0,  // 26: opensqt.market_maker.v1.PortfolioService.GetRiskProfile:input_type -> opensqt.market_maker.v1.GetRiskProfileRequest
	2,  // 27: opensqt.market_maker.v1.PortfolioService.SimulateMargin:input_type -> opensqt.market_maker.v1.SimulateMarginRequest
	4,  // 28: opensqt.market_maker.v1.PortfolioService.GetTargetPositions:input_type -> opensqt.market_maker.v1.GetTargetPositionsRequest
	7,  // 29: opensqt.market_maker.v1.PortfolioService.GetMarketScores:input_type -> opensqt.market_maker.v1.GetMarketScoresRequest
	1,  // 30: opensqt.market_maker.v1.PortfolioService.GetRiskProfile:output_type -> opensqt.market_maker.v1.RiskProfile
	3,  // 31: opensqt.market_maker.v1.PortfolioService.SimulateMargin:output_type -> opensqt.market_maker.v1.SimulateMarginResponse
	5,  // 32: opensqt.market_maker.v1.PortfolioService.GetTargetPositions:output_type -> opensqt.market_maker.v1.GetTargetPositionsResponse
	8,  // 33: opensqt.market_maker.v1.PortfolioService.GetMarketScores:output_type -> opensqt.market_maker.v1.GetMarketScoresResponse
	30, // [30:34] is the sub-list for method output_type
	26, // [26:30] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_opensqt_market_maker_v1_portfolio_proto_init() }
func file_opensqt_market_maker_v1_portfolio_proto_init() {
	if File_opensqt_market_maker_v1_portfolio_proto != nil {
		return
	}
	file_opensqt_market_maker_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_portfolio_proto_rawDesc), len(file_opensqt_market_maker_v1_portfolio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_opensqt_market_maker_v1_portfolio_proto_goTypes,
		DependencyIndexes: file_opensqt_market_maker_v1_portfolio_proto_depIdxs,
		MessageInfos:      file_opensqt_market_maker_v1_portfolio_proto_msgTypes,
	}.Build()
	File_opensqt_market_maker_v1_portfolio_proto = out.File
	file_opensqt_market_maker_v1_portfolio_proto_goTypes = nil
	file_opensqt_market_maker_v1_portfolio_proto_depIdxs = nil
}
