// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: opensqt/market_maker/v1/position.proto

package pb

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PositionServiceGetPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`     // Empty = all symbols
	Exchanges     []string               `protobuf:"bytes,2,rep,name=exchanges,proto3" json:"exchanges,omitempty"` // Empty = all exchanges
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetPositionsRequest) Reset() {
	*x = PositionServiceGetPositionsRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetPositionsRequest) ProtoMessage() {}

func (x *PositionServiceGetPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetPositionsRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceGetPositionsRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{0}
}

func (x *PositionServiceGetPositionsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *PositionServiceGetPositionsRequest) GetExchanges() []string {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

type PositionServiceGetPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*PositionData        `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetPositionsResponse) Reset() {
	*x = PositionServiceGetPositionsResponse{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetPositionsResponse) ProtoMessage() {}

func (x *PositionServiceGetPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetPositionsResponse.ProtoReflect.Descriptor instead.
func (*PositionServiceGetPositionsResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{1}
}

func (x *PositionServiceGetPositionsResponse) GetPositions() []*PositionData {
	if x != nil {
		return x.Positions
	}
	return nil
}

// Renamed from Position to PositionData to avoid conflict with resources.proto Position
type PositionData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Quantity      *decimal.Decimal       `protobuf:"bytes,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EntryPrice    *decimal.Decimal       `protobuf:"bytes,4,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	CurrentPrice  *decimal.Decimal       `protobuf:"bytes,5,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	UnrealizedPnl *decimal.Decimal       `protobuf:"bytes,6,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	RealizedPnl   *decimal.Decimal       `protobuf:"bytes,7,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	OpenedAt      int64                  `protobuf:"varint,8,opt,name=opened_at,json=openedAt,proto3" json:"opened_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionData) Reset() {
	*x = PositionData{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionData) ProtoMessage() {}

func (x *PositionData) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionData.ProtoReflect.Descriptor instead.
func (*PositionData) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{2}
}

func (x *PositionData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionData) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PositionData) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *PositionData) GetEntryPrice() *decimal.Decimal {
	if x != nil {
		return x.EntryPrice
	}
	return nil
}

func (x *PositionData) GetCurrentPrice() *decimal.Decimal {
	if x != nil {
		return x.CurrentPrice
	}
	return nil
}

func (x *PositionData) GetUnrealizedPnl() *decimal.Decimal {
	if x != nil {
		return x.UnrealizedPnl
	}
	return nil
}

func (x *PositionData) GetRealizedPnl() *decimal.Decimal {
	if x != nil {
		return x.RealizedPnl
	}
	return nil
}

func (x *PositionData) GetOpenedAt() int64 {
	if x != nil {
		return x.OpenedAt
	}
	return 0
}

func (x *PositionData) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type PositionServiceGetPositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Exchange      string                 `protobuf:"bytes,2,opt,name=exchange,proto3" json:"exchange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetPositionRequest) Reset() {
	*x = PositionServiceGetPositionRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetPositionRequest) ProtoMessage() {}

func (x *PositionServiceGetPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetPositionRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceGetPositionRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{3}
}

func (x *PositionServiceGetPositionRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionServiceGetPositionRequest) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

type PositionServiceGetPositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *PositionData          `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	OpenOrders    []*Order               `protobuf:"bytes,2,rep,name=open_orders,json=openOrders,proto3" json:"open_orders,omitempty"` // Orders for this position
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetPositionResponse) Reset() {
	*x = PositionServiceGetPositionResponse{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetPositionResponse) ProtoMessage() {}

func (x *PositionServiceGetPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetPositionResponse.ProtoReflect.Descriptor instead.
func (*PositionServiceGetPositionResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{4}
}

func (x *PositionServiceGetPositionResponse) GetPosition() *PositionData {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PositionServiceGetPositionResponse) GetOpenOrders() []*Order {
	if x != nil {
		return x.OpenOrders
	}
	return nil
}

type PositionServiceSubscribePositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceSubscribePositionsRequest) Reset() {
	*x = PositionServiceSubscribePositionsRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceSubscribePositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceSubscribePositionsRequest) ProtoMessage() {}

func (x *PositionServiceSubscribePositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceSubscribePositionsRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceSubscribePositionsRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{5}
}

func (x *PositionServiceSubscribePositionsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type PositionUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *PositionData          `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	UpdateType    string                 `protobuf:"bytes,2,opt,name=update_type,json=updateType,proto3" json:"update_type,omitempty"`       // "opened", "increased", "reduced", "closed", "snapshot"
	TriggerOrder  *Order                 `protobuf:"bytes,3,opt,name=trigger_order,json=triggerOrder,proto3" json:"trigger_order,omitempty"` // Order that caused update
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionUpdate) Reset() {
	*x = PositionUpdate{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionUpdate) ProtoMessage() {}

func (x *PositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionUpdate.ProtoReflect.Descriptor instead.
func (*PositionUpdate) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{6}
}

func (x *PositionUpdate) GetPosition() *PositionData {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *PositionUpdate) GetUpdateType() string {
	if x != nil {
		return x.UpdateType
	}
	return ""
}

func (x *PositionUpdate) GetTriggerOrder() *Order {
	if x != nil {
		return x.TriggerOrder
	}
	return nil
}

type PositionServiceGetOpenOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Exchanges     []string               `protobuf:"bytes,2,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetOpenOrdersRequest) Reset() {
	*x = PositionServiceGetOpenOrdersRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetOpenOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetOpenOrdersRequest) ProtoMessage() {}

func (x *PositionServiceGetOpenOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetOpenOrdersRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceGetOpenOrdersRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{7}
}

func (x *PositionServiceGetOpenOrdersRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *PositionServiceGetOpenOrdersRequest) GetExchanges() []string {
	if x != nil {
		return x.Exchanges
	}
	return nil
}

type PositionServiceGetOpenOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetOpenOrdersResponse) Reset() {
	*x = PositionServiceGetOpenOrdersResponse{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetOpenOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetOpenOrdersResponse) ProtoMessage() {}

func (x *PositionServiceGetOpenOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetOpenOrdersResponse.ProtoReflect.Descriptor instead.
func (*PositionServiceGetOpenOrdersResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{8}
}

func (x *PositionServiceGetOpenOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type PositionServiceGetOrderHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // Unix timestamp
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"` // Max results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetOrderHistoryRequest) Reset() {
	*x = PositionServiceGetOrderHistoryRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetOrderHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetOrderHistoryRequest) ProtoMessage() {}

func (x *PositionServiceGetOrderHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetOrderHistoryRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceGetOrderHistoryRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{9}
}

func (x *PositionServiceGetOrderHistoryRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *PositionServiceGetOrderHistoryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PositionServiceGetOrderHistoryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *PositionServiceGetOrderHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PositionServiceGetOrderHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // Pagination
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetOrderHistoryResponse) Reset() {
	*x = PositionServiceGetOrderHistoryResponse{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetOrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetOrderHistoryResponse) ProtoMessage() {}

func (x *PositionServiceGetOrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetOrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*PositionServiceGetOrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{10}
}

func (x *PositionServiceGetOrderHistoryResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *PositionServiceGetOrderHistoryResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type PositionServiceGetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetOrderRequest) Reset() {
	*x = PositionServiceGetOrderRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetOrderRequest) ProtoMessage() {}

func (x *PositionServiceGetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetOrderRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceGetOrderRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{11}
}

func (x *PositionServiceGetOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type PositionServiceGetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Fills         []*Fill                `protobuf:"bytes,2,rep,name=fills,proto3" json:"fills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetOrderResponse) Reset() {
	*x = PositionServiceGetOrderResponse{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetOrderResponse) ProtoMessage() {}

func (x *PositionServiceGetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetOrderResponse.ProtoReflect.Descriptor instead.
func (*PositionServiceGetOrderResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{12}
}

func (x *PositionServiceGetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *PositionServiceGetOrderResponse) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

type Fill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FillId        string                 `protobuf:"bytes,1,opt,name=fill_id,json=fillId,proto3" json:"fill_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=side,proto3" json:"side,omitempty"` // "buy", "sell"
	Quantity      *decimal.Decimal       `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         *decimal.Decimal       `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Fee           *decimal.Decimal       `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	FeeCurrency   string                 `protobuf:"bytes,8,opt,name=fee_currency,json=feeCurrency,proto3" json:"fee_currency,omitempty"`
	FilledAt      int64                  `protobuf:"varint,9,opt,name=filled_at,json=filledAt,proto3" json:"filled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fill) Reset() {
	*x = Fill{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fill) ProtoMessage() {}

func (x *Fill) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fill.ProtoReflect.Descriptor instead.
func (*Fill) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{13}
}

func (x *Fill) GetFillId() string {
	if x != nil {
		return x.FillId
	}
	return ""
}

func (x *Fill) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Fill) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Fill) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Fill) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *Fill) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Fill) GetFee() *decimal.Decimal {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *Fill) GetFeeCurrency() string {
	if x != nil {
		return x.FeeCurrency
	}
	return ""
}

func (x *Fill) GetFilledAt() int64 {
	if x != nil {
		return x.FilledAt
	}
	return 0
}

type PositionServiceGetFillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetFillsRequest) Reset() {
	*x = PositionServiceGetFillsRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetFillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetFillsRequest) ProtoMessage() {}

func (x *PositionServiceGetFillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetFillsRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceGetFillsRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{14}
}

func (x *PositionServiceGetFillsRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *PositionServiceGetFillsRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PositionServiceGetFillsRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *PositionServiceGetFillsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PositionServiceGetFillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fills         []*Fill                `protobuf:"bytes,1,rep,name=fills,proto3" json:"fills,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetFillsResponse) Reset() {
	*x = PositionServiceGetFillsResponse{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetFillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetFillsResponse) ProtoMessage() {}

func (x *PositionServiceGetFillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetFillsResponse.ProtoReflect.Descriptor instead.
func (*PositionServiceGetFillsResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{15}
}

func (x *PositionServiceGetFillsResponse) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

func (x *PositionServiceGetFillsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type PositionServiceGetPositionHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetPositionHistoryRequest) Reset() {
	*x = PositionServiceGetPositionHistoryRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetPositionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetPositionHistoryRequest) ProtoMessage() {}

func (x *PositionServiceGetPositionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetPositionHistoryRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceGetPositionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{16}
}

func (x *PositionServiceGetPositionHistoryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionServiceGetPositionHistoryRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PositionServiceGetPositionHistoryRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type PositionServiceGetPositionHistoryResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Snapshots     []*PositionSnapshotData `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetPositionHistoryResponse) Reset() {
	*x = PositionServiceGetPositionHistoryResponse{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetPositionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetPositionHistoryResponse) ProtoMessage() {}

func (x *PositionServiceGetPositionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetPositionHistoryResponse.ProtoReflect.Descriptor instead.
func (*PositionServiceGetPositionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{17}
}

func (x *PositionServiceGetPositionHistoryResponse) GetSnapshots() []*PositionSnapshotData {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

// Renamed to avoid conflict with models.proto if exists, or use directly
// models.proto has PositionManagerSnapshot which is different
type PositionSnapshotData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      *decimal.Decimal       `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EntryPrice    *decimal.Decimal       `protobuf:"bytes,3,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	MarketPrice   *decimal.Decimal       `protobuf:"bytes,4,opt,name=market_price,json=marketPrice,proto3" json:"market_price,omitempty"`
	UnrealizedPnl *decimal.Decimal       `protobuf:"bytes,5,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionSnapshotData) Reset() {
	*x = PositionSnapshotData{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionSnapshotData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionSnapshotData) ProtoMessage() {}

func (x *PositionSnapshotData) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionSnapshotData.ProtoReflect.Descriptor instead.
func (*PositionSnapshotData) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{18}
}

func (x *PositionSnapshotData) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionSnapshotData) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *PositionSnapshotData) GetEntryPrice() *decimal.Decimal {
	if x != nil {
		return x.EntryPrice
	}
	return nil
}

func (x *PositionSnapshotData) GetMarketPrice() *decimal.Decimal {
	if x != nil {
		return x.MarketPrice
	}
	return nil
}

func (x *PositionSnapshotData) GetUnrealizedPnl() *decimal.Decimal {
	if x != nil {
		return x.UnrealizedPnl
	}
	return nil
}

func (x *PositionSnapshotData) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PositionServiceGetRealizedPnLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	StartTime     int64                  `protobuf:"varint,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       int64                  `protobuf:"varint,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetRealizedPnLRequest) Reset() {
	*x = PositionServiceGetRealizedPnLRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetRealizedPnLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetRealizedPnLRequest) ProtoMessage() {}

func (x *PositionServiceGetRealizedPnLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetRealizedPnLRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceGetRealizedPnLRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{19}
}

func (x *PositionServiceGetRealizedPnLRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *PositionServiceGetRealizedPnLRequest) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PositionServiceGetRealizedPnLRequest) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type PositionServiceGetRealizedPnLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPnl      *decimal.Decimal       `protobuf:"bytes,1,opt,name=total_pnl,json=totalPnl,proto3" json:"total_pnl,omitempty"`
	BySymbol      []*SymbolPnL           `protobuf:"bytes,2,rep,name=by_symbol,json=bySymbol,proto3" json:"by_symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetRealizedPnLResponse) Reset() {
	*x = PositionServiceGetRealizedPnLResponse{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetRealizedPnLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetRealizedPnLResponse) ProtoMessage() {}

func (x *PositionServiceGetRealizedPnLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetRealizedPnLResponse.ProtoReflect.Descriptor instead.
func (*PositionServiceGetRealizedPnLResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{20}
}

func (x *PositionServiceGetRealizedPnLResponse) GetTotalPnl() *decimal.Decimal {
	if x != nil {
		return x.TotalPnl
	}
	return nil
}

func (x *PositionServiceGetRealizedPnLResponse) GetBySymbol() []*SymbolPnL {
	if x != nil {
		return x.BySymbol
	}
	return nil
}

type SymbolPnL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	RealizedPnl   *decimal.Decimal       `protobuf:"bytes,2,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	NumTrades     int32                  `protobuf:"varint,3,opt,name=num_trades,json=numTrades,proto3" json:"num_trades,omitempty"`
	WinningTrades int32                  `protobuf:"varint,4,opt,name=winning_trades,json=winningTrades,proto3" json:"winning_trades,omitempty"`
	LosingTrades  int32                  `protobuf:"varint,5,opt,name=losing_trades,json=losingTrades,proto3" json:"losing_trades,omitempty"`
	WinRate       string                 `protobuf:"bytes,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolPnL) Reset() {
	*x = SymbolPnL{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolPnL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolPnL) ProtoMessage() {}

func (x *SymbolPnL) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolPnL.ProtoReflect.Descriptor instead.
func (*SymbolPnL) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{21}
}

func (x *SymbolPnL) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SymbolPnL) GetRealizedPnl() *decimal.Decimal {
	if x != nil {
		return x.RealizedPnl
	}
	return nil
}

func (x *SymbolPnL) GetNumTrades() int32 {
	if x != nil {
		return x.NumTrades
	}
	return 0
}

func (x *SymbolPnL) GetWinningTrades() int32 {
	if x != nil {
		return x.WinningTrades
	}
	return 0
}

func (x *SymbolPnL) GetLosingTrades() int32 {
	if x != nil {
		return x.LosingTrades
	}
	return 0
}

func (x *SymbolPnL) GetWinRate() string {
	if x != nil {
		return x.WinRate
	}
	return ""
}

type PositionServiceGetUnrealizedPnLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetUnrealizedPnLRequest) Reset() {
	*x = PositionServiceGetUnrealizedPnLRequest{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetUnrealizedPnLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetUnrealizedPnLRequest) ProtoMessage() {}

func (x *PositionServiceGetUnrealizedPnLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetUnrealizedPnLRequest.ProtoReflect.Descriptor instead.
func (*PositionServiceGetUnrealizedPnLRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{22}
}

func (x *PositionServiceGetUnrealizedPnLRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

type PositionServiceGetUnrealizedPnLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPnl      *decimal.Decimal       `protobuf:"bytes,1,opt,name=total_pnl,json=totalPnl,proto3" json:"total_pnl,omitempty"`
	Positions     []*PositionPnL         `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionServiceGetUnrealizedPnLResponse) Reset() {
	*x = PositionServiceGetUnrealizedPnLResponse{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionServiceGetUnrealizedPnLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionServiceGetUnrealizedPnLResponse) ProtoMessage() {}

func (x *PositionServiceGetUnrealizedPnLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionServiceGetUnrealizedPnLResponse.ProtoReflect.Descriptor instead.
func (*PositionServiceGetUnrealizedPnLResponse) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{23}
}

func (x *PositionServiceGetUnrealizedPnLResponse) GetTotalPnl() *decimal.Decimal {
	if x != nil {
		return x.TotalPnl
	}
	return nil
}

func (x *PositionServiceGetUnrealizedPnLResponse) GetPositions() []*PositionPnL {
	if x != nil {
		return x.Positions
	}
	return nil
}

type PositionPnL struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      *decimal.Decimal       `protobuf:"bytes,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	EntryPrice    *decimal.Decimal       `protobuf:"bytes,3,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	CurrentPrice  *decimal.Decimal       `protobuf:"bytes,4,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"`
	UnrealizedPnl *decimal.Decimal       `protobuf:"bytes,5,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	PnlPercentage string                 `protobuf:"bytes,6,opt,name=pnl_percentage,json=pnlPercentage,proto3" json:"pnl_percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PositionPnL) Reset() {
	*x = PositionPnL{}
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionPnL) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionPnL) ProtoMessage() {}

func (x *PositionPnL) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_position_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionPnL.ProtoReflect.Descriptor instead.
func (*PositionPnL) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_position_proto_rawDescGZIP(), []int{24}
}

func (x *PositionPnL) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionPnL) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *PositionPnL) GetEntryPrice() *decimal.Decimal {
	if x != nil {
		return x.EntryPrice
	}
	return nil
}

func (x *PositionPnL) GetCurrentPrice() *decimal.Decimal {
	if x != nil {
		return x.CurrentPrice
	}
	return nil
}

func (x *PositionPnL) GetUnrealizedPnl() *decimal.Decimal {
	if x != nil {
		return x.UnrealizedPnl
	}
	return nil
}

func (x *PositionPnL) GetPnlPercentage() string {
	if x != nil {
		return x.PnlPercentage
	}
	return ""
}

var File_opensqt_market_maker_v1_position_proto protoreflect.FileDescriptor

const file_opensqt_market_maker_v1_position_proto_rawDesc = "" +
	"\n" +
	"&opensqt/market_maker/v1/position.proto\x12\x17opensqt.market_maker.v1\x1a'opensqt/market_maker/v1/resources.proto\x1a\x19google/type/decimal.proto\"\\\n" +
	"\"PositionServiceGetPositionsRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1c\n" +
	"\texchanges\x18\x02 \x03(\tR\texchanges\"j\n" +
	"#PositionServiceGetPositionsResponse\x12C\n" +
	"\tpositions\x18\x01 \x03(\v2%.opensqt.market_maker.v1.PositionDataR\tpositions\"\x98\x03\n" +
	"\fPositionData\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\x120\n" +
	"\bquantity\x18\x03 \x01(\v2\x14.google.type.DecimalR\bquantity\x125\n" +
	"\ventry_price\x18\x04 \x01(\v2\x14.google.type.DecimalR\n" +
	"entryPrice\x129\n" +
	"\rcurrent_price\x18\x05 \x01(\v2\x14.google.type.DecimalR\fcurrentPrice\x12;\n" +
	"\x0eunrealized_pnl\x18\x06 \x01(\v2\x14.google.type.DecimalR\runrealizedPnl\x127\n" +
	"\frealized_pnl\x18\a \x01(\v2\x14.google.type.DecimalR\vrealizedPnl\x12\x1b\n" +
	"\topened_at\x18\b \x01(\x03R\bopenedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\x03R\tupdatedAt\"W\n" +
	"!PositionServiceGetPositionRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bexchange\x18\x02 \x01(\tR\bexchange\"\xa8\x01\n" +
	"\"PositionServiceGetPositionResponse\x12A\n" +
	"\bposition\x18\x01 \x01(\v2%.opensqt.market_maker.v1.PositionDataR\bposition\x12?\n" +
	"\vopen_orders\x18\x02 \x03(\v2\x1e.opensqt.market_maker.v1.OrderR\n" +
	"openOrders\"D\n" +
	"(PositionServiceSubscribePositionsRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\xb9\x01\n" +
	"\x0ePositionUpdate\x12A\n" +
	"\bposition\x18\x01 \x01(\v2%.opensqt.market_maker.v1.PositionDataR\bposition\x12\x1f\n" +
	"\vupdate_type\x18\x02 \x01(\tR\n" +
	"updateType\x12C\n" +
	"\rtrigger_order\x18\x03 \x01(\v2\x1e.opensqt.market_maker.v1.OrderR\ftriggerOrder\"]\n" +
	"#PositionServiceGetOpenOrdersRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1c\n" +
	"\texchanges\x18\x02 \x03(\tR\texchanges\"^\n" +
	"$PositionServiceGetOpenOrdersResponse\x126\n" +
	"\x06orders\x18\x01 \x03(\v2\x1e.opensqt.market_maker.v1.OrderR\x06orders\"\x91\x01\n" +
	"%PositionServiceGetOrderHistoryRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"\x81\x01\n" +
	"&PositionServiceGetOrderHistoryResponse\x126\n" +
	"\x06orders\x18\x01 \x03(\v2\x1e.opensqt.market_maker.v1.OrderR\x06orders\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\";\n" +
	"\x1ePositionServiceGetOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"\x8c\x01\n" +
	"\x1fPositionServiceGetOrderResponse\x124\n" +
	"\x05order\x18\x01 \x01(\v2\x1e.opensqt.market_maker.v1.OrderR\x05order\x123\n" +
	"\x05fills\x18\x02 \x03(\v2\x1d.opensqt.market_maker.v1.FillR\x05fills\"\xac\x02\n" +
	"\x04Fill\x12\x17\n" +
	"\afill_id\x18\x01 \x01(\tR\x06fillId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x04 \x01(\tR\x04side\x120\n" +
	"\bquantity\x18\x05 \x01(\v2\x14.google.type.DecimalR\bquantity\x12*\n" +
	"\x05price\x18\x06 \x01(\v2\x14.google.type.DecimalR\x05price\x12&\n" +
	"\x03fee\x18\a \x01(\v2\x14.google.type.DecimalR\x03fee\x12!\n" +
	"\ffee_currency\x18\b \x01(\tR\vfeeCurrency\x12\x1b\n" +
	"\tfilled_at\x18\t \x01(\x03R\bfilledAt\"\x8a\x01\n" +
	"\x1ePositionServiceGetFillsRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"w\n" +
	"\x1fPositionServiceGetFillsResponse\x123\n" +
	"\x05fills\x18\x01 \x03(\v2\x1d.opensqt.market_maker.v1.FillR\x05fills\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"|\n" +
	"(PositionServiceGetPositionHistoryRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\"x\n" +
	")PositionServiceGetPositionHistoryResponse\x12K\n" +
	"\tsnapshots\x18\x01 \x03(\v2-.opensqt.market_maker.v1.PositionSnapshotDataR\tsnapshots\"\xab\x02\n" +
	"\x14PositionSnapshotData\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x120\n" +
	"\bquantity\x18\x02 \x01(\v2\x14.google.type.DecimalR\bquantity\x125\n" +
	"\ventry_price\x18\x03 \x01(\v2\x14.google.type.DecimalR\n" +
	"entryPrice\x127\n" +
	"\fmarket_price\x18\x04 \x01(\v2\x14.google.type.DecimalR\vmarketPrice\x12;\n" +
	"\x0eunrealized_pnl\x18\x05 \x01(\v2\x14.google.type.DecimalR\runrealizedPnl\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"z\n" +
	"$PositionServiceGetRealizedPnLRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x03R\aendTime\"\x9b\x01\n" +
	"%PositionServiceGetRealizedPnLResponse\x121\n" +
	"\ttotal_pnl\x18\x01 \x01(\v2\x14.google.type.DecimalR\btotalPnl\x12?\n" +
	"\tby_symbol\x18\x02 \x03(\v2\".opensqt.market_maker.v1.SymbolPnLR\bbySymbol\"\xe2\x01\n" +
	"\tSymbolPnL\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x127\n" +
	"\frealized_pnl\x18\x02 \x01(\v2\x14.google.type.DecimalR\vrealizedPnl\x12\x1d\n" +
	"\n" +
	"num_trades\x18\x03 \x01(\x05R\tnumTrades\x12%\n" +
	"\x0ewinning_trades\x18\x04 \x01(\x05R\rwinningTrades\x12#\n" +
	"\rlosing_trades\x18\x05 \x01(\x05R\flosingTrades\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\tR\awinRate\"B\n" +
	"&PositionServiceGetUnrealizedPnLRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\"\xa0\x01\n" +
	"'PositionServiceGetUnrealizedPnLResponse\x121\n" +
	"\ttotal_pnl\x18\x01 \x01(\v2\x14.google.type.DecimalR\btotalPnl\x12B\n" +
	"\tpositions\x18\x02 \x03(\v2$.opensqt.market_maker.v1.PositionPnLR\tpositions\"\xad\x02\n" +
	"\vPositionPnL\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x120\n" +
	"\bquantity\x18\x02 \x01(\v2\x14.google.type.DecimalR\bquantity\x125\n" +
	"\ventry_price\x18\x03 \x01(\v2\x14.google.type.DecimalR\n" +
	"entryPrice\x129\n" +
	"\rcurrent_price\x18\x04 \x01(\v2\x14.google.type.DecimalR\fcurrentPrice\x12;\n" +
	"\x0eunrealized_pnl\x18\x05 \x01(\v2\x14.google.type.DecimalR\runrealizedPnl\x12%\n" +
	"\x0epnl_percentage\x18\x06 \x01(\tR\rpnlPercentage2\x95\v\n" +
	"\x0fPositionService\x12\x89\x01\n" +
	"\fGetPositions\x12;.opensqt.market_maker.v1.PositionServiceGetPositionsRequest\x1a<.opensqt.market_maker.v1.PositionServiceGetPositionsResponse\x12\x86\x01\n" +
	"\vGetPosition\x12:.opensqt.market_maker.v1.PositionServiceGetPositionRequest\x1a;.opensqt.market_maker.v1.PositionServiceGetPositionResponse\x12\x82\x01\n" +
	"\x12SubscribePositions\x12A.opensqt.market_maker.v1.PositionServiceSubscribePositionsRequest\x1a'.opensqt.market_maker.v1.PositionUpdate0\x01\x12\x8c\x01\n" +
	"\rGetOpenOrders\x12<.opensqt.market_maker.v1.PositionServiceGetOpenOrdersRequest\x1a=.opensqt.market_maker.v1.PositionServiceGetOpenOrdersResponse\x12\x92\x01\n" +
	"\x0fGetOrderHistory\x12>.opensqt.market_maker.v1.PositionServiceGetOrderHistoryRequest\x1a?.opensqt.market_maker.v1.PositionServiceGetOrderHistoryResponse\x12}\n" +
	"\bGetOrder\x127.opensqt.market_maker.v1.PositionServiceGetOrderRequest\x1a8.opensqt.market_maker.v1.PositionServiceGetOrderResponse\x12}\n" +
	"\bGetFills\x127.opensqt.market_maker.v1.PositionServiceGetFillsRequest\x1a8.opensqt.market_maker.v1.PositionServiceGetFillsResponse\x12\x9b\x01\n" +
	"\x12GetPositionHistory\x12A.opensqt.market_maker.v1.PositionServiceGetPositionHistoryRequest\x1aB.opensqt.market_maker.v1.PositionServiceGetPositionHistoryResponse\x12\x8f\x01\n" +
	"\x0eGetRealizedPnL\x12=.opensqt.market_maker.v1.PositionServiceGetRealizedPnLRequest\x1a>.opensqt.market_maker.v1.PositionServiceGetRealizedPnLResponse\x12\x95\x01\n" +
	"\x10GetUnrealizedPnL\x12?.opensqt.market_maker.v1.PositionServiceGetUnrealizedPnLRequest\x1a@.opensqt.market_maker.v1.PositionServiceGetUnrealizedPnLResponseB\xc0\x01\n" +
	"\x1bcom.opensqt.market_maker.v1B\rPositionProtoP\x01Z\x18market_maker/internal/pb\xa2\x02\x03OMX\xaa\x02\x16Opensqt.MarketMaker.V1\xca\x02\x16Opensqt\\MarketMaker\\V1\xe2\x02\"Opensqt\\MarketMaker\\V1\\GPBMetadata\xea\x02\x18Opensqt::MarketMaker::V1b\x06proto3"

var (
	file_opensqt_market_maker_v1_position_proto_rawDescOnce sync.Once
	file_opensqt_market_maker_v1_position_proto_rawDescData []byte
)

func file_opensqt_market_maker_v1_position_proto_rawDescGZIP() []byte {
	file_opensqt_market_maker_v1_position_proto_rawDescOnce.Do(func() {
		file_opensqt_market_maker_v1_position_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_position_proto_rawDesc), len(file_opensqt_market_maker_v1_position_proto_rawDesc)))
	})
	return file_opensqt_market_maker_v1_position_proto_rawDescData
}

var file_opensqt_market_maker_v1_position_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_opensqt_market_maker_v1_position_proto_goTypes = []any{
	(*PositionServiceGetPositionsRequest)(nil),        // 0: opensqt.market_maker.v1.PositionServiceGetPositionsRequest
	(*PositionServiceGetPositionsResponse)(nil),       // 1: opensqt.market_maker.v1.PositionServiceGetPositionsResponse
	(*PositionData)(nil),                              // 2: opensqt.market_maker.v1.PositionData
	(*PositionServiceGetPositionRequest)(nil),         // 3: opensqt.market_maker.v1.PositionServiceGetPositionRequest
	(*PositionServiceGetPositionResponse)(nil),        // 4: opensqt.market_maker.v1.PositionServiceGetPositionResponse
	(*PositionServiceSubscribePositionsRequest)(nil),  // 5: opensqt.market_maker.v1.PositionServiceSubscribePositionsRequest
	(*PositionUpdate)(nil),                            // 6: opensqt.market_maker.v1.PositionUpdate
	(*PositionServiceGetOpenOrdersRequest)(nil),       // 7: opensqt.market_maker.v1.PositionServiceGetOpenOrdersRequest
	(*PositionServiceGetOpenOrdersResponse)(nil),      // 8: opensqt.market_maker.v1.PositionServiceGetOpenOrdersResponse
	(*PositionServiceGetOrderHistoryRequest)(nil),     // 9: opensqt.market_maker.v1.PositionServiceGetOrderHistoryRequest
	(*PositionServiceGetOrderHistoryResponse)(nil),    // 10: opensqt.market_maker.v1.PositionServiceGetOrderHistoryResponse
	(*PositionServiceGetOrderRequest)(nil),            // 11: opensqt.market_maker.v1.PositionServiceGetOrderRequest
	(*PositionServiceGetOrderResponse)(nil),           // 12: opensqt.market_maker.v1.PositionServiceGetOrderResponse
	(*Fill)(nil),                                      // 13: opensqt.market_maker.v1.Fill
	(*PositionServiceGetFillsRequest)(nil),            // 14: opensqt.market_maker.v1.PositionServiceGetFillsRequest
	(*PositionServiceGetFillsResponse)(nil),           // 15: opensqt.market_maker.v1.PositionServiceGetFillsResponse
	(*PositionServiceGetPositionHistoryRequest)(nil),  // 16: opensqt.market_maker.v1.PositionServiceGetPositionHistoryRequest
	(*PositionServiceGetPositionHistoryResponse)(nil), // 17: opensqt.market_maker.v1.PositionServiceGetPositionHistoryResponse
	(*PositionSnapshotData)(nil),                      // 18: opensqt.market_maker.v1.PositionSnapshotData
	(*PositionServiceGetRealizedPnLRequest)(nil),      // 19: opensqt.market_maker.v1.PositionServiceGetRealizedPnLRequest
	(*PositionServiceGetRealizedPnLResponse)(nil),     // 20: opensqt.market_maker.v1.PositionServiceGetRealizedPnLResponse
	(*SymbolPnL)(nil),                                 // 21: opensqt.market_maker.v1.SymbolPnL
	(*PositionServiceGetUnrealizedPnLRequest)(nil),    // 22: opensqt.market_maker.v1.PositionServiceGetUnrealizedPnLRequest
	(*PositionServiceGetUnrealizedPnLResponse)(nil),   // 23: opensqt.market_maker.v1.PositionServiceGetUnrealizedPnLResponse
	(*PositionPnL)(nil),                               // 24: opensqt.market_maker.v1.PositionPnL
	(*decimal.Decimal)(nil),                           // 25: google.type.Decimal
	(*Order)(nil),                                     // 26: opensqt.market_maker.v1.Order
}
var file_opensqt_market_maker_v1_position_proto_depIdxs = []int32{
	2,  // 0: opensqt.market_maker.v1.PositionServiceGetPositionsResponse.positions:type_name -> opensqt.market_maker.v1.PositionData
	25, // 1: opensqt.market_maker.v1.PositionData.quantity:type_name -> google.type.Decimal
	25, // 2: opensqt.market_maker.v1.PositionData.entry_price:type_name -> google.type.Decimal
	25, // 3: opensqt.market_maker.v1.PositionData.current_price:type_name -> google.type.Decimal
	25, // 4: opensqt.market_maker.v1.PositionData.unrealized_pnl:type_name -> google.type.Decimal
	25, // 5: opensqt.market_maker.v1.PositionData.realized_pnl:type_name -> google.type.Decimal
	2,  // 6: opensqt.market_maker.v1.PositionServiceGetPositionResponse.position:type_name -> opensqt.market_maker.v1.PositionData
	26, // 7: opensqt.market_maker.v1.PositionServiceGetPositionResponse.open_orders:type_name -> opensqt.market_maker.v1.Order
	2,  // 8: opensqt.market_maker.v1.PositionUpdate.position:type_name -> opensqt.market_maker.v1.PositionData
	26, // 9: opensqt.market_maker.v1.PositionUpdate.trigger_order:type_name -> opensqt.market_maker.v1.Order
	26, // 10: opensqt.market_maker.v1.PositionServiceGetOpenOrdersResponse.orders:type_name -> opensqt.market_maker.v1.Order
	26, // 11: opensqt.market_maker.v1.PositionServiceGetOrderHistoryResponse.orders:type_name -> opensqt.market_maker.v1.Order
	26, // 12: opensqt.market_maker.v1.PositionServiceGetOrderResponse.order:type_name -> opensqt.market_maker.v1.Order
	13, // 13: opensqt.market_maker.v1.PositionServiceGetOrderResponse.fills:type_name -> opensqt.market_maker.v1.Fill
	25, // 14: opensqt.market_maker.v1.Fill.quantity:type_name -> google.type.Decimal
	25, // 15: opensqt.market_maker.v1.Fill.price:type_name -> google.type.Decimal
	25, // 16: opensqt.market_maker.v1.Fill.fee:type_name -> google.type.Decimal
	13, // 17: opensqt.market_maker.v1.PositionServiceGetFillsResponse.fills:type_name -> opensqt.market_maker.v1.Fill
	18, // 18: opensqt.market_maker.v1.PositionServiceGetPositionHistoryResponse.snapshots:type_name -> opensqt.market_maker.v1.PositionSnapshotData
	25, // 19: opensqt.market_maker.v1.PositionSnapshotData.quantity:type_name -> google.type.Decimal
	25, // 20: opensqt.market_maker.v1.PositionSnapshotData.entry_price:type_name -> google.type.Decimal
	25, // 21: opensqt.market_maker.v1.PositionSnapshotData.market_price:type_name -> google.type.Decimal
	25, // 22: opensqt.market_maker.v1.PositionSnapshotData.unrealized_pnl:type_name -> google.type.Decimal
	25, // 23: opensqt.market_maker.v1.PositionServiceGetRealizedPnLResponse.total_pnl:type_name -> google.type.Decimal
	21, // 24: opensqt.market_maker.v1.PositionServiceGetRealizedPnLResponse.by_symbol:type_name -> opensqt.market_maker.v1.SymbolPnL
	25, // 25: opensqt.market_maker.v1.SymbolPnL.realized_pnl:type_name -> google.type.Decimal
	25, // 26: opensqt.market_maker.v1.PositionServiceGetUnrealizedPnLResponse.total_pnl:type_name -> google.type.Decimal
	24, // 27: opensqt.market_maker.v1.PositionServiceGetUnrealizedPnLResponse.positions:type_name -> opensqt.market_maker.v1.PositionPnL
	25, // 28: opensqt.market_maker.v1.PositionPnL.quantity:type_name -> google.type.Decimal
	25, // 29: opensqt.market_maker.v1.PositionPnL.entry_price:type_name -> google.type.Decimal
	25, // 30: opensqt.market_maker.v1.PositionPnL.current_price:type_name -> google.type.Decimal
	25, // 31: opensqt.market_maker.v1.PositionPnL.unrealized_pnl:type_name -> google.type.Decimal
	0,  // 32: opensqt.market_maker.v1.PositionService.GetPositions:input_type -> opensqt.market_maker.v1.PositionServiceGetPositionsRequest
	3,  // 33: opensqt.market_maker.v1.PositionService.GetPosition:input_type -> opensqt.market_maker.v1.PositionServiceGetPositionRequest
	5,  // 34: opensqt.market_maker.v1.PositionService.SubscribePositions:input_type -> opensqt.market_maker.v1.PositionServiceSubscribePositionsRequest
	7,  // 35: opensqt.market_maker.v1.PositionService.GetOpenOrders:input_type -> opensqt.market_maker.v1.PositionServiceGetOpenOrdersRequest
	9,  // 36: opensqt.market_maker.v1.PositionService.GetOrderHistory:input_type -> opensqt.market_maker.v1.PositionServiceGetOrderHistoryRequest
	11, // 37: opensqt.market_maker.v1.PositionService.GetOrder:input_type -> opensqt.market_maker.v1.PositionServiceGetOrderRequest
	14, // 38: opensqt.market_maker.v1.PositionService.GetFills:input_type -> opensqt.market_maker.v1.PositionServiceGetFillsRequest
	16, // 39: opensqt.market_maker.v1.PositionService.GetPositionHistory:input_type -> opensqt.market_maker.v1.PositionServiceGetPositionHistoryRequest
	19, // 40: opensqt.market_maker.v1.PositionService.GetRealizedPnL:input_type -> opensqt.market_maker.v1.PositionServiceGetRealizedPnLRequest
	22, // 41: opensqt.market_maker.v1.PositionService.GetUnrealizedPnL:input_type -> opensqt.market_maker.v1.PositionServiceGetUnrealizedPnLRequest
	1,  // 42: opensqt.market_maker.v1.PositionService.GetPositions:output_type -> opensqt.market_maker.v1.PositionServiceGetPositionsResponse
	4,  // 43: opensqt.market_maker.v1.PositionService.GetPosition:output_type -> opensqt.market_maker.v1.PositionServiceGetPositionResponse
	6,  // 44: opensqt.market_maker.v1.PositionService.SubscribePositions:output_type -> opensqt.market_maker.v1.PositionUpdate
	8,  // 45: opensqt.market_maker.v1.PositionService.GetOpenOrders:output_type -> opensqt.market_maker.v1.PositionServiceGetOpenOrdersResponse
	10, // 46: opensqt.market_maker.v1.PositionService.GetOrderHistory:output_type -> opensqt.market_maker.v1.PositionServiceGetOrderHistoryResponse
	12, // 47: opensqt.market_maker.v1.PositionService.GetOrder:output_type -> opensqt.market_maker.v1.PositionServiceGetOrderResponse
	15, // 48: opensqt.market_maker.v1.PositionService.GetFills:output_type -> opensqt.market_maker.v1.PositionServiceGetFillsResponse
	17, // 49: opensqt.market_maker.v1.PositionService.GetPositionHistory:output_type -> opensqt.market_maker.v1.PositionServiceGetPositionHistoryResponse
	20, // 50: opensqt.market_maker.v1.PositionService.GetRealizedPnL:output_type -> opensqt.market_maker.v1.PositionServiceGetRealizedPnLResponse
	23, // 51: opensqt.market_maker.v1.PositionService.GetUnrealizedPnL:output_type -> opensqt.market_maker.v1.PositionServiceGetUnrealizedPnLResponse
	42, // [42:52] is the sub-list for method output_type
	32, // [32:42] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_opensqt_market_maker_v1_position_proto_init() }
func file_opensqt_market_maker_v1_position_proto_init() {
	if File_opensqt_market_maker_v1_position_proto != nil {
		return
	}
	file_opensqt_market_maker_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_position_proto_rawDesc), len(file_opensqt_market_maker_v1_position_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_opensqt_market_maker_v1_position_proto_goTypes,
		DependencyIndexes: file_opensqt_market_maker_v1_position_proto_depIdxs,
		MessageInfos:      file_opensqt_market_maker_v1_position_proto_msgTypes,
	}.Build()
	File_opensqt_market_maker_v1_position_proto = out.File
	file_opensqt_market_maker_v1_position_proto_goTypes = nil
	file_opensqt_market_maker_v1_position_proto_depIdxs = nil
}
