// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: opensqt/market_maker/v1/position.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PositionService_GetPositions_FullMethodName       = "/opensqt.market_maker.v1.PositionService/GetPositions"
	PositionService_GetPosition_FullMethodName        = "/opensqt.market_maker.v1.PositionService/GetPosition"
	PositionService_SubscribePositions_FullMethodName = "/opensqt.market_maker.v1.PositionService/SubscribePositions"
	PositionService_GetOpenOrders_FullMethodName      = "/opensqt.market_maker.v1.PositionService/GetOpenOrders"
	PositionService_GetOrderHistory_FullMethodName    = "/opensqt.market_maker.v1.PositionService/GetOrderHistory"
	PositionService_GetOrder_FullMethodName           = "/opensqt.market_maker.v1.PositionService/GetOrder"
	PositionService_GetFills_FullMethodName           = "/opensqt.market_maker.v1.PositionService/GetFills"
	PositionService_GetPositionHistory_FullMethodName = "/opensqt.market_maker.v1.PositionService/GetPositionHistory"
	PositionService_GetRealizedPnL_FullMethodName     = "/opensqt.market_maker.v1.PositionService/GetRealizedPnL"
	PositionService_GetUnrealizedPnL_FullMethodName   = "/opensqt.market_maker.v1.PositionService/GetUnrealizedPnL"
)

// PositionServiceClient is the client API for PositionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PositionServiceClient interface {
	// Query positions
	GetPositions(ctx context.Context, in *PositionServiceGetPositionsRequest, opts ...grpc.CallOption) (*PositionServiceGetPositionsResponse, error)
	GetPosition(ctx context.Context, in *PositionServiceGetPositionRequest, opts ...grpc.CallOption) (*PositionServiceGetPositionResponse, error)
	// Subscribe to position updates (streaming)
	SubscribePositions(ctx context.Context, in *PositionServiceSubscribePositionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionUpdate], error)
	// Query orders
	GetOpenOrders(ctx context.Context, in *PositionServiceGetOpenOrdersRequest, opts ...grpc.CallOption) (*PositionServiceGetOpenOrdersResponse, error)
	GetOrderHistory(ctx context.Context, in *PositionServiceGetOrderHistoryRequest, opts ...grpc.CallOption) (*PositionServiceGetOrderHistoryResponse, error)
	GetOrder(ctx context.Context, in *PositionServiceGetOrderRequest, opts ...grpc.CallOption) (*PositionServiceGetOrderResponse, error)
	// Query fills
	GetFills(ctx context.Context, in *PositionServiceGetFillsRequest, opts ...grpc.CallOption) (*PositionServiceGetFillsResponse, error)
	// Position history
	GetPositionHistory(ctx context.Context, in *PositionServiceGetPositionHistoryRequest, opts ...grpc.CallOption) (*PositionServiceGetPositionHistoryResponse, error)
	// PnL queries
	GetRealizedPnL(ctx context.Context, in *PositionServiceGetRealizedPnLRequest, opts ...grpc.CallOption) (*PositionServiceGetRealizedPnLResponse, error)
	GetUnrealizedPnL(ctx context.Context, in *PositionServiceGetUnrealizedPnLRequest, opts ...grpc.CallOption) (*PositionServiceGetUnrealizedPnLResponse, error)
}

type positionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPositionServiceClient(cc grpc.ClientConnInterface) PositionServiceClient {
	return &positionServiceClient{cc}
}

func (c *positionServiceClient) GetPositions(ctx context.Context, in *PositionServiceGetPositionsRequest, opts ...grpc.CallOption) (*PositionServiceGetPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionServiceGetPositionsResponse)
	err := c.cc.Invoke(ctx, PositionService_GetPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) GetPosition(ctx context.Context, in *PositionServiceGetPositionRequest, opts ...grpc.CallOption) (*PositionServiceGetPositionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionServiceGetPositionResponse)
	err := c.cc.Invoke(ctx, PositionService_GetPosition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) SubscribePositions(ctx context.Context, in *PositionServiceSubscribePositionsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PositionUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PositionService_ServiceDesc.Streams[0], PositionService_SubscribePositions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PositionServiceSubscribePositionsRequest, PositionUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PositionService_SubscribePositionsClient = grpc.ServerStreamingClient[PositionUpdate]

func (c *positionServiceClient) GetOpenOrders(ctx context.Context, in *PositionServiceGetOpenOrdersRequest, opts ...grpc.CallOption) (*PositionServiceGetOpenOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionServiceGetOpenOrdersResponse)
	err := c.cc.Invoke(ctx, PositionService_GetOpenOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) GetOrderHistory(ctx context.Context, in *PositionServiceGetOrderHistoryRequest, opts ...grpc.CallOption) (*PositionServiceGetOrderHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionServiceGetOrderHistoryResponse)
	err := c.cc.Invoke(ctx, PositionService_GetOrderHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) GetOrder(ctx context.Context, in *PositionServiceGetOrderRequest, opts ...grpc.CallOption) (*PositionServiceGetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionServiceGetOrderResponse)
	err := c.cc.Invoke(ctx, PositionService_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) GetFills(ctx context.Context, in *PositionServiceGetFillsRequest, opts ...grpc.CallOption) (*PositionServiceGetFillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionServiceGetFillsResponse)
	err := c.cc.Invoke(ctx, PositionService_GetFills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) GetPositionHistory(ctx context.Context, in *PositionServiceGetPositionHistoryRequest, opts ...grpc.CallOption) (*PositionServiceGetPositionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionServiceGetPositionHistoryResponse)
	err := c.cc.Invoke(ctx, PositionService_GetPositionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) GetRealizedPnL(ctx context.Context, in *PositionServiceGetRealizedPnLRequest, opts ...grpc.CallOption) (*PositionServiceGetRealizedPnLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionServiceGetRealizedPnLResponse)
	err := c.cc.Invoke(ctx, PositionService_GetRealizedPnL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *positionServiceClient) GetUnrealizedPnL(ctx context.Context, in *PositionServiceGetUnrealizedPnLRequest, opts ...grpc.CallOption) (*PositionServiceGetUnrealizedPnLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PositionServiceGetUnrealizedPnLResponse)
	err := c.cc.Invoke(ctx, PositionService_GetUnrealizedPnL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PositionServiceServer is the server API for PositionService service.
// All implementations must embed UnimplementedPositionServiceServer
// for forward compatibility.
type PositionServiceServer interface {
	// Query positions
	GetPositions(context.Context, *PositionServiceGetPositionsRequest) (*PositionServiceGetPositionsResponse, error)
	GetPosition(context.Context, *PositionServiceGetPositionRequest) (*PositionServiceGetPositionResponse, error)
	// Subscribe to position updates (streaming)
	SubscribePositions(*PositionServiceSubscribePositionsRequest, grpc.ServerStreamingServer[PositionUpdate]) error
	// Query orders
	GetOpenOrders(context.Context, *PositionServiceGetOpenOrdersRequest) (*PositionServiceGetOpenOrdersResponse, error)
	GetOrderHistory(context.Context, *PositionServiceGetOrderHistoryRequest) (*PositionServiceGetOrderHistoryResponse, error)
	GetOrder(context.Context, *PositionServiceGetOrderRequest) (*PositionServiceGetOrderResponse, error)
	// Query fills
	GetFills(context.Context, *PositionServiceGetFillsRequest) (*PositionServiceGetFillsResponse, error)
	// Position history
	GetPositionHistory(context.Context, *PositionServiceGetPositionHistoryRequest) (*PositionServiceGetPositionHistoryResponse, error)
	// PnL queries
	GetRealizedPnL(context.Context, *PositionServiceGetRealizedPnLRequest) (*PositionServiceGetRealizedPnLResponse, error)
	GetUnrealizedPnL(context.Context, *PositionServiceGetUnrealizedPnLRequest) (*PositionServiceGetUnrealizedPnLResponse, error)
	mustEmbedUnimplementedPositionServiceServer()
}

// UnimplementedPositionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPositionServiceServer struct{}

func (UnimplementedPositionServiceServer) GetPositions(context.Context, *PositionServiceGetPositionsRequest) (*PositionServiceGetPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPositions not implemented")
}
func (UnimplementedPositionServiceServer) GetPosition(context.Context, *PositionServiceGetPositionRequest) (*PositionServiceGetPositionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPosition not implemented")
}
func (UnimplementedPositionServiceServer) SubscribePositions(*PositionServiceSubscribePositionsRequest, grpc.ServerStreamingServer[PositionUpdate]) error {
	return status.Error(codes.Unimplemented, "method SubscribePositions not implemented")
}
func (UnimplementedPositionServiceServer) GetOpenOrders(context.Context, *PositionServiceGetOpenOrdersRequest) (*PositionServiceGetOpenOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOpenOrders not implemented")
}
func (UnimplementedPositionServiceServer) GetOrderHistory(context.Context, *PositionServiceGetOrderHistoryRequest) (*PositionServiceGetOrderHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderHistory not implemented")
}
func (UnimplementedPositionServiceServer) GetOrder(context.Context, *PositionServiceGetOrderRequest) (*PositionServiceGetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedPositionServiceServer) GetFills(context.Context, *PositionServiceGetFillsRequest) (*PositionServiceGetFillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFills not implemented")
}
func (UnimplementedPositionServiceServer) GetPositionHistory(context.Context, *PositionServiceGetPositionHistoryRequest) (*PositionServiceGetPositionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPositionHistory not implemented")
}
func (UnimplementedPositionServiceServer) GetRealizedPnL(context.Context, *PositionServiceGetRealizedPnLRequest) (*PositionServiceGetRealizedPnLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRealizedPnL not implemented")
}
func (UnimplementedPositionServiceServer) GetUnrealizedPnL(context.Context, *PositionServiceGetUnrealizedPnLRequest) (*PositionServiceGetUnrealizedPnLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUnrealizedPnL not implemented")
}
func (UnimplementedPositionServiceServer) mustEmbedUnimplementedPositionServiceServer() {}
func (UnimplementedPositionServiceServer) testEmbeddedByValue()                         {}

// UnsafePositionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PositionServiceServer will
// result in compilation errors.
type UnsafePositionServiceServer interface {
	mustEmbedUnimplementedPositionServiceServer()
}

func RegisterPositionServiceServer(s grpc.ServiceRegistrar, srv PositionServiceServer) {
	// If the following call panics, it indicates UnimplementedPositionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PositionService_ServiceDesc, srv)
}

func _PositionService_GetPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionServiceGetPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetPositions(ctx, req.(*PositionServiceGetPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionServiceGetPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetPosition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetPosition(ctx, req.(*PositionServiceGetPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_SubscribePositions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PositionServiceSubscribePositionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PositionServiceServer).SubscribePositions(m, &grpc.GenericServerStream[PositionServiceSubscribePositionsRequest, PositionUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PositionService_SubscribePositionsServer = grpc.ServerStreamingServer[PositionUpdate]

func _PositionService_GetOpenOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionServiceGetOpenOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetOpenOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetOpenOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetOpenOrders(ctx, req.(*PositionServiceGetOpenOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_GetOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionServiceGetOrderHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetOrderHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetOrderHistory(ctx, req.(*PositionServiceGetOrderHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionServiceGetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetOrder(ctx, req.(*PositionServiceGetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_GetFills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionServiceGetFillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetFills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetFills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetFills(ctx, req.(*PositionServiceGetFillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_GetPositionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionServiceGetPositionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetPositionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetPositionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetPositionHistory(ctx, req.(*PositionServiceGetPositionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_GetRealizedPnL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionServiceGetRealizedPnLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetRealizedPnL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetRealizedPnL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetRealizedPnL(ctx, req.(*PositionServiceGetRealizedPnLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PositionService_GetUnrealizedPnL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PositionServiceGetUnrealizedPnLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PositionServiceServer).GetUnrealizedPnL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PositionService_GetUnrealizedPnL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PositionServiceServer).GetUnrealizedPnL(ctx, req.(*PositionServiceGetUnrealizedPnLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PositionService_ServiceDesc is the grpc.ServiceDesc for PositionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PositionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opensqt.market_maker.v1.PositionService",
	HandlerType: (*PositionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPositions",
			Handler:    _PositionService_GetPositions_Handler,
		},
		{
			MethodName: "GetPosition",
			Handler:    _PositionService_GetPosition_Handler,
		},
		{
			MethodName: "GetOpenOrders",
			Handler:    _PositionService_GetOpenOrders_Handler,
		},
		{
			MethodName: "GetOrderHistory",
			Handler:    _PositionService_GetOrderHistory_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _PositionService_GetOrder_Handler,
		},
		{
			MethodName: "GetFills",
			Handler:    _PositionService_GetFills_Handler,
		},
		{
			MethodName: "GetPositionHistory",
			Handler:    _PositionService_GetPositionHistory_Handler,
		},
		{
			MethodName: "GetRealizedPnL",
			Handler:    _PositionService_GetRealizedPnL_Handler,
		},
		{
			MethodName: "GetUnrealizedPnL",
			Handler:    _PositionService_GetUnrealizedPnL_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePositions",
			Handler:       _PositionService_SubscribePositions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "opensqt/market_maker/v1/position.proto",
}
