// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: opensqt/market_maker/v1/resources.proto

package pb

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	TotalWalletBalance     *decimal.Decimal       `protobuf:"bytes,1,opt,name=total_wallet_balance,json=totalWalletBalance,proto3" json:"total_wallet_balance,omitempty"`
	TotalMarginBalance     *decimal.Decimal       `protobuf:"bytes,2,opt,name=total_margin_balance,json=totalMarginBalance,proto3" json:"total_margin_balance,omitempty"`
	AvailableBalance       *decimal.Decimal       `protobuf:"bytes,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	Positions              []*Position            `protobuf:"bytes,4,rep,name=positions,proto3" json:"positions,omitempty"`
	AccountLeverage        int32                  `protobuf:"varint,5,opt,name=account_leverage,json=accountLeverage,proto3" json:"account_leverage,omitempty"`
	IsUnified              bool                   `protobuf:"varint,6,opt,name=is_unified,json=isUnified,proto3" json:"is_unified,omitempty"`
	HealthScore            *decimal.Decimal       `protobuf:"bytes,7,opt,name=health_score,json=healthScore,proto3" json:"health_score,omitempty"`
	MarginMode             MarginMode             `protobuf:"varint,8,opt,name=margin_mode,json=marginMode,proto3,enum=opensqt.market_maker.v1.MarginMode" json:"margin_mode,omitempty"`
	AdjustedEquity         *decimal.Decimal       `protobuf:"bytes,9,opt,name=adjusted_equity,json=adjustedEquity,proto3" json:"adjusted_equity,omitempty"`
	TotalMaintenanceMargin *decimal.Decimal       `protobuf:"bytes,10,opt,name=total_maintenance_margin,json=totalMaintenanceMargin,proto3" json:"total_maintenance_margin,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetTotalWalletBalance() *decimal.Decimal {
	if x != nil {
		return x.TotalWalletBalance
	}
	return nil
}

func (x *Account) GetTotalMarginBalance() *decimal.Decimal {
	if x != nil {
		return x.TotalMarginBalance
	}
	return nil
}

func (x *Account) GetAvailableBalance() *decimal.Decimal {
	if x != nil {
		return x.AvailableBalance
	}
	return nil
}

func (x *Account) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *Account) GetAccountLeverage() int32 {
	if x != nil {
		return x.AccountLeverage
	}
	return 0
}

func (x *Account) GetIsUnified() bool {
	if x != nil {
		return x.IsUnified
	}
	return false
}

func (x *Account) GetHealthScore() *decimal.Decimal {
	if x != nil {
		return x.HealthScore
	}
	return nil
}

func (x *Account) GetMarginMode() MarginMode {
	if x != nil {
		return x.MarginMode
	}
	return MarginMode_MARGIN_MODE_UNSPECIFIED
}

func (x *Account) GetAdjustedEquity() *decimal.Decimal {
	if x != nil {
		return x.AdjustedEquity
	}
	return nil
}

func (x *Account) GetTotalMaintenanceMargin() *decimal.Decimal {
	if x != nil {
		return x.TotalMaintenanceMargin
	}
	return nil
}

type Position struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Symbol           string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Size             *decimal.Decimal       `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	EntryPrice       *decimal.Decimal       `protobuf:"bytes,3,opt,name=entry_price,json=entryPrice,proto3" json:"entry_price,omitempty"`
	MarkPrice        *decimal.Decimal       `protobuf:"bytes,4,opt,name=mark_price,json=markPrice,proto3" json:"mark_price,omitempty"`
	UnrealizedPnl    *decimal.Decimal       `protobuf:"bytes,5,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	Leverage         int32                  `protobuf:"varint,6,opt,name=leverage,proto3" json:"leverage,omitempty"`
	MarginType       string                 `protobuf:"bytes,7,opt,name=margin_type,json=marginType,proto3" json:"margin_type,omitempty"`
	IsolatedMargin   *decimal.Decimal       `protobuf:"bytes,8,opt,name=isolated_margin,json=isolatedMargin,proto3" json:"isolated_margin,omitempty"`
	LiquidationPrice *decimal.Decimal       `protobuf:"bytes,9,opt,name=liquidation_price,json=liquidationPrice,proto3" json:"liquidation_price,omitempty"`
	Haircut          *decimal.Decimal       `protobuf:"bytes,10,opt,name=haircut,proto3" json:"haircut,omitempty"`
	NarrativeSector  string                 `protobuf:"bytes,11,opt,name=narrative_sector,json=narrativeSector,proto3" json:"narrative_sector,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{1}
}

func (x *Position) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Position) GetSize() *decimal.Decimal {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Position) GetEntryPrice() *decimal.Decimal {
	if x != nil {
		return x.EntryPrice
	}
	return nil
}

func (x *Position) GetMarkPrice() *decimal.Decimal {
	if x != nil {
		return x.MarkPrice
	}
	return nil
}

func (x *Position) GetUnrealizedPnl() *decimal.Decimal {
	if x != nil {
		return x.UnrealizedPnl
	}
	return nil
}

func (x *Position) GetLeverage() int32 {
	if x != nil {
		return x.Leverage
	}
	return 0
}

func (x *Position) GetMarginType() string {
	if x != nil {
		return x.MarginType
	}
	return ""
}

func (x *Position) GetIsolatedMargin() *decimal.Decimal {
	if x != nil {
		return x.IsolatedMargin
	}
	return nil
}

func (x *Position) GetLiquidationPrice() *decimal.Decimal {
	if x != nil {
		return x.LiquidationPrice
	}
	return nil
}

func (x *Position) GetHaircut() *decimal.Decimal {
	if x != nil {
		return x.Haircut
	}
	return nil
}

func (x *Position) GetNarrativeSector() string {
	if x != nil {
		return x.NarrativeSector
	}
	return ""
}

type SymbolInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbol            string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PricePrecision    int32                  `protobuf:"varint,2,opt,name=price_precision,json=pricePrecision,proto3" json:"price_precision,omitempty"`
	QuantityPrecision int32                  `protobuf:"varint,3,opt,name=quantity_precision,json=quantityPrecision,proto3" json:"quantity_precision,omitempty"`
	BaseAsset         string                 `protobuf:"bytes,4,opt,name=base_asset,json=baseAsset,proto3" json:"base_asset,omitempty"`
	QuoteAsset        string                 `protobuf:"bytes,5,opt,name=quote_asset,json=quoteAsset,proto3" json:"quote_asset,omitempty"`
	MinQuantity       *decimal.Decimal       `protobuf:"bytes,6,opt,name=min_quantity,json=minQuantity,proto3" json:"min_quantity,omitempty"`
	MinNotional       *decimal.Decimal       `protobuf:"bytes,7,opt,name=min_notional,json=minNotional,proto3" json:"min_notional,omitempty"`
	TickSize          *decimal.Decimal       `protobuf:"bytes,8,opt,name=tick_size,json=tickSize,proto3" json:"tick_size,omitempty"`
	StepSize          *decimal.Decimal       `protobuf:"bytes,9,opt,name=step_size,json=stepSize,proto3" json:"step_size,omitempty"`
	NarrativeSector   string                 `protobuf:"bytes,10,opt,name=narrative_sector,json=narrativeSector,proto3" json:"narrative_sector,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SymbolInfo) Reset() {
	*x = SymbolInfo{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolInfo) ProtoMessage() {}

func (x *SymbolInfo) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolInfo.ProtoReflect.Descriptor instead.
func (*SymbolInfo) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{2}
}

func (x *SymbolInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SymbolInfo) GetPricePrecision() int32 {
	if x != nil {
		return x.PricePrecision
	}
	return 0
}

func (x *SymbolInfo) GetQuantityPrecision() int32 {
	if x != nil {
		return x.QuantityPrecision
	}
	return 0
}

func (x *SymbolInfo) GetBaseAsset() string {
	if x != nil {
		return x.BaseAsset
	}
	return ""
}

func (x *SymbolInfo) GetQuoteAsset() string {
	if x != nil {
		return x.QuoteAsset
	}
	return ""
}

func (x *SymbolInfo) GetMinQuantity() *decimal.Decimal {
	if x != nil {
		return x.MinQuantity
	}
	return nil
}

func (x *SymbolInfo) GetMinNotional() *decimal.Decimal {
	if x != nil {
		return x.MinNotional
	}
	return nil
}

func (x *SymbolInfo) GetTickSize() *decimal.Decimal {
	if x != nil {
		return x.TickSize
	}
	return nil
}

func (x *SymbolInfo) GetStepSize() *decimal.Decimal {
	if x != nil {
		return x.StepSize
	}
	return nil
}

func (x *SymbolInfo) GetNarrativeSector() string {
	if x != nil {
		return x.NarrativeSector
	}
	return ""
}

type Trade struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TradeId       string                 `protobuf:"bytes,1,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	OrderId       int64                  `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          OrderSide              `protobuf:"varint,4,opt,name=side,proto3,enum=opensqt.market_maker.v1.OrderSide" json:"side,omitempty"`
	Price         *decimal.Decimal       `protobuf:"bytes,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      *decimal.Decimal       `protobuf:"bytes,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Fee           *decimal.Decimal       `protobuf:"bytes,7,opt,name=fee,proto3" json:"fee,omitempty"`
	FeeAsset      string                 `protobuf:"bytes,8,opt,name=fee_asset,json=feeAsset,proto3" json:"fee_asset,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	RealizedPnl   *decimal.Decimal       `protobuf:"bytes,10,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trade) Reset() {
	*x = Trade{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trade) ProtoMessage() {}

func (x *Trade) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trade.ProtoReflect.Descriptor instead.
func (*Trade) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{3}
}

func (x *Trade) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *Trade) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Trade) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Trade) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *Trade) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Trade) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *Trade) GetFee() *decimal.Decimal {
	if x != nil {
		return x.Fee
	}
	return nil
}

func (x *Trade) GetFeeAsset() string {
	if x != nil {
		return x.FeeAsset
	}
	return ""
}

func (x *Trade) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Trade) GetRealizedPnl() *decimal.Decimal {
	if x != nil {
		return x.RealizedPnl
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,2,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          OrderSide              `protobuf:"varint,4,opt,name=side,proto3,enum=opensqt.market_maker.v1.OrderSide" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,5,opt,name=type,proto3,enum=opensqt.market_maker.v1.OrderType" json:"type,omitempty"`
	Price         *decimal.Decimal       `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      *decimal.Decimal       `protobuf:"bytes,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ExecutedQty   *decimal.Decimal       `protobuf:"bytes,8,opt,name=executed_qty,json=executedQty,proto3" json:"executed_qty,omitempty"`
	AvgPrice      *decimal.Decimal       `protobuf:"bytes,9,opt,name=avg_price,json=avgPrice,proto3" json:"avg_price,omitempty"`
	Status        OrderStatus            `protobuf:"varint,10,opt,name=status,proto3,enum=opensqt.market_maker.v1.OrderStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdateTime    int64                  `protobuf:"varint,12,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Trades        []*Trade               `protobuf:"bytes,13,rep,name=trades,proto3" json:"trades,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{4}
}

func (x *Order) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Order) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *Order) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *Order) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *Order) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *Order) GetExecutedQty() *decimal.Decimal {
	if x != nil {
		return x.ExecutedQty
	}
	return nil
}

func (x *Order) GetAvgPrice() *decimal.Decimal {
	if x != nil {
		return x.AvgPrice
	}
	return nil
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *Order) GetTrades() []*Trade {
	if x != nil {
		return x.Trades
	}
	return nil
}

type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Open          *decimal.Decimal       `protobuf:"bytes,2,opt,name=open,proto3" json:"open,omitempty"`
	High          *decimal.Decimal       `protobuf:"bytes,3,opt,name=high,proto3" json:"high,omitempty"`
	Low           *decimal.Decimal       `protobuf:"bytes,4,opt,name=low,proto3" json:"low,omitempty"`
	Close         *decimal.Decimal       `protobuf:"bytes,5,opt,name=close,proto3" json:"close,omitempty"`
	Volume        *decimal.Decimal       `protobuf:"bytes,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsClosed      bool                   `protobuf:"varint,8,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{5}
}

func (x *Candle) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Candle) GetOpen() *decimal.Decimal {
	if x != nil {
		return x.Open
	}
	return nil
}

func (x *Candle) GetHigh() *decimal.Decimal {
	if x != nil {
		return x.High
	}
	return nil
}

func (x *Candle) GetLow() *decimal.Decimal {
	if x != nil {
		return x.Low
	}
	return nil
}

func (x *Candle) GetClose() *decimal.Decimal {
	if x != nil {
		return x.Close
	}
	return nil
}

func (x *Candle) GetVolume() *decimal.Decimal {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *Candle) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Candle) GetIsClosed() bool {
	if x != nil {
		return x.IsClosed
	}
	return false
}

type FundingRate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Exchange        string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol          string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Rate            *decimal.Decimal       `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`                                                 // Funding rate for the current interval (per-interval, not annualized); e.g., 0.0001 = 1 bp = 0.01%
	PredictedRate   *decimal.Decimal       `protobuf:"bytes,4,opt,name=predicted_rate,json=predictedRate,proto3" json:"predicted_rate,omitempty"`          // Optional; expected funding for the next interval when the venue provides it; unset if unknown
	NextFundingTime int64                  `protobuf:"varint,5,opt,name=next_funding_time,json=nextFundingTime,proto3" json:"next_funding_time,omitempty"` // Unix epoch milliseconds (UTC) of the start of the next funding interval; 0 means not applicable/unknown (e.g., spot)
	Timestamp       int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                      // Unix epoch milliseconds (UTC) when this rate was observed (exchange event time when available; otherwise connector receipt time)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FundingRate) Reset() {
	*x = FundingRate{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundingRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundingRate) ProtoMessage() {}

func (x *FundingRate) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundingRate.ProtoReflect.Descriptor instead.
func (*FundingRate) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{6}
}

func (x *FundingRate) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *FundingRate) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *FundingRate) GetRate() *decimal.Decimal {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *FundingRate) GetPredictedRate() *decimal.Decimal {
	if x != nil {
		return x.PredictedRate
	}
	return nil
}

func (x *FundingRate) GetNextFundingTime() int64 {
	if x != nil {
		return x.NextFundingTime
	}
	return 0
}

func (x *FundingRate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Ticker struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Symbol             string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	PriceChange        *decimal.Decimal       `protobuf:"bytes,2,opt,name=price_change,json=priceChange,proto3" json:"price_change,omitempty"`
	PriceChangePercent *decimal.Decimal       `protobuf:"bytes,3,opt,name=price_change_percent,json=priceChangePercent,proto3" json:"price_change_percent,omitempty"`
	LastPrice          *decimal.Decimal       `protobuf:"bytes,4,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	Volume             *decimal.Decimal       `protobuf:"bytes,5,opt,name=volume,proto3" json:"volume,omitempty"`                              // Base Volume
	QuoteVolume        *decimal.Decimal       `protobuf:"bytes,6,opt,name=quote_volume,json=quoteVolume,proto3" json:"quote_volume,omitempty"` // Quote Volume (Liquidity Proxy)
	Timestamp          int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	OpenInterest       *decimal.Decimal       `protobuf:"bytes,8,opt,name=open_interest,json=openInterest,proto3" json:"open_interest,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Ticker) Reset() {
	*x = Ticker{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ticker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ticker) ProtoMessage() {}

func (x *Ticker) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ticker.ProtoReflect.Descriptor instead.
func (*Ticker) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{7}
}

func (x *Ticker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Ticker) GetPriceChange() *decimal.Decimal {
	if x != nil {
		return x.PriceChange
	}
	return nil
}

func (x *Ticker) GetPriceChangePercent() *decimal.Decimal {
	if x != nil {
		return x.PriceChangePercent
	}
	return nil
}

func (x *Ticker) GetLastPrice() *decimal.Decimal {
	if x != nil {
		return x.LastPrice
	}
	return nil
}

func (x *Ticker) GetVolume() *decimal.Decimal {
	if x != nil {
		return x.Volume
	}
	return nil
}

func (x *Ticker) GetQuoteVolume() *decimal.Decimal {
	if x != nil {
		return x.QuoteVolume
	}
	return nil
}

func (x *Ticker) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Ticker) GetOpenInterest() *decimal.Decimal {
	if x != nil {
		return x.OpenInterest
	}
	return nil
}

// Request object for PlaceOrder, kept here as it's a fundamental resource definition
type PlaceOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          OrderSide              `protobuf:"varint,2,opt,name=side,proto3,enum=opensqt.market_maker.v1.OrderSide" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,3,opt,name=type,proto3,enum=opensqt.market_maker.v1.OrderType" json:"type,omitempty"`
	TimeInForce   TimeInForce            `protobuf:"varint,4,opt,name=time_in_force,json=timeInForce,proto3,enum=opensqt.market_maker.v1.TimeInForce" json:"time_in_force,omitempty"`
	Quantity      *decimal.Decimal       `protobuf:"bytes,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         *decimal.Decimal       `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	ReduceOnly    bool                   `protobuf:"varint,7,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	PostOnly      bool                   `protobuf:"varint,8,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,9,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	UseMargin     bool                   `protobuf:"varint,10,opt,name=use_margin,json=useMargin,proto3" json:"use_margin,omitempty"` // Use margin account for spot exchanges
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceOrderRequest) Reset() {
	*x = PlaceOrderRequest{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceOrderRequest) ProtoMessage() {}

func (x *PlaceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceOrderRequest.ProtoReflect.Descriptor instead.
func (*PlaceOrderRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{8}
}

func (x *PlaceOrderRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PlaceOrderRequest) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetTimeInForce() TimeInForce {
	if x != nil {
		return x.TimeInForce
	}
	return TimeInForce_TIME_IN_FORCE_UNSPECIFIED
}

func (x *PlaceOrderRequest) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *PlaceOrderRequest) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *PlaceOrderRequest) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *PlaceOrderRequest) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

func (x *PlaceOrderRequest) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *PlaceOrderRequest) GetUseMargin() bool {
	if x != nil {
		return x.UseMargin
	}
	return false
}

type ArbitrageEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpotExchange  string                 `protobuf:"bytes,1,opt,name=spot_exchange,json=spotExchange,proto3" json:"spot_exchange,omitempty"`
	PerpExchange  string                 `protobuf:"bytes,2,opt,name=perp_exchange,json=perpExchange,proto3" json:"perp_exchange,omitempty"`
	SpotOrder     *PlaceOrderRequest     `protobuf:"bytes,3,opt,name=spot_order,json=spotOrder,proto3" json:"spot_order,omitempty"`
	PerpOrder     *PlaceOrderRequest     `protobuf:"bytes,4,opt,name=perp_order,json=perpOrder,proto3" json:"perp_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbitrageEntryRequest) Reset() {
	*x = ArbitrageEntryRequest{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitrageEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitrageEntryRequest) ProtoMessage() {}

func (x *ArbitrageEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitrageEntryRequest.ProtoReflect.Descriptor instead.
func (*ArbitrageEntryRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{9}
}

func (x *ArbitrageEntryRequest) GetSpotExchange() string {
	if x != nil {
		return x.SpotExchange
	}
	return ""
}

func (x *ArbitrageEntryRequest) GetPerpExchange() string {
	if x != nil {
		return x.PerpExchange
	}
	return ""
}

func (x *ArbitrageEntryRequest) GetSpotOrder() *PlaceOrderRequest {
	if x != nil {
		return x.SpotOrder
	}
	return nil
}

func (x *ArbitrageEntryRequest) GetPerpOrder() *PlaceOrderRequest {
	if x != nil {
		return x.PerpOrder
	}
	return nil
}

type ArbitrageExitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpotExchange  string                 `protobuf:"bytes,1,opt,name=spot_exchange,json=spotExchange,proto3" json:"spot_exchange,omitempty"`
	PerpExchange  string                 `protobuf:"bytes,2,opt,name=perp_exchange,json=perpExchange,proto3" json:"perp_exchange,omitempty"`
	SpotOrder     *PlaceOrderRequest     `protobuf:"bytes,3,opt,name=spot_order,json=spotOrder,proto3" json:"spot_order,omitempty"`
	PerpOrder     *PlaceOrderRequest     `protobuf:"bytes,4,opt,name=perp_order,json=perpOrder,proto3" json:"perp_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbitrageExitRequest) Reset() {
	*x = ArbitrageExitRequest{}
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbitrageExitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbitrageExitRequest) ProtoMessage() {}

func (x *ArbitrageExitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_resources_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbitrageExitRequest.ProtoReflect.Descriptor instead.
func (*ArbitrageExitRequest) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_resources_proto_rawDescGZIP(), []int{10}
}

func (x *ArbitrageExitRequest) GetSpotExchange() string {
	if x != nil {
		return x.SpotExchange
	}
	return ""
}

func (x *ArbitrageExitRequest) GetPerpExchange() string {
	if x != nil {
		return x.PerpExchange
	}
	return ""
}

func (x *ArbitrageExitRequest) GetSpotOrder() *PlaceOrderRequest {
	if x != nil {
		return x.SpotOrder
	}
	return nil
}

func (x *ArbitrageExitRequest) GetPerpOrder() *PlaceOrderRequest {
	if x != nil {
		return x.PerpOrder
	}
	return nil
}

var File_opensqt_market_maker_v1_resources_proto protoreflect.FileDescriptor

const file_opensqt_market_maker_v1_resources_proto_rawDesc = "" +
	"\n" +
	"'opensqt/market_maker/v1/resources.proto\x12\x17opensqt.market_maker.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/type/decimal.proto\x1a#opensqt/market_maker/v1/types.proto\"\xf5\x04\n" +
	"\aAccount\x12F\n" +
	"\x14total_wallet_balance\x18\x01 \x01(\v2\x14.google.type.DecimalR\x12totalWalletBalance\x12F\n" +
	"\x14total_margin_balance\x18\x02 \x01(\v2\x14.google.type.DecimalR\x12totalMarginBalance\x12A\n" +
	"\x11available_balance\x18\x03 \x01(\v2\x14.google.type.DecimalR\x10availableBalance\x12?\n" +
	"\tpositions\x18\x04 \x03(\v2!.opensqt.market_maker.v1.PositionR\tpositions\x12)\n" +
	"\x10account_leverage\x18\x05 \x01(\x05R\x0faccountLeverage\x12\x1d\n" +
	"\n" +
	"is_unified\x18\x06 \x01(\bR\tisUnified\x127\n" +
	"\fhealth_score\x18\a \x01(\v2\x14.google.type.DecimalR\vhealthScore\x12D\n" +
	"\vmargin_mode\x18\b \x01(\x0e2#.opensqt.market_maker.v1.MarginModeR\n" +
	"marginMode\x12=\n" +
	"\x0fadjusted_equity\x18\t \x01(\v2\x14.google.type.DecimalR\x0eadjustedEquity\x12N\n" +
	"\x18total_maintenance_margin\x18\n" +
	" \x01(\v2\x14.google.type.DecimalR\x16totalMaintenanceMargin\"\x8f\x04\n" +
	"\bPosition\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12(\n" +
	"\x04size\x18\x02 \x01(\v2\x14.google.type.DecimalR\x04size\x125\n" +
	"\ventry_price\x18\x03 \x01(\v2\x14.google.type.DecimalR\n" +
	"entryPrice\x123\n" +
	"\n" +
	"mark_price\x18\x04 \x01(\v2\x14.google.type.DecimalR\tmarkPrice\x12;\n" +
	"\x0eunrealized_pnl\x18\x05 \x01(\v2\x14.google.type.DecimalR\runrealizedPnl\x12\x1a\n" +
	"\bleverage\x18\x06 \x01(\x05R\bleverage\x12\x1f\n" +
	"\vmargin_type\x18\a \x01(\tR\n" +
	"marginType\x12=\n" +
	"\x0fisolated_margin\x18\b \x01(\v2\x14.google.type.DecimalR\x0eisolatedMargin\x12A\n" +
	"\x11liquidation_price\x18\t \x01(\v2\x14.google.type.DecimalR\x10liquidationPrice\x12.\n" +
	"\ahaircut\x18\n" +
	" \x01(\v2\x14.google.type.DecimalR\ahaircut\x12)\n" +
	"\x10narrative_sector\x18\v \x01(\tR\x0fnarrativeSector\"\xbf\x03\n" +
	"\n" +
	"SymbolInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12'\n" +
	"\x0fprice_precision\x18\x02 \x01(\x05R\x0epricePrecision\x12-\n" +
	"\x12quantity_precision\x18\x03 \x01(\x05R\x11quantityPrecision\x12\x1d\n" +
	"\n" +
	"base_asset\x18\x04 \x01(\tR\tbaseAsset\x12\x1f\n" +
	"\vquote_asset\x18\x05 \x01(\tR\n" +
	"quoteAsset\x127\n" +
	"\fmin_quantity\x18\x06 \x01(\v2\x14.google.type.DecimalR\vminQuantity\x127\n" +
	"\fmin_notional\x18\a \x01(\v2\x14.google.type.DecimalR\vminNotional\x121\n" +
	"\ttick_size\x18\b \x01(\v2\x14.google.type.DecimalR\btickSize\x121\n" +
	"\tstep_size\x18\t \x01(\v2\x14.google.type.DecimalR\bstepSize\x12)\n" +
	"\x10narrative_sector\x18\n" +
	" \x01(\tR\x0fnarrativeSector\"\xa3\x03\n" +
	"\x05Trade\x12\x19\n" +
	"\btrade_id\x18\x01 \x01(\tR\atradeId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x03R\aorderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x126\n" +
	"\x04side\x18\x04 \x01(\x0e2\".opensqt.market_maker.v1.OrderSideR\x04side\x12*\n" +
	"\x05price\x18\x05 \x01(\v2\x14.google.type.DecimalR\x05price\x120\n" +
	"\bquantity\x18\x06 \x01(\v2\x14.google.type.DecimalR\bquantity\x12&\n" +
	"\x03fee\x18\a \x01(\v2\x14.google.type.DecimalR\x03fee\x12\x1b\n" +
	"\tfee_asset\x18\b \x01(\tR\bfeeAsset\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x127\n" +
	"\frealized_pnl\x18\n" +
	" \x01(\v2\x14.google.type.DecimalR\vrealizedPnl\"\xee\x04\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x03R\aorderId\x12&\n" +
	"\x0fclient_order_id\x18\x02 \x01(\tR\rclientOrderId\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x126\n" +
	"\x04side\x18\x04 \x01(\x0e2\".opensqt.market_maker.v1.OrderSideR\x04side\x126\n" +
	"\x04type\x18\x05 \x01(\x0e2\".opensqt.market_maker.v1.OrderTypeR\x04type\x12*\n" +
	"\x05price\x18\x06 \x01(\v2\x14.google.type.DecimalR\x05price\x120\n" +
	"\bquantity\x18\a \x01(\v2\x14.google.type.DecimalR\bquantity\x127\n" +
	"\fexecuted_qty\x18\b \x01(\v2\x14.google.type.DecimalR\vexecutedQty\x121\n" +
	"\tavg_price\x18\t \x01(\v2\x14.google.type.DecimalR\bavgPrice\x12<\n" +
	"\x06status\x18\n" +
	" \x01(\x0e2$.opensqt.market_maker.v1.OrderStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1f\n" +
	"\vupdate_time\x18\f \x01(\x03R\n" +
	"updateTime\x126\n" +
	"\x06trades\x18\r \x03(\v2\x1e.opensqt.market_maker.v1.TradeR\x06trades\"\xb1\x02\n" +
	"\x06Candle\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12(\n" +
	"\x04open\x18\x02 \x01(\v2\x14.google.type.DecimalR\x04open\x12(\n" +
	"\x04high\x18\x03 \x01(\v2\x14.google.type.DecimalR\x04high\x12&\n" +
	"\x03low\x18\x04 \x01(\v2\x14.google.type.DecimalR\x03low\x12*\n" +
	"\x05close\x18\x05 \x01(\v2\x14.google.type.DecimalR\x05close\x12,\n" +
	"\x06volume\x18\x06 \x01(\v2\x14.google.type.DecimalR\x06volume\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tis_closed\x18\b \x01(\bR\bisClosed\"\xf2\x01\n" +
	"\vFundingRate\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12(\n" +
	"\x04rate\x18\x03 \x01(\v2\x14.google.type.DecimalR\x04rate\x12;\n" +
	"\x0epredicted_rate\x18\x04 \x01(\v2\x14.google.type.DecimalR\rpredictedRate\x12*\n" +
	"\x11next_funding_time\x18\x05 \x01(\x03R\x0fnextFundingTime\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"\x96\x03\n" +
	"\x06Ticker\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x127\n" +
	"\fprice_change\x18\x02 \x01(\v2\x14.google.type.DecimalR\vpriceChange\x12F\n" +
	"\x14price_change_percent\x18\x03 \x01(\v2\x14.google.type.DecimalR\x12priceChangePercent\x123\n" +
	"\n" +
	"last_price\x18\x04 \x01(\v2\x14.google.type.DecimalR\tlastPrice\x12,\n" +
	"\x06volume\x18\x05 \x01(\v2\x14.google.type.DecimalR\x06volume\x127\n" +
	"\fquote_volume\x18\x06 \x01(\v2\x14.google.type.DecimalR\vquoteVolume\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x129\n" +
	"\ropen_interest\x18\b \x01(\v2\x14.google.type.DecimalR\fopenInterest\"\xc8\x03\n" +
	"\x11PlaceOrderRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x126\n" +
	"\x04side\x18\x02 \x01(\x0e2\".opensqt.market_maker.v1.OrderSideR\x04side\x126\n" +
	"\x04type\x18\x03 \x01(\x0e2\".opensqt.market_maker.v1.OrderTypeR\x04type\x12H\n" +
	"\rtime_in_force\x18\x04 \x01(\x0e2$.opensqt.market_maker.v1.TimeInForceR\vtimeInForce\x120\n" +
	"\bquantity\x18\x05 \x01(\v2\x14.google.type.DecimalR\bquantity\x12*\n" +
	"\x05price\x18\x06 \x01(\v2\x14.google.type.DecimalR\x05price\x12\x1f\n" +
	"\vreduce_only\x18\a \x01(\bR\n" +
	"reduceOnly\x12\x1b\n" +
	"\tpost_only\x18\b \x01(\bR\bpostOnly\x12&\n" +
	"\x0fclient_order_id\x18\t \x01(\tR\rclientOrderId\x12\x1d\n" +
	"\n" +
	"use_margin\x18\n" +
	" \x01(\bR\tuseMargin\"\xf7\x01\n" +
	"\x15ArbitrageEntryRequest\x12#\n" +
	"\rspot_exchange\x18\x01 \x01(\tR\fspotExchange\x12#\n" +
	"\rperp_exchange\x18\x02 \x01(\tR\fperpExchange\x12I\n" +
	"\n" +
	"spot_order\x18\x03 \x01(\v2*.opensqt.market_maker.v1.PlaceOrderRequestR\tspotOrder\x12I\n" +
	"\n" +
	"perp_order\x18\x04 \x01(\v2*.opensqt.market_maker.v1.PlaceOrderRequestR\tperpOrder\"\xf6\x01\n" +
	"\x14ArbitrageExitRequest\x12#\n" +
	"\rspot_exchange\x18\x01 \x01(\tR\fspotExchange\x12#\n" +
	"\rperp_exchange\x18\x02 \x01(\tR\fperpExchange\x12I\n" +
	"\n" +
	"spot_order\x18\x03 \x01(\v2*.opensqt.market_maker.v1.PlaceOrderRequestR\tspotOrder\x12I\n" +
	"\n" +
	"perp_order\x18\x04 \x01(\v2*.opensqt.market_maker.v1.PlaceOrderRequestR\tperpOrderB\xc1\x01\n" +
	"\x1bcom.opensqt.market_maker.v1B\x0eResourcesProtoP\x01Z\x18market_maker/internal/pb\xa2\x02\x03OMX\xaa\x02\x16Opensqt.MarketMaker.V1\xca\x02\x16Opensqt\\MarketMaker\\V1\xe2\x02\"Opensqt\\MarketMaker\\V1\\GPBMetadata\xea\x02\x18Opensqt::MarketMaker::V1b\x06proto3"

var (
	file_opensqt_market_maker_v1_resources_proto_rawDescOnce sync.Once
	file_opensqt_market_maker_v1_resources_proto_rawDescData []byte
)

func file_opensqt_market_maker_v1_resources_proto_rawDescGZIP() []byte {
	file_opensqt_market_maker_v1_resources_proto_rawDescOnce.Do(func() {
		file_opensqt_market_maker_v1_resources_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_resources_proto_rawDesc), len(file_opensqt_market_maker_v1_resources_proto_rawDesc)))
	})
	return file_opensqt_market_maker_v1_resources_proto_rawDescData
}

var file_opensqt_market_maker_v1_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_opensqt_market_maker_v1_resources_proto_goTypes = []any{
	(*Account)(nil),               // 0: opensqt.market_maker.v1.Account
	(*Position)(nil),              // 1: opensqt.market_maker.v1.Position
	(*SymbolInfo)(nil),            // 2: opensqt.market_maker.v1.SymbolInfo
	(*Trade)(nil),                 // 3: opensqt.market_maker.v1.Trade
	(*Order)(nil),                 // 4: opensqt.market_maker.v1.Order
	(*Candle)(nil),                // 5: opensqt.market_maker.v1.Candle
	(*FundingRate)(nil),           // 6: opensqt.market_maker.v1.FundingRate
	(*Ticker)(nil),                // 7: opensqt.market_maker.v1.Ticker
	(*PlaceOrderRequest)(nil),     // 8: opensqt.market_maker.v1.PlaceOrderRequest
	(*ArbitrageEntryRequest)(nil), // 9: opensqt.market_maker.v1.ArbitrageEntryRequest
	(*ArbitrageExitRequest)(nil),  // 10: opensqt.market_maker.v1.ArbitrageExitRequest
	(*decimal.Decimal)(nil),       // 11: google.type.Decimal
	(MarginMode)(0),               // 12: opensqt.market_maker.v1.MarginMode
	(OrderSide)(0),                // 13: opensqt.market_maker.v1.OrderSide
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
	(OrderType)(0),                // 15: opensqt.market_maker.v1.OrderType
	(OrderStatus)(0),              // 16: opensqt.market_maker.v1.OrderStatus
	(TimeInForce)(0),              // 17: opensqt.market_maker.v1.TimeInForce
}
var file_opensqt_market_maker_v1_resources_proto_depIdxs = []int32{
	11, // 0: opensqt.market_maker.v1.Account.total_wallet_balance:type_name -> google.type.Decimal
	11, // 1: opensqt.market_maker.v1.Account.total_margin_balance:type_name -> google.type.Decimal
	11, // 2: opensqt.market_maker.v1.Account.available_balance:type_name -> google.type.Decimal
	1,  // 3: opensqt.market_maker.v1.Account.positions:type_name -> opensqt.market_maker.v1.Position
	11, // 4: opensqt.market_maker.v1.Account.health_score:type_name -> google.type.Decimal
	12, // 5: opensqt.market_maker.v1.Account.margin_mode:type_name -> opensqt.market_maker.v1.MarginMode
	11, // 6: opensqt.market_maker.v1.Account.adjusted_equity:type_name -> google.type.Decimal
	11, // 7: opensqt.market_maker.v1.Account.total_maintenance_margin:type_name -> google.type.Decimal
	11, // 8: opensqt.market_maker.v1.Position.size:type_name -> google.type.Decimal
	11, // 9: opensqt.market_maker.v1.Position.entry_price:type_name -> google.type.Decimal
	11, // 10: opensqt.market_maker.v1.Position.mark_price:type_name -> google.type.Decimal
	11, // 11: opensqt.market_maker.v1.Position.unrealized_pnl:type_name -> google.type.Decimal
	11, // 12: opensqt.market_maker.v1.Position.isolated_margin:type_name -> google.type.Decimal
	11, // 13: opensqt.market_maker.v1.Position.liquidation_price:type_name -> google.type.Decimal
	11, // 14: opensqt.market_maker.v1.Position.haircut:type_name -> google.type.Decimal
	11, // 15: opensqt.market_maker.v1.SymbolInfo.min_quantity:type_name -> google.type.Decimal
	11, // 16: opensqt.market_maker.v1.SymbolInfo.min_notional:type_name -> google.type.Decimal
	11, // 17: opensqt.market_maker.v1.SymbolInfo.tick_size:type_name -> google.type.Decimal
	11, // 18: opensqt.market_maker.v1.SymbolInfo.step_size:type_name -> google.type.Decimal
	13, // 19: opensqt.market_maker.v1.Trade.side:type_name -> opensqt.market_maker.v1.OrderSide
	11, // 20: opensqt.market_maker.v1.Trade.price:type_name -> google.type.Decimal
	11, // 21: opensqt.market_maker.v1.Trade.quantity:type_name -> google.type.Decimal
	11, // 22: opensqt.market_maker.v1.Trade.fee:type_name -> google.type.Decimal
	14, // 23: opensqt.market_maker.v1.Trade.timestamp:type_name -> google.protobuf.Timestamp
	11, // 24: opensqt.market_maker.v1.Trade.realized_pnl:type_name -> google.type.Decimal
	13, // 25: opensqt.market_maker.v1.Order.side:type_name -> opensqt.market_maker.v1.OrderSide
	15, // 26: opensqt.market_maker.v1.Order.type:type_name -> opensqt.market_maker.v1.OrderType
	11, // 27: opensqt.market_maker.v1.Order.price:type_name -> google.type.Decimal
	11, // 28: opensqt.market_maker.v1.Order.quantity:type_name -> google.type.Decimal
	11, // 29: opensqt.market_maker.v1.Order.executed_qty:type_name -> google.type.Decimal
	11, // 30: opensqt.market_maker.v1.Order.avg_price:type_name -> google.type.Decimal
	16, // 31: opensqt.market_maker.v1.Order.status:type_name -> opensqt.market_maker.v1.OrderStatus
	14, // 32: opensqt.market_maker.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	3,  // 33: opensqt.market_maker.v1.Order.trades:type_name -> opensqt.market_maker.v1.Trade
	11, // 34: opensqt.market_maker.v1.Candle.open:type_name -> google.type.Decimal
	11, // 35: opensqt.market_maker.v1.Candle.high:type_name -> google.type.Decimal
	11, // 36: opensqt.market_maker.v1.Candle.low:type_name -> google.type.Decimal
	11, // 37: opensqt.market_maker.v1.Candle.close:type_name -> google.type.Decimal
	11, // 38: opensqt.market_maker.v1.Candle.volume:type_name -> google.type.Decimal
	11, // 39: opensqt.market_maker.v1.FundingRate.rate:type_name -> google.type.Decimal
	11, // 40: opensqt.market_maker.v1.FundingRate.predicted_rate:type_name -> google.type.Decimal
	11, // 41: opensqt.market_maker.v1.Ticker.price_change:type_name -> google.type.Decimal
	11, // 42: opensqt.market_maker.v1.Ticker.price_change_percent:type_name -> google.type.Decimal
	11, // 43: opensqt.market_maker.v1.Ticker.last_price:type_name -> google.type.Decimal
	11, // 44: opensqt.market_maker.v1.Ticker.volume:type_name -> google.type.Decimal
	11, // 45: opensqt.market_maker.v1.Ticker.quote_volume:type_name -> google.type.Decimal
	11, // 46: opensqt.market_maker.v1.Ticker.open_interest:type_name -> google.type.Decimal
	13, // 47: opensqt.market_maker.v1.PlaceOrderRequest.side:type_name -> opensqt.market_maker.v1.OrderSide
	15, // 48: opensqt.market_maker.v1.PlaceOrderRequest.type:type_name -> opensqt.market_maker.v1.OrderType
	17, // 49: opensqt.market_maker.v1.PlaceOrderRequest.time_in_force:type_name -> opensqt.market_maker.v1.TimeInForce
	11, // 50: opensqt.market_maker.v1.PlaceOrderRequest.quantity:type_name -> google.type.Decimal
	11, // 51: opensqt.market_maker.v1.PlaceOrderRequest.price:type_name -> google.type.Decimal
	8,  // 52: opensqt.market_maker.v1.ArbitrageEntryRequest.spot_order:type_name -> opensqt.market_maker.v1.PlaceOrderRequest
	8,  // 53: opensqt.market_maker.v1.ArbitrageEntryRequest.perp_order:type_name -> opensqt.market_maker.v1.PlaceOrderRequest
	8,  // 54: opensqt.market_maker.v1.ArbitrageExitRequest.spot_order:type_name -> opensqt.market_maker.v1.PlaceOrderRequest
	8,  // 55: opensqt.market_maker.v1.ArbitrageExitRequest.perp_order:type_name -> opensqt.market_maker.v1.PlaceOrderRequest
	56, // [56:56] is the sub-list for method output_type
	56, // [56:56] is the sub-list for method input_type
	56, // [56:56] is the sub-list for extension type_name
	56, // [56:56] is the sub-list for extension extendee
	0,  // [0:56] is the sub-list for field type_name
}

func init() { file_opensqt_market_maker_v1_resources_proto_init() }
func file_opensqt_market_maker_v1_resources_proto_init() {
	if File_opensqt_market_maker_v1_resources_proto != nil {
		return
	}
	file_opensqt_market_maker_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_resources_proto_rawDesc), len(file_opensqt_market_maker_v1_resources_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opensqt_market_maker_v1_resources_proto_goTypes,
		DependencyIndexes: file_opensqt_market_maker_v1_resources_proto_depIdxs,
		MessageInfos:      file_opensqt_market_maker_v1_resources_proto_msgTypes,
	}.Build()
	File_opensqt_market_maker_v1_resources_proto = out.File
	file_opensqt_market_maker_v1_resources_proto_goTypes = nil
	file_opensqt_market_maker_v1_resources_proto_depIdxs = nil
}
