// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: opensqt/market_maker/v1/state.proto

package pb

import (
	decimal "google.golang.org/genproto/googleapis/type/decimal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InventorySlot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Price             *decimal.Decimal       `protobuf:"bytes,1,opt,name=price,proto3" json:"price,omitempty"`
	PositionStatus    PositionStatus         `protobuf:"varint,2,opt,name=position_status,json=positionStatus,proto3,enum=opensqt.market_maker.v1.PositionStatus" json:"position_status,omitempty"`
	PositionQty       *decimal.Decimal       `protobuf:"bytes,3,opt,name=position_qty,json=positionQty,proto3" json:"position_qty,omitempty"`
	OrderId           int64                  `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ClientOid         string                 `protobuf:"bytes,5,opt,name=client_oid,json=clientOid,proto3" json:"client_oid,omitempty"`
	OrderSide         OrderSide              `protobuf:"varint,6,opt,name=order_side,json=orderSide,proto3,enum=opensqt.market_maker.v1.OrderSide" json:"order_side,omitempty"`
	OrderStatus       OrderStatus            `protobuf:"varint,7,opt,name=order_status,json=orderStatus,proto3,enum=opensqt.market_maker.v1.OrderStatus" json:"order_status,omitempty"`
	OrderPrice        *decimal.Decimal       `protobuf:"bytes,8,opt,name=order_price,json=orderPrice,proto3" json:"order_price,omitempty"`
	OrderFilledQty    *decimal.Decimal       `protobuf:"bytes,9,opt,name=order_filled_qty,json=orderFilledQty,proto3" json:"order_filled_qty,omitempty"`
	SlotStatus        SlotStatus             `protobuf:"varint,10,opt,name=slot_status,json=slotStatus,proto3,enum=opensqt.market_maker.v1.SlotStatus" json:"slot_status,omitempty"`
	PostOnlyFailCount int32                  `protobuf:"varint,11,opt,name=post_only_fail_count,json=postOnlyFailCount,proto3" json:"post_only_fail_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InventorySlot) Reset() {
	*x = InventorySlot{}
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventorySlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventorySlot) ProtoMessage() {}

func (x *InventorySlot) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventorySlot.ProtoReflect.Descriptor instead.
func (*InventorySlot) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *InventorySlot) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *InventorySlot) GetPositionStatus() PositionStatus {
	if x != nil {
		return x.PositionStatus
	}
	return PositionStatus_POSITION_STATUS_UNSPECIFIED
}

func (x *InventorySlot) GetPositionQty() *decimal.Decimal {
	if x != nil {
		return x.PositionQty
	}
	return nil
}

func (x *InventorySlot) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *InventorySlot) GetClientOid() string {
	if x != nil {
		return x.ClientOid
	}
	return ""
}

func (x *InventorySlot) GetOrderSide() OrderSide {
	if x != nil {
		return x.OrderSide
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *InventorySlot) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *InventorySlot) GetOrderPrice() *decimal.Decimal {
	if x != nil {
		return x.OrderPrice
	}
	return nil
}

func (x *InventorySlot) GetOrderFilledQty() *decimal.Decimal {
	if x != nil {
		return x.OrderFilledQty
	}
	return nil
}

func (x *InventorySlot) GetSlotStatus() SlotStatus {
	if x != nil {
		return x.SlotStatus
	}
	return SlotStatus_SLOT_STATUS_UNSPECIFIED
}

func (x *InventorySlot) GetPostOnlyFailCount() int32 {
	if x != nil {
		return x.PostOnlyFailCount
	}
	return 0
}

type State struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Slots           map[string]*InventorySlot `protobuf:"bytes,1,rep,name=slots,proto3" json:"slots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LastPrice       *decimal.Decimal          `protobuf:"bytes,2,opt,name=last_price,json=lastPrice,proto3" json:"last_price,omitempty"`
	LastUpdateTime  int64                     `protobuf:"varint,3,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	Symbol          string                    `protobuf:"bytes,4,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Version         int64                     `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Checksum        string                    `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	IsRiskTriggered bool                      `protobuf:"varint,7,opt,name=is_risk_triggered,json=isRiskTriggered,proto3" json:"is_risk_triggered,omitempty"`
	OrderIndex      map[int64]string          `protobuf:"bytes,8,rep,name=order_index,json=orderIndex,proto3" json:"order_index,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *State) GetSlots() map[string]*InventorySlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *State) GetLastPrice() *decimal.Decimal {
	if x != nil {
		return x.LastPrice
	}
	return nil
}

func (x *State) GetLastUpdateTime() int64 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

func (x *State) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *State) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *State) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *State) GetIsRiskTriggered() bool {
	if x != nil {
		return x.IsRiskTriggered
	}
	return false
}

func (x *State) GetOrderIndex() map[int64]string {
	if x != nil {
		return x.OrderIndex
	}
	return nil
}

type PositionManagerSnapshot struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	Symbol         string                    `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Slots          map[string]*InventorySlot `protobuf:"bytes,2,rep,name=slots,proto3" json:"slots,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AnchorPrice    *decimal.Decimal          `protobuf:"bytes,3,opt,name=anchor_price,json=anchorPrice,proto3" json:"anchor_price,omitempty"`
	TotalSlots     int64                     `protobuf:"varint,4,opt,name=total_slots,json=totalSlots,proto3" json:"total_slots,omitempty"`
	ActiveSlots    int64                     `protobuf:"varint,5,opt,name=active_slots,json=activeSlots,proto3" json:"active_slots,omitempty"`
	MarginLocked   bool                      `protobuf:"varint,6,opt,name=margin_locked,json=marginLocked,proto3" json:"margin_locked,omitempty"`
	LastUpdateTime int64                     `protobuf:"varint,7,opt,name=last_update_time,json=lastUpdateTime,proto3" json:"last_update_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PositionManagerSnapshot) Reset() {
	*x = PositionManagerSnapshot{}
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PositionManagerSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PositionManagerSnapshot) ProtoMessage() {}

func (x *PositionManagerSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PositionManagerSnapshot.ProtoReflect.Descriptor instead.
func (*PositionManagerSnapshot) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *PositionManagerSnapshot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PositionManagerSnapshot) GetSlots() map[string]*InventorySlot {
	if x != nil {
		return x.Slots
	}
	return nil
}

func (x *PositionManagerSnapshot) GetAnchorPrice() *decimal.Decimal {
	if x != nil {
		return x.AnchorPrice
	}
	return nil
}

func (x *PositionManagerSnapshot) GetTotalSlots() int64 {
	if x != nil {
		return x.TotalSlots
	}
	return 0
}

func (x *PositionManagerSnapshot) GetActiveSlots() int64 {
	if x != nil {
		return x.ActiveSlots
	}
	return 0
}

func (x *PositionManagerSnapshot) GetMarginLocked() bool {
	if x != nil {
		return x.MarginLocked
	}
	return false
}

func (x *PositionManagerSnapshot) GetLastUpdateTime() int64 {
	if x != nil {
		return x.LastUpdateTime
	}
	return 0
}

type OrderAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          OrderActionType        `protobuf:"varint,1,opt,name=type,proto3,enum=opensqt.market_maker.v1.OrderActionType" json:"type,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	OrderId       int64                  `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Price         *decimal.Decimal       `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	Request       *PlaceOrderRequest     `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAction) Reset() {
	*x = OrderAction{}
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAction) ProtoMessage() {}

func (x *OrderAction) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAction.ProtoReflect.Descriptor instead.
func (*OrderAction) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *OrderAction) GetType() OrderActionType {
	if x != nil {
		return x.Type
	}
	return OrderActionType_ORDER_ACTION_TYPE_UNSPECIFIED
}

func (x *OrderAction) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OrderAction) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderAction) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *OrderAction) GetRequest() *PlaceOrderRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type TargetPositionState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Size          *decimal.Decimal       `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetPositionState) Reset() {
	*x = TargetPositionState{}
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetPositionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetPositionState) ProtoMessage() {}

func (x *TargetPositionState) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetPositionState.ProtoReflect.Descriptor instead.
func (*TargetPositionState) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_state_proto_rawDescGZIP(), []int{4}
}

func (x *TargetPositionState) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *TargetPositionState) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TargetPositionState) GetSize() *decimal.Decimal {
	if x != nil {
		return x.Size
	}
	return nil
}

type TargetOrder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         *decimal.Decimal       `protobuf:"bytes,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      *decimal.Decimal       `protobuf:"bytes,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Side          OrderSide              `protobuf:"varint,5,opt,name=side,proto3,enum=opensqt.market_maker.v1.OrderSide" json:"side,omitempty"`
	Type          OrderType              `protobuf:"varint,6,opt,name=type,proto3,enum=opensqt.market_maker.v1.OrderType" json:"type,omitempty"`
	ClientOrderId string                 `protobuf:"bytes,7,opt,name=client_order_id,json=clientOrderId,proto3" json:"client_order_id,omitempty"`
	ReduceOnly    bool                   `protobuf:"varint,8,opt,name=reduce_only,json=reduceOnly,proto3" json:"reduce_only,omitempty"`
	PostOnly      bool                   `protobuf:"varint,9,opt,name=post_only,json=postOnly,proto3" json:"post_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetOrder) Reset() {
	*x = TargetOrder{}
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetOrder) ProtoMessage() {}

func (x *TargetOrder) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetOrder.ProtoReflect.Descriptor instead.
func (*TargetOrder) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *TargetOrder) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *TargetOrder) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TargetOrder) GetPrice() *decimal.Decimal {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *TargetOrder) GetQuantity() *decimal.Decimal {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *TargetOrder) GetSide() OrderSide {
	if x != nil {
		return x.Side
	}
	return OrderSide_ORDER_SIDE_UNSPECIFIED
}

func (x *TargetOrder) GetType() OrderType {
	if x != nil {
		return x.Type
	}
	return OrderType_ORDER_TYPE_UNSPECIFIED
}

func (x *TargetOrder) GetClientOrderId() string {
	if x != nil {
		return x.ClientOrderId
	}
	return ""
}

func (x *TargetOrder) GetReduceOnly() bool {
	if x != nil {
		return x.ReduceOnly
	}
	return false
}

func (x *TargetOrder) GetPostOnly() bool {
	if x != nil {
		return x.PostOnly
	}
	return false
}

type TargetState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Positions     []*TargetPositionState `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	Orders        []*TargetOrder         `protobuf:"bytes,3,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetState) Reset() {
	*x = TargetState{}
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetState) ProtoMessage() {}

func (x *TargetState) ProtoReflect() protoreflect.Message {
	mi := &file_opensqt_market_maker_v1_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetState.ProtoReflect.Descriptor instead.
func (*TargetState) Descriptor() ([]byte, []int) {
	return file_opensqt_market_maker_v1_state_proto_rawDescGZIP(), []int{6}
}

func (x *TargetState) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TargetState) GetPositions() []*TargetPositionState {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *TargetState) GetOrders() []*TargetOrder {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_opensqt_market_maker_v1_state_proto protoreflect.FileDescriptor

const file_opensqt_market_maker_v1_state_proto_rawDesc = "" +
	"\n" +
	"#opensqt/market_maker/v1/state.proto\x12\x17opensqt.market_maker.v1\x1a\x19google/type/decimal.proto\x1a#opensqt/market_maker/v1/types.proto\x1a'opensqt/market_maker/v1/resources.proto\"\xfa\x04\n" +
	"\rInventorySlot\x12*\n" +
	"\x05price\x18\x01 \x01(\v2\x14.google.type.DecimalR\x05price\x12P\n" +
	"\x0fposition_status\x18\x02 \x01(\x0e2'.opensqt.market_maker.v1.PositionStatusR\x0epositionStatus\x127\n" +
	"\fposition_qty\x18\x03 \x01(\v2\x14.google.type.DecimalR\vpositionQty\x12\x19\n" +
	"\border_id\x18\x04 \x01(\x03R\aorderId\x12\x1d\n" +
	"\n" +
	"client_oid\x18\x05 \x01(\tR\tclientOid\x12A\n" +
	"\n" +
	"order_side\x18\x06 \x01(\x0e2\".opensqt.market_maker.v1.OrderSideR\torderSide\x12G\n" +
	"\forder_status\x18\a \x01(\x0e2$.opensqt.market_maker.v1.OrderStatusR\vorderStatus\x125\n" +
	"\vorder_price\x18\b \x01(\v2\x14.google.type.DecimalR\n" +
	"orderPrice\x12>\n" +
	"\x10order_filled_qty\x18\t \x01(\v2\x14.google.type.DecimalR\x0eorderFilledQty\x12D\n" +
	"\vslot_status\x18\n" +
	" \x01(\x0e2#.opensqt.market_maker.v1.SlotStatusR\n" +
	"slotStatus\x12/\n" +
	"\x14post_only_fail_count\x18\v \x01(\x05R\x11postOnlyFailCount\"\x93\x04\n" +
	"\x05State\x12?\n" +
	"\x05slots\x18\x01 \x03(\v2).opensqt.market_maker.v1.State.SlotsEntryR\x05slots\x123\n" +
	"\n" +
	"last_price\x18\x02 \x01(\v2\x14.google.type.DecimalR\tlastPrice\x12(\n" +
	"\x10last_update_time\x18\x03 \x01(\x03R\x0elastUpdateTime\x12\x16\n" +
	"\x06symbol\x18\x04 \x01(\tR\x06symbol\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x1a\n" +
	"\bchecksum\x18\x06 \x01(\tR\bchecksum\x12*\n" +
	"\x11is_risk_triggered\x18\a \x01(\bR\x0fisRiskTriggered\x12O\n" +
	"\vorder_index\x18\b \x03(\v2..opensqt.market_maker.v1.State.OrderIndexEntryR\n" +
	"orderIndex\x1a`\n" +
	"\n" +
	"SlotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.opensqt.market_maker.v1.InventorySlotR\x05value:\x028\x01\x1a=\n" +
	"\x0fOrderIndexEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb2\x03\n" +
	"\x17PositionManagerSnapshot\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12Q\n" +
	"\x05slots\x18\x02 \x03(\v2;.opensqt.market_maker.v1.PositionManagerSnapshot.SlotsEntryR\x05slots\x127\n" +
	"\fanchor_price\x18\x03 \x01(\v2\x14.google.type.DecimalR\vanchorPrice\x12\x1f\n" +
	"\vtotal_slots\x18\x04 \x01(\x03R\n" +
	"totalSlots\x12!\n" +
	"\factive_slots\x18\x05 \x01(\x03R\vactiveSlots\x12#\n" +
	"\rmargin_locked\x18\x06 \x01(\bR\fmarginLocked\x12(\n" +
	"\x10last_update_time\x18\a \x01(\x03R\x0elastUpdateTime\x1a`\n" +
	"\n" +
	"SlotsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\x05value\x18\x02 \x01(\v2&.opensqt.market_maker.v1.InventorySlotR\x05value:\x028\x01\"\xf0\x01\n" +
	"\vOrderAction\x12<\n" +
	"\x04type\x18\x01 \x01(\x0e2(.opensqt.market_maker.v1.OrderActionTypeR\x04type\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x03R\aorderId\x12*\n" +
	"\x05price\x18\x04 \x01(\v2\x14.google.type.DecimalR\x05price\x12D\n" +
	"\arequest\x18\x05 \x01(\v2*.opensqt.market_maker.v1.PlaceOrderRequestR\arequest\"s\n" +
	"\x13TargetPositionState\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12(\n" +
	"\x04size\x18\x03 \x01(\v2\x14.google.type.DecimalR\x04size\"\xf5\x02\n" +
	"\vTargetOrder\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12*\n" +
	"\x05price\x18\x03 \x01(\v2\x14.google.type.DecimalR\x05price\x120\n" +
	"\bquantity\x18\x04 \x01(\v2\x14.google.type.DecimalR\bquantity\x126\n" +
	"\x04side\x18\x05 \x01(\x0e2\".opensqt.market_maker.v1.OrderSideR\x04side\x126\n" +
	"\x04type\x18\x06 \x01(\x0e2\".opensqt.market_maker.v1.OrderTypeR\x04type\x12&\n" +
	"\x0fclient_order_id\x18\a \x01(\tR\rclientOrderId\x12\x1f\n" +
	"\vreduce_only\x18\b \x01(\bR\n" +
	"reduceOnly\x12\x1b\n" +
	"\tpost_only\x18\t \x01(\bR\bpostOnly\"\xb5\x01\n" +
	"\vTargetState\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12J\n" +
	"\tpositions\x18\x02 \x03(\v2,.opensqt.market_maker.v1.TargetPositionStateR\tpositions\x12<\n" +
	"\x06orders\x18\x03 \x03(\v2$.opensqt.market_maker.v1.TargetOrderR\x06ordersB\xbd\x01\n" +
	"\x1bcom.opensqt.market_maker.v1B\n" +
	"StateProtoP\x01Z\x18market_maker/internal/pb\xa2\x02\x03OMX\xaa\x02\x16Opensqt.MarketMaker.V1\xca\x02\x16Opensqt\\MarketMaker\\V1\xe2\x02\"Opensqt\\MarketMaker\\V1\\GPBMetadata\xea\x02\x18Opensqt::MarketMaker::V1b\x06proto3"

var (
	file_opensqt_market_maker_v1_state_proto_rawDescOnce sync.Once
	file_opensqt_market_maker_v1_state_proto_rawDescData []byte
)

func file_opensqt_market_maker_v1_state_proto_rawDescGZIP() []byte {
	file_opensqt_market_maker_v1_state_proto_rawDescOnce.Do(func() {
		file_opensqt_market_maker_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_state_proto_rawDesc), len(file_opensqt_market_maker_v1_state_proto_rawDesc)))
	})
	return file_opensqt_market_maker_v1_state_proto_rawDescData
}

var file_opensqt_market_maker_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_opensqt_market_maker_v1_state_proto_goTypes = []any{
	(*InventorySlot)(nil),           // 0: opensqt.market_maker.v1.InventorySlot
	(*State)(nil),                   // 1: opensqt.market_maker.v1.State
	(*PositionManagerSnapshot)(nil), // 2: opensqt.market_maker.v1.PositionManagerSnapshot
	(*OrderAction)(nil),             // 3: opensqt.market_maker.v1.OrderAction
	(*TargetPositionState)(nil),     // 4: opensqt.market_maker.v1.TargetPositionState
	(*TargetOrder)(nil),             // 5: opensqt.market_maker.v1.TargetOrder
	(*TargetState)(nil),             // 6: opensqt.market_maker.v1.TargetState
	nil,                             // 7: opensqt.market_maker.v1.State.SlotsEntry
	nil,                             // 8: opensqt.market_maker.v1.State.OrderIndexEntry
	nil,                             // 9: opensqt.market_maker.v1.PositionManagerSnapshot.SlotsEntry
	(*decimal.Decimal)(nil),         // 10: google.type.Decimal
	(PositionStatus)(0),             // 11: opensqt.market_maker.v1.PositionStatus
	(OrderSide)(0),                  // 12: opensqt.market_maker.v1.OrderSide
	(OrderStatus)(0),                // 13: opensqt.market_maker.v1.OrderStatus
	(SlotStatus)(0),                 // 14: opensqt.market_maker.v1.SlotStatus
	(OrderActionType)(0),            // 15: opensqt.market_maker.v1.OrderActionType
	(*PlaceOrderRequest)(nil),       // 16: opensqt.market_maker.v1.PlaceOrderRequest
	(OrderType)(0),                  // 17: opensqt.market_maker.v1.OrderType
}
var file_opensqt_market_maker_v1_state_proto_depIdxs = []int32{
	10, // 0: opensqt.market_maker.v1.InventorySlot.price:type_name -> google.type.Decimal
	11, // 1: opensqt.market_maker.v1.InventorySlot.position_status:type_name -> opensqt.market_maker.v1.PositionStatus
	10, // 2: opensqt.market_maker.v1.InventorySlot.position_qty:type_name -> google.type.Decimal
	12, // 3: opensqt.market_maker.v1.InventorySlot.order_side:type_name -> opensqt.market_maker.v1.OrderSide
	13, // 4: opensqt.market_maker.v1.InventorySlot.order_status:type_name -> opensqt.market_maker.v1.OrderStatus
	10, // 5: opensqt.market_maker.v1.InventorySlot.order_price:type_name -> google.type.Decimal
	10, // 6: opensqt.market_maker.v1.InventorySlot.order_filled_qty:type_name -> google.type.Decimal
	14, // 7: opensqt.market_maker.v1.InventorySlot.slot_status:type_name -> opensqt.market_maker.v1.SlotStatus
	7,  // 8: opensqt.market_maker.v1.State.slots:type_name -> opensqt.market_maker.v1.State.SlotsEntry
	10, // 9: opensqt.market_maker.v1.State.last_price:type_name -> google.type.Decimal
	8,  // 10: opensqt.market_maker.v1.State.order_index:type_name -> opensqt.market_maker.v1.State.OrderIndexEntry
	9,  // 11: opensqt.market_maker.v1.PositionManagerSnapshot.slots:type_name -> opensqt.market_maker.v1.PositionManagerSnapshot.SlotsEntry
	10, // 12: opensqt.market_maker.v1.PositionManagerSnapshot.anchor_price:type_name -> google.type.Decimal
	15, // 13: opensqt.market_maker.v1.OrderAction.type:type_name -> opensqt.market_maker.v1.OrderActionType
	10, // 14: opensqt.market_maker.v1.OrderAction.price:type_name -> google.type.Decimal
	16, // 15: opensqt.market_maker.v1.OrderAction.request:type_name -> opensqt.market_maker.v1.PlaceOrderRequest
	10, // 16: opensqt.market_maker.v1.TargetPositionState.size:type_name -> google.type.Decimal
	10, // 17: opensqt.market_maker.v1.TargetOrder.price:type_name -> google.type.Decimal
	10, // 18: opensqt.market_maker.v1.TargetOrder.quantity:type_name -> google.type.Decimal
	12, // 19: opensqt.market_maker.v1.TargetOrder.side:type_name -> opensqt.market_maker.v1.OrderSide
	17, // 20: opensqt.market_maker.v1.TargetOrder.type:type_name -> opensqt.market_maker.v1.OrderType
	4,  // 21: opensqt.market_maker.v1.TargetState.positions:type_name -> opensqt.market_maker.v1.TargetPositionState
	5,  // 22: opensqt.market_maker.v1.TargetState.orders:type_name -> opensqt.market_maker.v1.TargetOrder
	0,  // 23: opensqt.market_maker.v1.State.SlotsEntry.value:type_name -> opensqt.market_maker.v1.InventorySlot
	0,  // 24: opensqt.market_maker.v1.PositionManagerSnapshot.SlotsEntry.value:type_name -> opensqt.market_maker.v1.InventorySlot
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_opensqt_market_maker_v1_state_proto_init() }
func file_opensqt_market_maker_v1_state_proto_init() {
	if File_opensqt_market_maker_v1_state_proto != nil {
		return
	}
	file_opensqt_market_maker_v1_types_proto_init()
	file_opensqt_market_maker_v1_resources_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opensqt_market_maker_v1_state_proto_rawDesc), len(file_opensqt_market_maker_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opensqt_market_maker_v1_state_proto_goTypes,
		DependencyIndexes: file_opensqt_market_maker_v1_state_proto_depIdxs,
		MessageInfos:      file_opensqt_market_maker_v1_state_proto_msgTypes,
	}.Build()
	File_opensqt_market_maker_v1_state_proto = out.File
	file_opensqt_market_maker_v1_state_proto_goTypes = nil
	file_opensqt_market_maker_v1_state_proto_depIdxs = nil
}
